const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const helpers = @import("test_helpers.zig");
const lazyCollectTable = helpers.lazyCollectTable;
const lazyQualityTable = helpers.lazyQualityTable;

test "device lazy frame collects class operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var class_plan = try DeviceLazyFrame.init(gpa, table);
    defer class_plan.deinit();
    try class_plan.withColumnCompareScalar("predicted_active", "sales", f64, 4.0, .gt);
    try class_plan.classificationProfile("active", "predicted_active", "active_cls");
    try class_plan.select(&.{ "active", "predicted_active", "active_cls_tp", "active_cls_fp", "active_cls_tn", "active_cls_fn", "active_cls_correct" });
    const class_explain = try class_plan.explain(gpa);
    defer gpa.free(class_explain);
    try std.testing.expect(std.mem.indexOf(u8, class_explain, "classification_profile(actual=active, predicted=predicted_active") != null);
    var classed = try class_plan.collect();
    defer classed.deinit();
    try std.testing.expectEqual(@as(usize, 4), classed.height());
    try std.testing.expectEqual(@as(usize, 7), classed.width());
    const lazy_tp = try (try classed.column("active_cls_tp")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_tp);
    const lazy_fp = try (try classed.column("active_cls_fp")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_fp);
    const lazy_tn = try (try classed.column("active_cls_tn")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_tn);
    const lazy_fn = try (try classed.column("active_cls_fn")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_fn);
    const lazy_correct = try (try classed.column("active_cls_correct")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_correct);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_tp);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_fp);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false }, lazy_tn);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false }, lazy_fn);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_correct);
}

test "device lazy frame collects rolling class operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_class_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_class_plan.deinit();
    try rolling_class_plan.withColumnCompareScalar("predicted_active", "sales", f64, 4.0, .gt);
    try rolling_class_plan.rollingClassificationProfile("active", "predicted_active", "active_cls", .{ .window = 2, .min_periods = 2 });
    try rolling_class_plan.select(&.{ "active", "predicted_active", "active_cls_rolling_class_count", "active_cls_rolling_tp_count", "active_cls_rolling_fp_count", "active_cls_rolling_tn_count", "active_cls_rolling_fn_count", "active_cls_rolling_accuracy", "active_cls_rolling_precision", "active_cls_rolling_recall" });
    const rolling_class_explain = try rolling_class_plan.explain(gpa);
    defer gpa.free(rolling_class_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_class_explain, "rolling_classification_profile(actual=active, predicted=predicted_active") != null);
    var lazy_rolling_class = try rolling_class_plan.collect();
    defer lazy_rolling_class.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_class.height());
    try std.testing.expectEqual(@as(usize, 10), lazy_rolling_class.width());
    const lazy_rolling_class_count = try (try lazy_rolling_class.column("active_cls_rolling_class_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_class_count);
    const lazy_rolling_tp_count = try (try lazy_rolling_class.column("active_cls_rolling_tp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_tp_count);
    const lazy_rolling_fp_count = try (try lazy_rolling_class.column("active_cls_rolling_fp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fp_count);
    const lazy_rolling_tn_count = try (try lazy_rolling_class.column("active_cls_rolling_tn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_tn_count);
    const lazy_rolling_fn_count = try (try lazy_rolling_class.column("active_cls_rolling_fn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fn_count);
    const lazy_rolling_accuracy = try (try lazy_rolling_class.column("active_cls_rolling_accuracy")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_accuracy);
    const lazy_rolling_precision = try (try lazy_rolling_class.column("active_cls_rolling_precision")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_precision);
    const lazy_rolling_recall = try (try lazy_rolling_class.column("active_cls_rolling_recall")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_recall);
    const lazy_rolling_class_validity = try (try lazy_rolling_class.column("active_cls_rolling_accuracy")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_class_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_class_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_rolling_tp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_rolling_fp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_rolling_tn_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 0, 0 }, lazy_rolling_fn_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_class_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_accuracy[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_accuracy[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_accuracy[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_rolling_precision[1]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_precision[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_precision[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_recall[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_recall[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_recall[3], 1e-12);
}

test "device lazy frame collects expanding class operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_class_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_class_plan.deinit();
    try expanding_class_plan.withColumnCompareScalar("predicted_active", "sales", f64, 4.0, .gt);
    try expanding_class_plan.expandingClassificationProfile("active", "predicted_active", "active_cls", .{ .min_periods = 2 });
    try expanding_class_plan.select(&.{ "active", "predicted_active", "active_cls_expanding_class_count", "active_cls_expanding_tp_count", "active_cls_expanding_fp_count", "active_cls_expanding_tn_count", "active_cls_expanding_fn_count", "active_cls_expanding_accuracy", "active_cls_expanding_precision", "active_cls_expanding_recall" });
    const expanding_class_explain = try expanding_class_plan.explain(gpa);
    defer gpa.free(expanding_class_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_class_explain, "expanding_classification_profile(actual=active, predicted=predicted_active") != null);
    var lazy_expanding_class = try expanding_class_plan.collect();
    defer lazy_expanding_class.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_class.height());
    try std.testing.expectEqual(@as(usize, 10), lazy_expanding_class.width());
    const lazy_expanding_class_count = try (try lazy_expanding_class.column("active_cls_expanding_class_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_class_count);
    const lazy_expanding_tp_count = try (try lazy_expanding_class.column("active_cls_expanding_tp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_tp_count);
    const lazy_expanding_fp_count = try (try lazy_expanding_class.column("active_cls_expanding_fp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fp_count);
    const lazy_expanding_tn_count = try (try lazy_expanding_class.column("active_cls_expanding_tn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_tn_count);
    const lazy_expanding_fn_count = try (try lazy_expanding_class.column("active_cls_expanding_fn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fn_count);
    const lazy_expanding_accuracy = try (try lazy_expanding_class.column("active_cls_expanding_accuracy")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_accuracy);
    const lazy_expanding_precision = try (try lazy_expanding_class.column("active_cls_expanding_precision")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_precision);
    const lazy_expanding_recall = try (try lazy_expanding_class.column("active_cls_expanding_recall")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_recall);
    const lazy_expanding_class_validity = try (try lazy_expanding_class.column("active_cls_expanding_accuracy")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_class_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_class_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_expanding_tp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_expanding_fp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_tn_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 1 }, lazy_expanding_fn_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_class_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_accuracy[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_accuracy[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_expanding_accuracy[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_expanding_precision[1]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_precision[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_precision[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_recall[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_recall[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_recall[3], 1e-12);
}
