const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("test_helpers.zig").lazyCollectTable;

test "device lazy frame collects crossover operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var crossover_plan = try DeviceLazyFrame.init(gpa, table);
    defer crossover_plan.deinit();
    try crossover_plan.withColumnScalar("units_f64", "sales", f64, 1.0, .sub);
    try crossover_plan.crossoverProfile("sales", "units_f64", "sales_units", .{ .periods = 1 });
    try crossover_plan.select(&.{ "sales", "units_f64", "sales_units_spread", "sales_units_ratio", "sales_units_cross_above", "sales_units_cross_below" });
    const crossover_explain = try crossover_plan.explain(gpa);
    defer gpa.free(crossover_explain);
    try std.testing.expect(std.mem.indexOf(u8, crossover_explain, "crossover_profile(sales,units_f64") != null);
    var crossover = try crossover_plan.collect();
    defer crossover.deinit();
    try std.testing.expectEqual(@as(usize, 4), crossover.height());
    try std.testing.expectEqual(@as(usize, 6), crossover.width());
    const lazy_spread = try (try crossover.column("sales_units_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_spread);
    const lazy_ratio = try (try crossover.column("sales_units_ratio")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ratio);
    const lazy_cross_above = try (try crossover.column("sales_units_cross_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_cross_above);
    const lazy_cross_below = try (try crossover.column("sales_units_cross_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_cross_below);
    const lazy_cross_validity = try (try crossover.column("sales_units_cross_above")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_cross_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_cross_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_ratio[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_ratio[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), lazy_ratio[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0 / 6.0), lazy_ratio[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_cross_above);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_cross_below);
}

test "device lazy frame collects rolling crossover operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_crossover_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_crossover_plan.deinit();
    try rolling_crossover_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try rolling_crossover_plan.withColumnScalar("zero_sales", "sales", f64, 0.0, .mul);
    try rolling_crossover_plan.rollingCrossoverProfile("sales_minus4", "zero_sales", "sales_zero", .{ .periods = 1 }, .{ .window = 2, .min_periods = 2 });
    try rolling_crossover_plan.select(&.{ "sales", "sales_minus4", "zero_sales", "sales_zero_rolling_cross_count", "sales_zero_rolling_cross_above_count", "sales_zero_rolling_cross_below_count", "sales_zero_rolling_cross_above_rate", "sales_zero_rolling_cross_below_rate", "sales_zero_rolling_mean_abs_spread" });
    const rolling_crossover_explain = try rolling_crossover_plan.explain(gpa);
    defer gpa.free(rolling_crossover_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_crossover_explain, "rolling_crossover_profile(sales_minus4,zero_sales") != null);
    var rolling_crossover = try rolling_crossover_plan.collect();
    defer rolling_crossover.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_crossover.height());
    try std.testing.expectEqual(@as(usize, 9), rolling_crossover.width());
    const lazy_rolling_cross_count = try (try rolling_crossover.column("sales_zero_rolling_cross_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_count);
    const lazy_rolling_cross_above_count = try (try rolling_crossover.column("sales_zero_rolling_cross_above_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_above_count);
    const lazy_rolling_cross_below_count = try (try rolling_crossover.column("sales_zero_rolling_cross_below_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_below_count);
    const lazy_rolling_cross_above_rate = try (try rolling_crossover.column("sales_zero_rolling_cross_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_above_rate);
    const lazy_rolling_cross_below_rate = try (try rolling_crossover.column("sales_zero_rolling_cross_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_below_rate);
    const lazy_rolling_mean_abs_spread = try (try rolling_crossover.column("sales_zero_rolling_mean_abs_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_abs_spread);
    const lazy_rolling_crossover_validity = try (try rolling_crossover.column("sales_zero_rolling_cross_above_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_crossover_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_cross_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_rolling_cross_above_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_rolling_cross_below_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_crossover_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_cross_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_cross_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_cross_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_cross_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_rolling_mean_abs_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_mean_abs_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_abs_spread[3], 1e-12);
}

test "device lazy frame collects expanding crossover operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_crossover_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_crossover_plan.deinit();
    try expanding_crossover_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try expanding_crossover_plan.withColumnScalar("zero_sales", "sales", f64, 0.0, .mul);
    try expanding_crossover_plan.expandingCrossoverProfile("sales_minus4", "zero_sales", "sales_zero", .{ .periods = 1 }, .{ .min_periods = 2 });
    try expanding_crossover_plan.select(&.{ "sales", "sales_minus4", "zero_sales", "sales_zero_expanding_cross_count", "sales_zero_expanding_cross_above_count", "sales_zero_expanding_cross_below_count", "sales_zero_expanding_cross_above_rate", "sales_zero_expanding_cross_below_rate", "sales_zero_expanding_mean_abs_spread" });
    const expanding_crossover_explain = try expanding_crossover_plan.explain(gpa);
    defer gpa.free(expanding_crossover_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_crossover_explain, "expanding_crossover_profile(sales_minus4,zero_sales") != null);
    var expanding_crossover = try expanding_crossover_plan.collect();
    defer expanding_crossover.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_crossover.height());
    try std.testing.expectEqual(@as(usize, 9), expanding_crossover.width());
    const lazy_expanding_cross_count = try (try expanding_crossover.column("sales_zero_expanding_cross_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_count);
    const lazy_expanding_cross_above_count = try (try expanding_crossover.column("sales_zero_expanding_cross_above_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_above_count);
    const lazy_expanding_cross_below_count = try (try expanding_crossover.column("sales_zero_expanding_cross_below_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_below_count);
    const lazy_expanding_cross_above_rate = try (try expanding_crossover.column("sales_zero_expanding_cross_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_above_rate);
    const lazy_expanding_cross_below_rate = try (try expanding_crossover.column("sales_zero_expanding_cross_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_below_rate);
    const lazy_expanding_mean_abs_spread = try (try expanding_crossover.column("sales_zero_expanding_mean_abs_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_abs_spread);
    const lazy_expanding_crossover_validity = try (try expanding_crossover.column("sales_zero_expanding_cross_above_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_crossover_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_cross_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_expanding_cross_above_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_expanding_cross_below_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_crossover_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_cross_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_cross_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_cross_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_cross_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_mean_abs_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), lazy_expanding_mean_abs_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), lazy_expanding_mean_abs_spread[3], 1e-12);
}
