const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("test_helpers.zig").lazyCollectTable;

test "device lazy frame collects fit operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var fit_plan = try DeviceLazyFrame.init(gpa, table);
    defer fit_plan.deinit();
    try fit_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try fit_plan.linearFitProfile("sales_minus1", "sales", "sales_fit", .{});
    try fit_plan.select(&.{ "sales", "sales_minus1", "sales_fit_fitted", "sales_fit_residual", "sales_fit_residual_zscore", "sales_fit_slope" });
    const fit_explain = try fit_plan.explain(gpa);
    defer gpa.free(fit_explain);
    try std.testing.expect(std.mem.indexOf(u8, fit_explain, "linear_fit_profile(sales_minus1->sales") != null);
    var fit = try fit_plan.collect();
    defer fit.deinit();
    try std.testing.expectEqual(@as(usize, 4), fit.height());
    try std.testing.expectEqual(@as(usize, 6), fit.width());
    const lazy_fitted = try (try fit.column("sales_fit_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fitted);
    const lazy_fit_residual = try (try fit.column("sales_fit_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_residual);
    const lazy_fit_residual_z = try (try fit.column("sales_fit_residual_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_residual_z);
    const lazy_fit_slope = try (try fit.column("sales_fit_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_slope);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_fitted[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_fit_residual[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_fit_residual[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_fit_residual_z[0]));
    try std.testing.expect(std.math.isNan(lazy_fit_residual_z[3]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_fit_slope[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_fit_slope[3], 1e-12);
}

test "device lazy frame collects error operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var error_plan = try DeviceLazyFrame.init(gpa, table);
    defer error_plan.deinit();
    try error_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try error_plan.errorProfile("sales", "sales_minus1", "sales_err");
    try error_plan.select(&.{ "sales", "sales_err_error", "sales_err_abs_error", "sales_err_squared_error", "sales_err_ape", "sales_err_smape" });
    const error_explain = try error_plan.explain(gpa);
    defer gpa.free(error_explain);
    try std.testing.expect(std.mem.indexOf(u8, error_explain, "error_profile(actual=sales, predicted=sales_minus1") != null);
    var lazy_errors = try error_plan.collect();
    defer lazy_errors.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_errors.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_errors.width());
    const lazy_error = try (try lazy_errors.column("sales_err_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_error);
    const lazy_abs_error = try (try lazy_errors.column("sales_err_abs_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_abs_error);
    const lazy_squared_error = try (try lazy_errors.column("sales_err_squared_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_squared_error);
    const lazy_ape = try (try lazy_errors.column("sales_err_ape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ape);
    const lazy_smape = try (try lazy_errors.column("sales_err_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_smape);
    try std.testing.expectEqualSlices(f64, &.{ 1.0, 1.0, 1.0, 1.0 }, lazy_error);
    try std.testing.expectEqualSlices(f64, &.{ 1.0, 1.0, 1.0, 1.0 }, lazy_abs_error);
    try std.testing.expectEqualSlices(f64, &.{ 1.0, 1.0, 1.0, 1.0 }, lazy_squared_error);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_ape[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_ape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), lazy_ape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 7.0), lazy_ape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_smape[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 5.0), lazy_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 9.0), lazy_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 13.0), lazy_smape[3], 1e-12);
}

test "device lazy frame collects rolling error operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_error_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_error_plan.deinit();
    try rolling_error_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try rolling_error_plan.rollingErrorProfile("sales", "sales_minus1", "sales_err", .{ .window = 2, .min_periods = 2 });
    try rolling_error_plan.select(&.{ "sales", "sales_err_rolling_error_count", "sales_err_rolling_mae", "sales_err_rolling_rmse", "sales_err_rolling_mape", "sales_err_rolling_smape" });
    const rolling_error_explain = try rolling_error_plan.explain(gpa);
    defer gpa.free(rolling_error_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_error_explain, "rolling_error_profile(actual=sales, predicted=sales_minus1") != null);
    var rolling_errors = try rolling_error_plan.collect();
    defer rolling_errors.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_errors.height());
    try std.testing.expectEqual(@as(usize, 6), rolling_errors.width());
    const lazy_rolling_error_count = try (try rolling_errors.column("sales_err_rolling_error_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_error_count);
    const lazy_rolling_mae = try (try rolling_errors.column("sales_err_rolling_mae")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mae);
    const lazy_rolling_rmse = try (try rolling_errors.column("sales_err_rolling_rmse")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_rmse);
    const lazy_rolling_mape = try (try rolling_errors.column("sales_err_rolling_mape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mape);
    const lazy_rolling_smape = try (try rolling_errors.column("sales_err_rolling_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_smape);
    const lazy_rolling_error_validity = try (try rolling_errors.column("sales_err_rolling_mae")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_error_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_error_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_error_validity);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_rolling_mae);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_rolling_rmse);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0) / 2.0), lazy_rolling_mape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (1.0 / 3.0 + 0.2) / 2.0), lazy_rolling_mape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (0.2 + 1.0 / 7.0) / 2.0), lazy_rolling_mape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0) / 2.0), lazy_rolling_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 5.0 + 2.0 / 9.0) / 2.0), lazy_rolling_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 9.0 + 2.0 / 13.0) / 2.0), lazy_rolling_smape[3], 1e-12);
}

test "device lazy frame collects expanding error operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_error_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_error_plan.deinit();
    try expanding_error_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try expanding_error_plan.expandingErrorProfile("sales", "sales_minus1", "sales_err", .{ .min_periods = 2 });
    try expanding_error_plan.select(&.{ "sales", "sales_err_expanding_error_count", "sales_err_expanding_mae", "sales_err_expanding_rmse", "sales_err_expanding_mape", "sales_err_expanding_smape" });
    const expanding_error_explain = try expanding_error_plan.explain(gpa);
    defer gpa.free(expanding_error_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_error_explain, "expanding_error_profile(actual=sales, predicted=sales_minus1") != null);
    var expanding_errors = try expanding_error_plan.collect();
    defer expanding_errors.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_errors.height());
    try std.testing.expectEqual(@as(usize, 6), expanding_errors.width());
    const lazy_expanding_error_count = try (try expanding_errors.column("sales_err_expanding_error_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_error_count);
    const lazy_expanding_mae = try (try expanding_errors.column("sales_err_expanding_mae")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mae);
    const lazy_expanding_rmse = try (try expanding_errors.column("sales_err_expanding_rmse")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_rmse);
    const lazy_expanding_mape = try (try expanding_errors.column("sales_err_expanding_mape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mape);
    const lazy_expanding_smape = try (try expanding_errors.column("sales_err_expanding_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_smape);
    const lazy_expanding_error_validity = try (try expanding_errors.column("sales_err_expanding_mae")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_error_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_error_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_error_validity);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_expanding_mae);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_expanding_rmse);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0) / 2.0), lazy_expanding_mape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0 + 0.2) / 3.0), lazy_expanding_mape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0 + 0.2 + 1.0 / 7.0) / 4.0), lazy_expanding_mape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0) / 2.0), lazy_expanding_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0 + 2.0 / 9.0) / 3.0), lazy_expanding_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0 + 2.0 / 9.0 + 2.0 / 13.0) / 4.0), lazy_expanding_smape[3], 1e-12);
}
