const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("test_helpers.zig").lazyCollectTable;

test "device lazy frame collects rolling quantile operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_quantile_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_quantile_plan.deinit();
    try rolling_quantile_plan.rollingQuantileProfile("sales", "sales", .{ .window = 2, .min_periods = 1 });
    try rolling_quantile_plan.select(&.{ "sales", "sales_rolling_q1", "sales_rolling_median", "sales_rolling_q3", "sales_rolling_iqr" });
    const rolling_quantile_explain = try rolling_quantile_plan.explain(gpa);
    defer gpa.free(rolling_quantile_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_quantile_explain, "rolling_quantile_profile(sales") != null);
    var rolling_quantile = try rolling_quantile_plan.collect();
    defer rolling_quantile.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_quantile.height());
    try std.testing.expectEqual(@as(usize, 5), rolling_quantile.width());
    const lazy_rolling_q1 = try (try rolling_quantile.column("sales_rolling_q1")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_q1);
    const lazy_rolling_median = try (try rolling_quantile.column("sales_rolling_median")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_median);
    const lazy_rolling_q3 = try (try rolling_quantile.column("sales_rolling_q3")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_q3);
    const lazy_rolling_iqr = try (try rolling_quantile.column("sales_rolling_iqr")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_iqr);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_q1[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.25), lazy_rolling_q1[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.5), lazy_rolling_q1[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.5), lazy_rolling_q1[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_median[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), lazy_rolling_median[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_rolling_median[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.0), lazy_rolling_median[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_q3[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_rolling_q3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.5), lazy_rolling_q3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.5), lazy_rolling_q3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_iqr[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_iqr[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_iqr[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_iqr[3], 1e-12);
}

test "device lazy frame collects expanding quantile operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_quantile_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_quantile_plan.deinit();
    try expanding_quantile_plan.expandingQuantileProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_quantile_plan.select(&.{ "sales", "sales_expanding_q1", "sales_expanding_median", "sales_expanding_q3", "sales_expanding_iqr" });
    const expanding_quantile_explain = try expanding_quantile_plan.explain(gpa);
    defer gpa.free(expanding_quantile_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_quantile_explain, "expanding_quantile_profile(sales") != null);
    var expanding_quantile = try expanding_quantile_plan.collect();
    defer expanding_quantile.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_quantile.height());
    try std.testing.expectEqual(@as(usize, 5), expanding_quantile.width());
    const lazy_expanding_q1 = try (try expanding_quantile.column("sales_expanding_q1")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_q1);
    const lazy_expanding_median = try (try expanding_quantile.column("sales_expanding_median")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_median);
    const lazy_expanding_q3 = try (try expanding_quantile.column("sales_expanding_q3")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_q3);
    const lazy_expanding_iqr = try (try expanding_quantile.column("sales_expanding_iqr")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_iqr);
    const lazy_expanding_quantile_validity = try (try expanding_quantile.column("sales_expanding_median")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_quantile_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_quantile_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.25), lazy_expanding_q1[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), lazy_expanding_q1[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_expanding_q1[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), lazy_expanding_median[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_median[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_expanding_median[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_expanding_q3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_expanding_q3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.5), lazy_expanding_q3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_iqr[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_iqr[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_expanding_iqr[3], 1e-12);
}

test "device lazy frame collects rolling bool operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_bool_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_bool_plan.deinit();
    try rolling_bool_plan.rollingBoolProfile("active", "active", .{ .window = 2, .min_periods = 1 });
    try rolling_bool_plan.select(&.{ "active", "active_rolling_true_count", "active_rolling_false_count", "active_rolling_true_rate", "active_rolling_any", "active_rolling_all" });
    const rolling_bool_explain = try rolling_bool_plan.explain(gpa);
    defer gpa.free(rolling_bool_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_bool_explain, "rolling_bool_profile(active") != null);
    var rolling_bool = try rolling_bool_plan.collect();
    defer rolling_bool.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_bool.height());
    try std.testing.expectEqual(@as(usize, 6), rolling_bool.width());
    const lazy_true_count = try (try rolling_bool.column("active_rolling_true_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_true_count);
    const lazy_false_count = try (try rolling_bool.column("active_rolling_false_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_false_count);
    const lazy_true_rate = try (try rolling_bool.column("active_rolling_true_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_true_rate);
    const lazy_rolling_any = try (try rolling_bool.column("active_rolling_any")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_any);
    const lazy_rolling_all = try (try rolling_bool.column("active_rolling_all")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_all);
    const lazy_bool_validity = try (try rolling_bool.column("active_rolling_true_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_bool_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 2 }, lazy_true_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_false_count);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_bool_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_true_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_true_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_true_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_true_rate[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_rolling_any);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, true }, lazy_rolling_all);
}

test "device lazy frame collects expanding bool operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_bool_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_bool_plan.deinit();
    try expanding_bool_plan.expandingBoolProfile("active", "active", .{ .min_periods = 2 });
    try expanding_bool_plan.select(&.{ "active", "active_expanding_true_count", "active_expanding_false_count", "active_expanding_true_rate", "active_expanding_any", "active_expanding_all" });
    const expanding_bool_explain = try expanding_bool_plan.explain(gpa);
    defer gpa.free(expanding_bool_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_bool_explain, "expanding_bool_profile(active") != null);
    var lazy_expanding_bool = try expanding_bool_plan.collect();
    defer lazy_expanding_bool.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_bool.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_bool.width());
    const lazy_expanding_true_count = try (try lazy_expanding_bool.column("active_expanding_true_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_true_count);
    const lazy_expanding_false_count = try (try lazy_expanding_bool.column("active_expanding_false_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_false_count);
    const lazy_expanding_true_rate = try (try lazy_expanding_bool.column("active_expanding_true_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_true_rate);
    const lazy_expanding_any = try (try lazy_expanding_bool.column("active_expanding_any")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_any);
    const lazy_expanding_all = try (try lazy_expanding_bool.column("active_expanding_all")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_all);
    const lazy_expanding_bool_validity = try (try lazy_expanding_bool.column("active_expanding_true_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_bool_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 2, 3 }, lazy_expanding_true_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_false_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_bool_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_true_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_true_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_expanding_true_rate[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_any);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_expanding_all);
}
