const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("test_helpers.zig").lazyCollectTable;

test "device lazy frame collects rolling robust operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_robust_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_robust_plan.deinit();
    try rolling_robust_plan.rollingRobustProfile("sales", "sales", .{ .window = 2, .min_periods = 2 });
    try rolling_robust_plan.select(&.{ "sales", "sales_rolling_median_centered", "sales_rolling_mad_zscore", "sales_rolling_iqr_outlier", "sales_rolling_winsorized" });
    const rolling_robust_explain = try rolling_robust_plan.explain(gpa);
    defer gpa.free(rolling_robust_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_robust_explain, "rolling_robust_profile(sales") != null);
    var lazy_rolling_robust = try rolling_robust_plan.collect();
    defer lazy_rolling_robust.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_robust.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_rolling_robust.width());
    const lazy_rolling_median_centered = try (try lazy_rolling_robust.column("sales_rolling_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_median_centered);
    const lazy_rolling_mad_zscore = try (try lazy_rolling_robust.column("sales_rolling_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mad_zscore);
    const lazy_rolling_iqr_outlier = try (try lazy_rolling_robust.column("sales_rolling_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_iqr_outlier);
    const lazy_rolling_winsorized = try (try lazy_rolling_robust.column("sales_rolling_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_winsorized);
    const lazy_rolling_robust_validity = try (try lazy_rolling_robust.column("sales_rolling_median_centered")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_robust_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_robust_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), lazy_rolling_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), lazy_rolling_mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), lazy_rolling_mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_rolling_iqr_outlier);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_winsorized[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_winsorized[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_rolling_winsorized[3], 1e-12);
}

test "device lazy frame collects rolling operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_plan.deinit();
    try rolling_plan.rollingProfile("sales", "sales", .{ .window = 2, .min_periods = 1 });
    try rolling_plan.select(&.{ "sales", "sales_rolling_mean", "sales_rolling_stddev" });
    const rolling_explain = try rolling_plan.explain(gpa);
    defer gpa.free(rolling_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_explain, "rolling_profile(sales") != null);
    var rolling = try rolling_plan.collect();
    defer rolling.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling.height());
    try std.testing.expectEqual(@as(usize, 3), rolling.width());
    const rolling_mean = try (try rolling.column("sales_rolling_mean")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean);
    const rolling_stddev = try (try rolling.column("sales_rolling_stddev")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_stddev);
    const rolling_validity = try (try rolling.column("sales_rolling_mean")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, rolling_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_mean[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), rolling_mean[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), rolling_mean[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.0), rolling_mean[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_stddev[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_stddev[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_stddev[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_stddev[3], 1e-12);
}

test "device lazy frame collects rolling moment operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_moment_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_moment_plan.deinit();
    try rolling_moment_plan.rollingMomentProfile("sales", "sales", .{ .window = 2, .min_periods = 2 });
    try rolling_moment_plan.select(&.{ "sales", "sales_rolling_moment_count", "sales_rolling_m3", "sales_rolling_m4", "sales_rolling_skewness", "sales_rolling_kurtosis" });
    const rolling_moment_explain = try rolling_moment_plan.explain(gpa);
    defer gpa.free(rolling_moment_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_moment_explain, "rolling_moment_profile(sales") != null);
    var rolling_moments = try rolling_moment_plan.collect();
    defer rolling_moments.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_moments.height());
    try std.testing.expectEqual(@as(usize, 6), rolling_moments.width());
    const lazy_moment_count = try (try rolling_moments.column("sales_rolling_moment_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_moment_count);
    const lazy_m3 = try (try rolling_moments.column("sales_rolling_m3")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_m3);
    const lazy_m4 = try (try rolling_moments.column("sales_rolling_m4")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_m4);
    const lazy_skewness = try (try rolling_moments.column("sales_rolling_skewness")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_skewness);
    const lazy_kurtosis = try (try rolling_moments.column("sales_rolling_kurtosis")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_kurtosis);
    const lazy_moment_validity = try (try rolling_moments.column("sales_rolling_skewness")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_moment_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_moment_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_moment_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_m3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_m3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_m3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0625), lazy_m4[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_m4[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_m4[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_skewness[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_skewness[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_skewness[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_kurtosis[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_kurtosis[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_kurtosis[3], 1e-12);
}

test "device lazy frame collects ema operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var ema_plan = try DeviceLazyFrame.init(gpa, table);
    defer ema_plan.deinit();
    try ema_plan.emaProfile("sales", "sales", .{ .alpha = 0.5, .min_periods = 1 });
    try ema_plan.select(&.{ "sales", "sales_ema", "sales_ema_residual", "sales_ema_ratio" });
    const ema_explain = try ema_plan.explain(gpa);
    defer gpa.free(ema_explain);
    try std.testing.expect(std.mem.indexOf(u8, ema_explain, "ema_profile(sales") != null);
    var ema = try ema_plan.collect();
    defer ema.deinit();
    try std.testing.expectEqual(@as(usize, 4), ema.height());
    try std.testing.expectEqual(@as(usize, 4), ema.width());
    const lazy_ema = try (try ema.column("sales_ema")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ema);
    const lazy_ema_residual = try (try ema.column("sales_ema_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ema_residual);
    const lazy_ema_ratio = try (try ema.column("sales_ema_ratio")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ema_ratio);
    const lazy_ema_validity = try (try ema.column("sales_ema")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_ema_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_ema_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_ema[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), lazy_ema[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.75), lazy_ema[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.375), lazy_ema[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_ema_residual[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_ema_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), lazy_ema_residual[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.625), lazy_ema_residual[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_ema_ratio[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.2), lazy_ema_ratio[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.75), lazy_ema_ratio[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0 / 5.375), lazy_ema_ratio[3], 1e-12);
}

test "device lazy frame collects rolling range operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_range_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_range_plan.deinit();
    try rolling_range_plan.rollingRangeProfile("sales", "sales", .{ .window = 2, .min_periods = 1 });
    try rolling_range_plan.select(&.{ "sales", "sales_rolling_low", "sales_rolling_high", "sales_rolling_position" });
    const rolling_range_explain = try rolling_range_plan.explain(gpa);
    defer gpa.free(rolling_range_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_range_explain, "rolling_range_profile(sales") != null);
    var rolling_range = try rolling_range_plan.collect();
    defer rolling_range.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_range.height());
    try std.testing.expectEqual(@as(usize, 4), rolling_range.width());
    const lazy_rolling_low = try (try rolling_range.column("sales_rolling_low")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_low);
    const lazy_rolling_high = try (try rolling_range.column("sales_rolling_high")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_high);
    const lazy_rolling_position = try (try rolling_range.column("sales_rolling_position")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_position);
    const lazy_rolling_range_validity = try (try rolling_range.column("sales_rolling_position")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_range_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_rolling_range_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_low[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_low[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_low[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_low[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_high[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_high[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_high[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_rolling_high[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_rolling_position[0]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_position[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_position[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_position[3], 1e-12);
}

test "device lazy frame collects rolling norm operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_norm_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_norm_plan.deinit();
    try rolling_norm_plan.rollingNormalizeProfile("sales", "sales", .{ .window = 2, .min_periods = 1 });
    try rolling_norm_plan.select(&.{ "sales", "sales_rolling_centered", "sales_rolling_zscore", "sales_rolling_minmax" });
    const rolling_norm_explain = try rolling_norm_plan.explain(gpa);
    defer gpa.free(rolling_norm_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_norm_explain, "rolling_normalize_profile(sales") != null);
    var rolling_norm = try rolling_norm_plan.collect();
    defer rolling_norm.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_norm.height());
    try std.testing.expectEqual(@as(usize, 4), rolling_norm.width());
    const lazy_rolling_centered = try (try rolling_norm.column("sales_rolling_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_centered);
    const lazy_rolling_zscore = try (try rolling_norm.column("sales_rolling_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_zscore);
    const lazy_rolling_minmax = try (try rolling_norm.column("sales_rolling_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_minmax);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_centered[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_rolling_zscore[0]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_zscore[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_rolling_minmax[0]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_minmax[3], 1e-12);
}
