const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const helpers = @import("test_helpers.zig");
const lazyCollectTable = helpers.lazyCollectTable;
const lazyQualityTable = helpers.lazyQualityTable;

test "device lazy frame collects transition operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var transition_plan = try DeviceLazyFrame.init(gpa, table);
    defer transition_plan.deinit();
    try transition_plan.boolTransitionProfile("active", "active", .{ .periods = 1 });
    try transition_plan.select(&.{ "active", "active_rising", "active_falling", "active_toggled", "active_true_streak", "active_false_streak" });
    const transition_explain = try transition_plan.explain(gpa);
    defer gpa.free(transition_explain);
    try std.testing.expect(std.mem.indexOf(u8, transition_explain, "bool_transition_profile(active") != null);
    var lazy_transition = try transition_plan.collect();
    defer lazy_transition.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_transition.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_transition.width());
    const lazy_rising = try (try lazy_transition.column("active_rising")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_rising);
    const lazy_falling = try (try lazy_transition.column("active_falling")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_falling);
    const lazy_toggled = try (try lazy_transition.column("active_toggled")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_toggled);
    const lazy_true_streak = try (try lazy_transition.column("active_true_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_true_streak);
    const lazy_false_streak = try (try lazy_transition.column("active_false_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_false_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false }, lazy_rising);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false }, lazy_falling);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, false }, lazy_toggled);
    try std.testing.expectEqualSlices(i64, &.{ 1, 0, 1, 2 }, lazy_true_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 0, 0 }, lazy_false_streak);
}

test "device lazy frame collects rolling transition operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_transition_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_transition_plan.deinit();
    try rolling_transition_plan.rollingBoolTransitionProfile("active", "active", .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_transition_plan.select(&.{ "active", "active_rolling_transition_count", "active_rolling_rising_count", "active_rolling_falling_count", "active_rolling_toggle_count", "active_rolling_rising_rate", "active_rolling_falling_rate", "active_rolling_toggle_rate" });
    const rolling_transition_explain = try rolling_transition_plan.explain(gpa);
    defer gpa.free(rolling_transition_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_transition_explain, "rolling_bool_transition_profile(active") != null);
    var lazy_rolling_transition = try rolling_transition_plan.collect();
    defer lazy_rolling_transition.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_transition.height());
    try std.testing.expectEqual(@as(usize, 8), lazy_rolling_transition.width());
    const lazy_rolling_transition_count = try (try lazy_rolling_transition.column("active_rolling_transition_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_transition_count);
    const lazy_rolling_rising_count = try (try lazy_rolling_transition.column("active_rolling_rising_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_rising_count);
    const lazy_rolling_falling_count = try (try lazy_rolling_transition.column("active_rolling_falling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_falling_count);
    const lazy_rolling_toggle_count = try (try lazy_rolling_transition.column("active_rolling_toggle_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_toggle_count);
    const lazy_rolling_rising_rate = try (try lazy_rolling_transition.column("active_rolling_rising_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_rising_rate);
    const lazy_rolling_falling_rate = try (try lazy_rolling_transition.column("active_rolling_falling_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_falling_rate);
    const lazy_rolling_toggle_rate = try (try lazy_rolling_transition.column("active_rolling_toggle_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_toggle_rate);
    const lazy_rolling_transition_validity = try (try lazy_rolling_transition.column("active_rolling_toggle_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_transition_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_rolling_transition_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_rolling_rising_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_rolling_falling_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 1 }, lazy_rolling_toggle_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_transition_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_rising_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_rising_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_rising_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_falling_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_falling_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_falling_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_toggle_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_toggle_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_toggle_rate[3], 1e-12);
}

test "device lazy frame collects expanding transition operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_transition_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_transition_plan.deinit();
    try expanding_transition_plan.expandingBoolTransitionProfile("active", "active", .{ .periods = 1 }, .{ .min_periods = 2 });
    try expanding_transition_plan.select(&.{ "active", "active_expanding_transition_count", "active_expanding_rising_count", "active_expanding_falling_count", "active_expanding_toggle_count", "active_expanding_rising_rate", "active_expanding_falling_rate", "active_expanding_toggle_rate" });
    const expanding_transition_explain = try expanding_transition_plan.explain(gpa);
    defer gpa.free(expanding_transition_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_transition_explain, "expanding_bool_transition_profile(active") != null);
    var lazy_expanding_transition = try expanding_transition_plan.collect();
    defer lazy_expanding_transition.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_transition.height());
    try std.testing.expectEqual(@as(usize, 8), lazy_expanding_transition.width());
    const lazy_expanding_transition_count = try (try lazy_expanding_transition.column("active_expanding_transition_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_transition_count);
    const lazy_expanding_rising_count = try (try lazy_expanding_transition.column("active_expanding_rising_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_rising_count);
    const lazy_expanding_falling_count = try (try lazy_expanding_transition.column("active_expanding_falling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_falling_count);
    const lazy_expanding_toggle_count = try (try lazy_expanding_transition.column("active_expanding_toggle_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_toggle_count);
    const lazy_expanding_rising_rate = try (try lazy_expanding_transition.column("active_expanding_rising_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_rising_rate);
    const lazy_expanding_falling_rate = try (try lazy_expanding_transition.column("active_expanding_falling_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_falling_rate);
    const lazy_expanding_toggle_rate = try (try lazy_expanding_transition.column("active_expanding_toggle_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_toggle_rate);
    const lazy_expanding_transition_validity = try (try lazy_expanding_transition.column("active_expanding_toggle_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_transition_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3 }, lazy_expanding_transition_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_expanding_rising_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_falling_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_expanding_toggle_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_expanding_transition_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_rising_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_rising_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_falling_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_falling_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_toggle_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_toggle_rate[3], 1e-12);
}
