const std = @import("std");
const vectra = @import("vectra");

const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;

test "device dataframe crossover profile methods" {
    const gpa = std.testing.allocator;

    var fast = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 3.0, 2.0, 5.0, 4.0, 6.0 }, &.{ true, true, true, true, false, true }, .cpu);
    defer fast.deinit();
    var slow = try DeviceColumn.fromSlice(f64, gpa, &.{ 2.0, 2.0, 2.0, 4.0, 5.0, 0.0 }, .cpu);
    defer slow.deinit();
    var signal_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "fast", .data = fast },
        .{ .name = "slow", .data = slow },
    });
    defer signal_table.deinit();

    var cross = try signal_table.crossoverProfile("fast", "slow", "fast_slow", .{ .periods = 1 });
    defer cross.deinit();
    try std.testing.expectEqual(@as(usize, 6), cross.width());
    const spread = try (try cross.column("fast_slow_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(spread);
    const ratio = try (try cross.column("fast_slow_ratio")).f64.toOwnedSlice(gpa);
    defer gpa.free(ratio);
    const cross_above = try (try cross.column("fast_slow_cross_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(cross_above);
    const cross_below = try (try cross.column("fast_slow_cross_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(cross_below);
    const spread_validity = try (try cross.column("fast_slow_spread")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(spread_validity);
    const cross_validity = try (try cross.column("fast_slow_cross_above")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(cross_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false, true }, spread_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, false, false }, cross_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), spread[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), spread[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.0), spread[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), ratio[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), ratio[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), ratio[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), ratio[3], 1e-12);
    try std.testing.expect(std.math.isNan(ratio[5]));
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, false, false }, cross_above);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false, false, false }, cross_below);

    var rolling_cross = try signal_table.rollingCrossoverProfile("fast", "slow", "fast_slow", .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_cross.deinit();
    try std.testing.expectEqual(@as(usize, 8), rolling_cross.width());
    const rolling_cross_count = try (try rolling_cross.column("fast_slow_rolling_cross_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_cross_count);
    const rolling_cross_above_count = try (try rolling_cross.column("fast_slow_rolling_cross_above_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_cross_above_count);
    const rolling_cross_below_count = try (try rolling_cross.column("fast_slow_rolling_cross_below_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_cross_below_count);
    const rolling_cross_above_rate = try (try rolling_cross.column("fast_slow_rolling_cross_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_cross_above_rate);
    const rolling_cross_below_rate = try (try rolling_cross.column("fast_slow_rolling_cross_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_cross_below_rate);
    const rolling_mean_abs_spread = try (try rolling_cross.column("fast_slow_rolling_mean_abs_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean_abs_spread);
    const rolling_cross_validity = try (try rolling_cross.column("fast_slow_rolling_cross_above_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_cross_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 2, 2 }, rolling_cross_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 2, 1, 1 }, rolling_cross_above_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 0 }, rolling_cross_below_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true }, rolling_cross_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_cross_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_cross_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_cross_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_cross_above_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_cross_above_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_cross_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_mean_abs_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_mean_abs_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_mean_abs_spread[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_mean_abs_spread[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.5), rolling_mean_abs_spread[5], 1e-12);

    var expanding_cross = try signal_table.expandingCrossoverProfile("fast", "slow", "fast_slow", .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_cross.deinit();
    try std.testing.expectEqual(@as(usize, 8), expanding_cross.width());
    const expanding_cross_count = try (try expanding_cross.column("fast_slow_expanding_cross_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_cross_count);
    const expanding_cross_above_count = try (try expanding_cross.column("fast_slow_expanding_cross_above_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_cross_above_count);
    const expanding_cross_below_count = try (try expanding_cross.column("fast_slow_expanding_cross_below_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_cross_below_count);
    const expanding_cross_above_rate = try (try expanding_cross.column("fast_slow_expanding_cross_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_cross_above_rate);
    const expanding_cross_below_rate = try (try expanding_cross.column("fast_slow_expanding_cross_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_cross_below_rate);
    const expanding_mean_abs_spread = try (try expanding_cross.column("fast_slow_expanding_mean_abs_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean_abs_spread);
    const expanding_cross_validity = try (try expanding_cross.column("fast_slow_expanding_cross_above_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_cross_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4, 5 }, expanding_cross_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 2, 2, 2 }, expanding_cross_above_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 0 }, expanding_cross_below_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true }, expanding_cross_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_cross_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_cross_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_cross_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_cross_above_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.4), expanding_cross_above_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_cross_below_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_mean_abs_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), expanding_mean_abs_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), expanding_mean_abs_spread[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), expanding_mean_abs_spread[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.8), expanding_mean_abs_spread[5], 1e-12);

    var corr = try signal_table.rollingCorrelationProfile("fast", "slow", "fast_slow", .{ .window = 3, .min_periods = 2 });
    defer corr.deinit();
    try std.testing.expectEqual(@as(usize, 6), corr.width());
    const pair_count = try (try corr.column("fast_slow_rolling_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(pair_count);
    const covariance = try (try corr.column("fast_slow_rolling_covariance")).f64.toOwnedSlice(gpa);
    defer gpa.free(covariance);
    const correlation = try (try corr.column("fast_slow_rolling_correlation")).f64.toOwnedSlice(gpa);
    defer gpa.free(correlation);
    const beta = try (try corr.column("fast_slow_rolling_beta")).f64.toOwnedSlice(gpa);
    defer gpa.free(beta);
    const corr_validity = try (try corr.column("fast_slow_rolling_correlation")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(corr_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 2, 2 }, pair_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true }, corr_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), covariance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), covariance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.1111111111111107), covariance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), covariance[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), covariance[5], 1e-12);
    try std.testing.expect(std.math.isNan(correlation[1]));
    try std.testing.expect(std.math.isNan(correlation[2]));
    try std.testing.expectApproxEqAbs(@as(f64, 0.944911182523068), correlation[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), correlation[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), correlation[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), beta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.714285714285715), beta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), beta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -4.0), beta[5], 1e-12);
}
