const std = @import("std");
const vectra = @import("vectra");

const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;

test "device dataframe sign and validity profile methods" {
    const gpa = std.testing.allocator;

    var signed_values_col = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ -1.0, -2.0, 0.0, 3.0, -4.0, 0.0, 5.0 }, &.{ true, true, true, true, true, false, true }, .cpu);
    defer signed_values_col.deinit();
    var signed_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "signal", .data = signed_values_col },
    });
    defer signed_table.deinit();
    var sign = try signed_table.signProfile("signal", "signal", .{ .periods = 1 });
    defer sign.deinit();
    try std.testing.expectEqual(@as(usize, 6), sign.width());
    const sign_values = try (try sign.column("signal_sign")).i64.toOwnedSlice(gpa);
    defer gpa.free(sign_values);
    const sign_flip = try (try sign.column("signal_sign_flip")).bool.toOwnedSlice(gpa);
    defer gpa.free(sign_flip);
    const positive_streak = try (try sign.column("signal_positive_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(positive_streak);
    const negative_streak = try (try sign.column("signal_negative_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(negative_streak);
    const zero_streak = try (try sign.column("signal_zero_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(zero_streak);
    const sign_validity = try (try sign.column("signal_sign")).i64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(sign_validity);
    const flip_validity = try (try sign.column("signal_sign_flip")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(flip_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, true, false, true }, sign_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false, false }, flip_validity);
    try std.testing.expectEqualSlices(i64, &.{ -1, -1, 0, 1, -1, 0, 1 }, sign_values);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, false, false }, sign_flip);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 1, 0, 0, 1 }, positive_streak);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 0, 0, 1, 0, 0 }, negative_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 0, 0, 0, 0 }, zero_streak);

    var rolling_sign = try signed_table.rollingSignProfile("signal", "signal", .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_sign.deinit();
    try std.testing.expectEqual(@as(usize, 6), rolling_sign.width());
    const rolling_sign_count = try (try rolling_sign.column("signal_rolling_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_sign_count);
    const rolling_positive_rate = try (try rolling_sign.column("signal_rolling_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_positive_rate);
    const rolling_negative_rate = try (try rolling_sign.column("signal_rolling_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_negative_rate);
    const rolling_zero_rate = try (try rolling_sign.column("signal_rolling_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_zero_rate);
    const rolling_flip_rate = try (try rolling_sign.column("signal_rolling_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_flip_rate);
    const rolling_sign_rate_validity = try (try rolling_sign.column("signal_rolling_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_sign_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 3, 2, 2 }, rolling_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, rolling_sign_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_positive_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_positive_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_negative_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_zero_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_zero_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_flip_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_flip_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_flip_rate[6], 1e-12);

    var expanding_sign = try signed_table.expandingSignProfile("signal", "signal", .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_sign.deinit();
    try std.testing.expectEqual(@as(usize, 6), expanding_sign.width());
    const expanding_sign_count = try (try expanding_sign.column("signal_expanding_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_sign_count);
    const expanding_positive_rate = try (try expanding_sign.column("signal_expanding_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_positive_rate);
    const expanding_negative_rate = try (try expanding_sign.column("signal_expanding_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_negative_rate);
    const expanding_zero_rate = try (try expanding_sign.column("signal_expanding_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_zero_rate);
    const expanding_flip_rate = try (try expanding_sign.column("signal_expanding_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_flip_rate);
    const expanding_sign_rate_validity = try (try expanding_sign.column("signal_expanding_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_sign_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 5, 6 }, expanding_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, expanding_sign_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), expanding_positive_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_positive_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_negative_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), expanding_negative_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_negative_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_zero_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), expanding_zero_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_flip_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_flip_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), expanding_flip_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_flip_rate[6], 1e-12);

    var trend_source = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 3.0, 2.0, 2.0, 5.0, 0.0, 4.0 }, &.{ true, true, true, true, true, false, true }, .cpu);
    defer trend_source.deinit();
    var trend_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5, 6, 7 }, .cpu);
    defer trend_id.deinit();
    var trend_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "price", .data = trend_source },
        .{ .name = "id", .data = trend_id },
    });
    defer trend_table.deinit();

    var validity = try trend_table.validityProfile("price", "price");
    defer validity.deinit();
    try std.testing.expectEqual(@as(usize, 6), validity.width());
    const is_null = try (try validity.column("price_is_null")).bool.toOwnedSlice(gpa);
    defer gpa.free(is_null);
    const is_valid = try (try validity.column("price_is_valid")).bool.toOwnedSlice(gpa);
    defer gpa.free(is_valid);
    const valid_streak = try (try validity.column("price_valid_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(valid_streak);
    const null_streak = try (try validity.column("price_null_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(null_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false, false, true, false }, is_null);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, true, false, true }, is_valid);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 0, 1 }, valid_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 1, 0 }, null_streak);

    var rolling_quality = try trend_table.rollingValidityProfile("price", "price", .{ .window = 3, .min_periods = 2 });
    defer rolling_quality.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_quality.width());
    const rolling_validity_count = try (try rolling_quality.column("price_rolling_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_validity_count);
    const rolling_valid_count = try (try rolling_quality.column("price_rolling_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_valid_count);
    const rolling_null_count = try (try rolling_quality.column("price_rolling_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_null_count);
    const rolling_valid_rate = try (try rolling_quality.column("price_rolling_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_valid_rate);
    const rolling_null_rate = try (try rolling_quality.column("price_rolling_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_null_rate);
    const rolling_validity_rate_validity = try (try rolling_quality.column("price_rolling_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_validity_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 3, 3, 3 }, rolling_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 3, 2, 2 }, rolling_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 1, 1 }, rolling_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, rolling_validity_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_valid_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_valid_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_valid_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_null_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_null_rate[6], 1e-12);

    var expanding_quality = try trend_table.expandingValidityProfile("price", "price", .{ .min_periods = 2 });
    defer expanding_quality.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_quality.width());
    const expanding_validity_count = try (try expanding_quality.column("price_expanding_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity_count);
    const expanding_valid_count = try (try expanding_quality.column("price_expanding_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_valid_count);
    const expanding_null_count = try (try expanding_quality.column("price_expanding_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_null_count);
    const expanding_valid_rate = try (try expanding_quality.column("price_expanding_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_valid_rate);
    const expanding_null_rate = try (try expanding_quality.column("price_expanding_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_null_rate);
    const expanding_validity_rate_validity = try (try expanding_quality.column("price_expanding_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 6, 7 }, expanding_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 5, 6 }, expanding_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 1, 1 }, expanding_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, expanding_validity_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_valid_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 6.0), expanding_valid_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.0 / 7.0), expanding_valid_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 6.0), expanding_null_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 7.0), expanding_null_rate[6], 1e-12);
}
