const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const helpers = @import("dataframe_lazy_test_helpers.zig");
const lazyCollectTable = helpers.lazyCollectTable;
const lazyQualityTable = helpers.lazyQualityTable;

test "device lazy frame collects change operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var change_plan = try DeviceLazyFrame.init(gpa, table);
    defer change_plan.deinit();
    try change_plan.changePointProfile("sales", "sales", 2.0, .{ .periods = 1 });
    try change_plan.select(&.{ "sales", "sales_change_delta", "sales_change_abs_delta", "sales_change_pct", "sales_change_point" });
    const change_explain = try change_plan.explain(gpa);
    defer gpa.free(change_explain);
    try std.testing.expect(std.mem.indexOf(u8, change_explain, "change_point_profile(sales") != null);
    var lazy_change = try change_plan.collect();
    defer lazy_change.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_change.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_change.width());
    const lazy_change_delta = try (try lazy_change.column("sales_change_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_delta);
    const lazy_change_abs_delta = try (try lazy_change.column("sales_change_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_abs_delta);
    const lazy_change_pct = try (try lazy_change.column("sales_change_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_pct);
    const lazy_change_point = try (try lazy_change.column("sales_change_point")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_point);
    const lazy_change_validity = try (try lazy_change.column("sales_change_delta")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_change_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_change_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_change_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_change_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.4), lazy_change_pct[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_change_point);
}

test "device lazy frame collects rolling change operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_change_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_change_plan.deinit();
    try rolling_change_plan.rollingChangePointProfile("sales", "sales", 2.0, .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_change_plan.select(&.{ "sales", "sales_rolling_change_count", "sales_rolling_change_point_count", "sales_rolling_change_rate", "sales_rolling_mean_abs_delta", "sales_rolling_max_abs_delta" });
    const rolling_change_explain = try rolling_change_plan.explain(gpa);
    defer gpa.free(rolling_change_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_change_explain, "rolling_change_point_profile(sales") != null);
    var lazy_rolling_change = try rolling_change_plan.collect();
    defer lazy_rolling_change.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_change.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_change.width());
    const lazy_rolling_change_count = try (try lazy_rolling_change.column("sales_rolling_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_count);
    const lazy_rolling_change_point_count = try (try lazy_rolling_change.column("sales_rolling_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_point_count);
    const lazy_rolling_change_rate = try (try lazy_rolling_change.column("sales_rolling_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_rate);
    const lazy_rolling_mean_abs_delta = try (try lazy_rolling_change.column("sales_rolling_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_abs_delta);
    const lazy_rolling_max_abs_delta = try (try lazy_rolling_change.column("sales_rolling_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_max_abs_delta);
    const lazy_rolling_change_validity = try (try lazy_rolling_change.column("sales_rolling_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_rolling_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_rolling_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_change_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_mean_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_rolling_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_max_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_max_abs_delta[3], 1e-12);
}

test "device lazy frame collects expanding change operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_change_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_change_plan.deinit();
    try expanding_change_plan.expandingChangePointProfile("sales", "sales", 2.0, .{ .periods = 1 }, .{ .min_periods = 1 });
    try expanding_change_plan.select(&.{ "sales", "sales_expanding_change_count", "sales_expanding_change_point_count", "sales_expanding_change_rate", "sales_expanding_mean_abs_delta", "sales_expanding_max_abs_delta" });
    const expanding_change_explain = try expanding_change_plan.explain(gpa);
    defer gpa.free(expanding_change_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_change_explain, "expanding_change_point_profile(sales") != null);
    var lazy_expanding_change = try expanding_change_plan.collect();
    defer lazy_expanding_change.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_change.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_change.width());
    const lazy_expanding_change_count = try (try lazy_expanding_change.column("sales_expanding_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_count);
    const lazy_expanding_change_point_count = try (try lazy_expanding_change.column("sales_expanding_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_point_count);
    const lazy_expanding_change_rate = try (try lazy_expanding_change.column("sales_expanding_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_rate);
    const lazy_expanding_mean_abs_delta = try (try lazy_expanding_change.column("sales_expanding_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_abs_delta);
    const lazy_expanding_max_abs_delta = try (try lazy_expanding_change.column("sales_expanding_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_max_abs_delta);
    const lazy_expanding_change_validity = try (try lazy_expanding_change.column("sales_expanding_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3 }, lazy_expanding_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_expanding_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_change_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_mean_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.0), lazy_expanding_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_max_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_expanding_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_expanding_max_abs_delta[3], 1e-12);
}

test "device lazy frame collects sign operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var sign_plan = try DeviceLazyFrame.init(gpa, table);
    defer sign_plan.deinit();
    try sign_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try sign_plan.signProfile("sales_minus4", "sales", .{ .periods = 1 });
    try sign_plan.select(&.{ "sales_minus4", "sales_sign", "sales_sign_flip", "sales_positive_streak", "sales_negative_streak" });
    const sign_explain = try sign_plan.explain(gpa);
    defer gpa.free(sign_explain);
    try std.testing.expect(std.mem.indexOf(u8, sign_explain, "sign_profile(sales_minus4") != null);
    var lazy_sign = try sign_plan.collect();
    defer lazy_sign.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_sign.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_sign.width());
    const lazy_sign_values = try (try lazy_sign.column("sales_sign")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_sign_values);
    const lazy_sign_flip = try (try lazy_sign.column("sales_sign_flip")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_sign_flip);
    const lazy_positive_streak = try (try lazy_sign.column("sales_positive_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_positive_streak);
    const lazy_negative_streak = try (try lazy_sign.column("sales_negative_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_negative_streak);
    try std.testing.expectEqualSlices(i64, &.{ -1, -1, 1, 1 }, lazy_sign_values);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false }, lazy_sign_flip);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_positive_streak);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 0, 0 }, lazy_negative_streak);
}

test "device lazy frame collects rolling sign operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_sign_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_sign_plan.deinit();
    try rolling_sign_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try rolling_sign_plan.rollingSignProfile("sales_minus4", "sales", .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_sign_plan.select(&.{ "sales_minus4", "sales_rolling_sign_count", "sales_rolling_positive_rate", "sales_rolling_negative_rate", "sales_rolling_zero_rate", "sales_rolling_sign_flip_rate" });
    const rolling_sign_explain = try rolling_sign_plan.explain(gpa);
    defer gpa.free(rolling_sign_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_sign_explain, "rolling_sign_profile(sales_minus4") != null);
    var lazy_rolling_sign = try rolling_sign_plan.collect();
    defer lazy_rolling_sign.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_sign.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_sign.width());
    const lazy_rolling_sign_count = try (try lazy_rolling_sign.column("sales_rolling_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_sign_count);
    const lazy_rolling_positive_rate = try (try lazy_rolling_sign.column("sales_rolling_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_positive_rate);
    const lazy_rolling_negative_rate = try (try lazy_rolling_sign.column("sales_rolling_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_negative_rate);
    const lazy_rolling_zero_rate = try (try lazy_rolling_sign.column("sales_rolling_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_zero_rate);
    const lazy_rolling_sign_flip_rate = try (try lazy_rolling_sign.column("sales_rolling_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_sign_flip_rate);
    const lazy_rolling_sign_validity = try (try lazy_rolling_sign.column("sales_rolling_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_sign_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_rolling_sign_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_positive_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_positive_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_negative_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_negative_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_negative_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_zero_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_sign_flip_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_sign_flip_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_sign_flip_rate[3], 1e-12);
}

test "device lazy frame collects expanding sign operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_sign_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_sign_plan.deinit();
    try expanding_sign_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try expanding_sign_plan.expandingSignProfile("sales_minus4", "sales", .{ .periods = 1 }, .{ .min_periods = 1 });
    try expanding_sign_plan.select(&.{ "sales_minus4", "sales_expanding_sign_count", "sales_expanding_positive_rate", "sales_expanding_negative_rate", "sales_expanding_zero_rate", "sales_expanding_sign_flip_rate" });
    const expanding_sign_explain = try expanding_sign_plan.explain(gpa);
    defer gpa.free(expanding_sign_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_sign_explain, "expanding_sign_profile(sales_minus4") != null);
    var lazy_expanding_sign = try expanding_sign_plan.collect();
    defer lazy_expanding_sign.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_sign.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_sign.width());
    const lazy_expanding_sign_count = try (try lazy_expanding_sign.column("sales_expanding_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_sign_count);
    const lazy_expanding_positive_rate = try (try lazy_expanding_sign.column("sales_expanding_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_positive_rate);
    const lazy_expanding_negative_rate = try (try lazy_expanding_sign.column("sales_expanding_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_negative_rate);
    const lazy_expanding_zero_rate = try (try lazy_expanding_sign.column("sales_expanding_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_zero_rate);
    const lazy_expanding_sign_flip_rate = try (try lazy_expanding_sign.column("sales_expanding_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_sign_flip_rate);
    const lazy_expanding_sign_validity = try (try lazy_expanding_sign.column("sales_expanding_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_sign_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_expanding_sign_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_positive_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_positive_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_negative_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_negative_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_negative_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_zero_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_sign_flip_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_sign_flip_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_sign_flip_rate[3], 1e-12);
}
