const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const helpers = @import("dataframe_lazy_test_helpers.zig");
const lazyCollectTable = helpers.lazyCollectTable;
const lazyQualityTable = helpers.lazyQualityTable;

test "device lazy frame collects validity operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var validity_plan = try DeviceLazyFrame.init(gpa, table);
    defer validity_plan.deinit();
    try validity_plan.validityProfile("sales", "sales");
    try validity_plan.select(&.{ "sales", "sales_is_null", "sales_is_valid", "sales_valid_streak", "sales_null_streak" });
    const validity_explain = try validity_plan.explain(gpa);
    defer gpa.free(validity_explain);
    try std.testing.expect(std.mem.indexOf(u8, validity_explain, "validity_profile(sales") != null);
    var lazy_validity = try validity_plan.collect();
    defer lazy_validity.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_validity.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_validity.width());
    const lazy_is_null = try (try lazy_validity.column("sales_is_null")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_is_null);
    const lazy_is_valid = try (try lazy_validity.column("sales_is_valid")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_is_valid);
    const lazy_valid_streak = try (try lazy_validity.column("sales_valid_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_valid_streak);
    const lazy_null_streak = try (try lazy_validity.column("sales_null_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_null_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_is_null);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_is_valid);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_valid_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_null_streak);
}

test "device lazy frame collects rolling validity operations" {
    const gpa = std.testing.allocator;
    var quality_table = try lazyQualityTable(gpa);
    defer quality_table.deinit();
    var rolling_validity_plan = try DeviceLazyFrame.init(gpa, quality_table);
    defer rolling_validity_plan.deinit();
    try rolling_validity_plan.rollingValidityProfile("quality", "quality", .{ .window = 2, .min_periods = 2 });
    try rolling_validity_plan.select(&.{ "quality", "quality_rolling_validity_count", "quality_rolling_valid_count", "quality_rolling_null_count", "quality_rolling_valid_rate", "quality_rolling_null_rate" });
    const rolling_validity_explain = try rolling_validity_plan.explain(gpa);
    defer gpa.free(rolling_validity_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_validity_explain, "rolling_validity_profile(quality") != null);
    var lazy_rolling_validity = try rolling_validity_plan.collect();
    defer lazy_rolling_validity.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_validity.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_validity.width());
    const lazy_rolling_validity_count = try (try lazy_rolling_validity.column("quality_rolling_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_validity_count);
    const lazy_rolling_valid_count = try (try lazy_rolling_validity.column("quality_rolling_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_valid_count);
    const lazy_rolling_null_count = try (try lazy_rolling_validity.column("quality_rolling_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_null_count);
    const lazy_rolling_valid_rate = try (try lazy_rolling_validity.column("quality_rolling_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_valid_rate);
    const lazy_rolling_null_rate = try (try lazy_rolling_validity.column("quality_rolling_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_null_rate);
    const lazy_rolling_validity_validity = try (try lazy_rolling_validity.column("quality_rolling_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_validity_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 2 }, lazy_rolling_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_rolling_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_validity_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_valid_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_valid_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_null_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_null_rate[3], 1e-12);
}

test "device lazy frame collects expanding validity operations" {
    const gpa = std.testing.allocator;
    var quality_table = try lazyQualityTable(gpa);
    defer quality_table.deinit();
    var expanding_validity_plan = try DeviceLazyFrame.init(gpa, quality_table);
    defer expanding_validity_plan.deinit();
    try expanding_validity_plan.expandingValidityProfile("quality", "quality", .{ .min_periods = 2 });
    try expanding_validity_plan.select(&.{ "quality", "quality_expanding_validity_count", "quality_expanding_valid_count", "quality_expanding_null_count", "quality_expanding_valid_rate", "quality_expanding_null_rate" });
    const expanding_validity_explain = try expanding_validity_plan.explain(gpa);
    defer gpa.free(expanding_validity_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_validity_explain, "expanding_validity_profile(quality") != null);
    var lazy_expanding_validity = try expanding_validity_plan.collect();
    defer lazy_expanding_validity.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_validity.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_validity.width());
    const lazy_expanding_validity_count = try (try lazy_expanding_validity.column("quality_expanding_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_validity_count);
    const lazy_expanding_valid_count = try (try lazy_expanding_validity.column("quality_expanding_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_valid_count);
    const lazy_expanding_null_count = try (try lazy_expanding_validity.column("quality_expanding_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_null_count);
    const lazy_expanding_valid_rate = try (try lazy_expanding_validity.column("quality_expanding_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_valid_rate);
    const lazy_expanding_null_rate = try (try lazy_expanding_validity.column("quality_expanding_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_null_rate);
    const lazy_expanding_validity_validity = try (try lazy_expanding_validity.column("quality_expanding_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_validity_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 2, 3 }, lazy_expanding_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_validity_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_valid_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_expanding_valid_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_null_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_null_rate[3], 1e-12);
}
