const std = @import("std");
const boltha = @import("boltha");
const vectra = @import("vectra");

const DataFrame = vectra.DataFrame;
const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;
const DeviceLazyFrame = vectra.DeviceLazyFrame;
const DeviceDType = vectra.DeviceDType;
const DeviceValidityEncoding = vectra.DeviceValidityEncoding;
const DeviceParquetScan = vectra.DeviceParquetScan;

test "device dataframe window transform profiles" {
    const gpa = std.testing.allocator;

    var lag_source = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 10.0, 0.0, 15.0, 20.0, 99.0 }, &.{ true, true, true, true, false }, .cpu);
    defer lag_source.deinit();
    var lag_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5 }, .cpu);
    defer lag_id.deinit();
    var lag_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "sales", .data = lag_source },
        .{ .name = "id", .data = lag_id },
    });
    defer lag_table.deinit();

    var lagged = try lag_table.lagProfile("sales", "sales", .{ .periods = 2 });
    defer lagged.deinit();
    try std.testing.expectEqual(@as(usize, 5), lagged.width());
    const lag_values = try (try lagged.column("sales_lag")).f64.toOwnedSlice(gpa);
    defer gpa.free(lag_values);
    const diff_values = try (try lagged.column("sales_diff")).f64.toOwnedSlice(gpa);
    defer gpa.free(diff_values);
    const pct_values = try (try lagged.column("sales_pct_change")).f64.toOwnedSlice(gpa);
    defer gpa.free(pct_values);
    const lag_validity = try (try lagged.column("sales_lag")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lag_validity);
    const diff_validity = try (try lagged.column("sales_diff")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(diff_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true }, lag_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, false }, diff_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0), lag_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lag_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 15.0), lag_values[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), diff_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 20.0), diff_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), pct_values[2], 1e-12);
    try std.testing.expect(std.math.isNan(pct_values[3]));

    var leaded = try lag_table.leadProfile("sales", "sales", .{ .periods = 2 });
    defer leaded.deinit();
    try std.testing.expectEqual(@as(usize, 5), leaded.width());
    const lead_values = try (try leaded.column("sales_lead")).f64.toOwnedSlice(gpa);
    defer gpa.free(lead_values);
    const forward_diff = try (try leaded.column("sales_forward_diff")).f64.toOwnedSlice(gpa);
    defer gpa.free(forward_diff);
    const forward_pct = try (try leaded.column("sales_forward_pct_change")).f64.toOwnedSlice(gpa);
    defer gpa.free(forward_pct);
    const lead_validity = try (try leaded.column("sales_lead")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lead_validity);
    const forward_validity = try (try leaded.column("sales_forward_diff")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(forward_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, false, false, false }, lead_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, false, false, false }, forward_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 15.0), lead_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 20.0), lead_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), forward_diff[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 20.0), forward_diff[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), forward_pct[0], 1e-12);
    try std.testing.expect(std.math.isNan(forward_pct[1]));

    var expanding = try lag_table.expandingProfile("sales", "sales", .{ .min_periods = 2 });
    defer expanding.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding.width());
    const expanding_count = try (try expanding.column("sales_expanding_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_count);
    const expanding_sum = try (try expanding.column("sales_expanding_sum")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_sum);
    const expanding_mean = try (try expanding.column("sales_expanding_mean")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean);
    const expanding_min = try (try expanding.column("sales_expanding_min")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_min);
    const expanding_max = try (try expanding.column("sales_expanding_max")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_max);
    const expanding_validity = try (try expanding.column("sales_expanding_mean")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0), expanding_sum[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 25.0), expanding_sum[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 45.0), expanding_sum[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 45.0), expanding_sum[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), expanding_mean[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 25.0 / 3.0), expanding_mean[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 11.25), expanding_mean[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 11.25), expanding_mean[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_min[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_min[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0), expanding_max[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 20.0), expanding_max[4], 1e-12);

    var expanding_normalized = try lag_table.expandingNormalizeProfile("sales", "sales", .{ .min_periods = 2 });
    defer expanding_normalized.deinit();
    try std.testing.expectEqual(@as(usize, 5), expanding_normalized.width());
    const expanding_centered = try (try expanding_normalized.column("sales_expanding_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_centered);
    const expanding_zscore = try (try expanding_normalized.column("sales_expanding_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_zscore);
    const expanding_minmax = try (try expanding_normalized.column("sales_expanding_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_minmax);
    const expanding_normalized_validity = try (try expanding_normalized.column("sales_expanding_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_normalized_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, false }, expanding_normalized_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -5.0), expanding_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 20.0 / 3.0), expanding_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 8.75), expanding_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), expanding_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0690449676496976), expanding_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.1832159566199232), expanding_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_minmax[3], 1e-12);

    var expanding_moments = try lag_table.expandingMomentProfile("sales", "sales", .{ .min_periods = 2 });
    defer expanding_moments.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_moments.width());
    const expanding_moment_count = try (try expanding_moments.column("sales_expanding_moment_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_moment_count);
    const expanding_m3 = try (try expanding_moments.column("sales_expanding_m3")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_m3);
    const expanding_m4 = try (try expanding_moments.column("sales_expanding_m4")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_m4);
    const expanding_skewness = try (try expanding_moments.column("sales_expanding_skewness")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_skewness);
    const expanding_kurtosis = try (try expanding_moments.column("sales_expanding_kurtosis")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_kurtosis);
    const expanding_moment_validity = try (try expanding_moments.column("sales_expanding_skewness")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_moment_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_moment_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_moment_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_m3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -92.59259259259267), expanding_m3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -175.78125), expanding_m3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 625.0), expanding_m4[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2268.5185185185187), expanding_m4[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5520.01953125), expanding_m4[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_skewness[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.3818017741606065), expanding_skewness[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.43465075957466565), expanding_skewness[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), expanding_kurtosis[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), expanding_kurtosis[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.1542857142857144), expanding_kurtosis[3], 1e-12);

    var clipped = try lag_table.clipProfile("sales", "sales", .{ .lower = 5.0, .upper = 15.0 });
    defer clipped.deinit();
    try std.testing.expectEqual(@as(usize, 6), clipped.width());
    const clipped_values = try (try clipped.column("sales_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(clipped_values);
    const below_values = try (try clipped.column("sales_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(below_values);
    const above_values = try (try clipped.column("sales_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(above_values);
    const in_range_values = try (try clipped.column("sales_in_range")).bool.toOwnedSlice(gpa);
    defer gpa.free(in_range_values);
    const clip_validity = try (try clipped.column("sales_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(clip_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false }, clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0), clipped_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), clipped_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 15.0), clipped_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 15.0), clipped_values[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false, false }, below_values);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true, false }, above_values);
    try std.testing.expectEqualSlices(bool, &.{ true, false, true, false, false }, in_range_values);

    var rolling_clipped = try lag_table.rollingClipProfile("sales", "sales", .{ .lower = 5.0, .upper = 15.0 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_clipped.deinit();
    try std.testing.expectEqual(@as(usize, 8), rolling_clipped.width());
    const rolling_clip_count = try (try rolling_clipped.column("sales_rolling_clip_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_clip_count);
    const rolling_mean_clipped = try (try rolling_clipped.column("sales_rolling_mean_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean_clipped);
    const rolling_clipped_rate = try (try rolling_clipped.column("sales_rolling_clipped_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_clipped_rate);
    const rolling_clip_below_rate = try (try rolling_clipped.column("sales_rolling_clip_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_clip_below_rate);
    const rolling_clip_above_rate = try (try rolling_clipped.column("sales_rolling_clip_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_clip_above_rate);
    const rolling_in_range_rate = try (try rolling_clipped.column("sales_rolling_clip_in_range_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_in_range_rate);
    const rolling_clip_validity = try (try rolling_clipped.column("sales_rolling_mean_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_clip_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 2 }, rolling_clip_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 7.5), rolling_mean_clipped[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0), rolling_mean_clipped[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 35.0 / 3.0), rolling_mean_clipped[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 15.0), rolling_mean_clipped[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_clipped_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_clipped_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_clipped_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_clipped_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_clip_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_clip_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_clip_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_clip_below_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_clip_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_clip_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_clip_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_clip_above_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_in_range_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_in_range_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_in_range_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_in_range_rate[4], 1e-12);

    var expanding_clipped = try lag_table.expandingClipProfile("sales", "sales", .{ .lower = 5.0, .upper = 15.0 }, .{ .min_periods = 2 });
    defer expanding_clipped.deinit();
    try std.testing.expectEqual(@as(usize, 8), expanding_clipped.width());
    const expanding_clip_count = try (try expanding_clipped.column("sales_expanding_clip_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_clip_count);
    const expanding_mean_clipped = try (try expanding_clipped.column("sales_expanding_mean_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean_clipped);
    const expanding_clipped_rate = try (try expanding_clipped.column("sales_expanding_clipped_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_clipped_rate);
    const expanding_clip_below_rate = try (try expanding_clipped.column("sales_expanding_clip_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_clip_below_rate);
    const expanding_clip_above_rate = try (try expanding_clipped.column("sales_expanding_clip_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_clip_above_rate);
    const expanding_clip_in_range_rate = try (try expanding_clipped.column("sales_expanding_clip_in_range_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_clip_in_range_rate);
    const expanding_clip_validity = try (try expanding_clipped.column("sales_expanding_mean_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_clip_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_clip_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 7.5), expanding_mean_clipped[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0), expanding_mean_clipped[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 11.25), expanding_mean_clipped[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 11.25), expanding_mean_clipped[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clipped_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_clipped_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clipped_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clipped_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clip_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_clip_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_clip_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_clip_below_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_clip_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_clip_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_clip_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_clip_above_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clip_in_range_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), expanding_clip_in_range_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clip_in_range_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_clip_in_range_rate[4], 1e-12);

    var thresholded = try lag_table.thresholdProfile("sales", "sales", .{ .threshold = 10.0 });
    defer thresholded.deinit();
    try std.testing.expectEqual(@as(usize, 7), thresholded.width());
    const threshold_distance = try (try thresholded.column("sales_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(threshold_distance);
    const threshold_abs_distance = try (try thresholded.column("sales_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(threshold_abs_distance);
    const threshold_above = try (try thresholded.column("sales_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(threshold_above);
    const threshold_below = try (try thresholded.column("sales_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(threshold_below);
    const threshold_at = try (try thresholded.column("sales_at")).bool.toOwnedSlice(gpa);
    defer gpa.free(threshold_at);
    const threshold_validity = try (try thresholded.column("sales_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(threshold_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false }, threshold_validity);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, -10.0, 5.0, 10.0, 0.0 }, threshold_distance);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 10.0, 5.0, 10.0, 0.0 }, threshold_abs_distance);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, false }, threshold_above);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false, false }, threshold_below);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false, false }, threshold_at);

    var rolling_thresholded = try lag_table.rollingThresholdProfile("sales", "sales", 10.0, .{ .window = 3, .min_periods = 2 });
    defer rolling_thresholded.deinit();
    try std.testing.expectEqual(@as(usize, 8), rolling_thresholded.width());
    const rolling_threshold_count = try (try rolling_thresholded.column("sales_rolling_threshold_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_threshold_count);
    const rolling_mean_distance = try (try rolling_thresholded.column("sales_rolling_mean_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean_distance);
    const rolling_mean_abs_distance = try (try rolling_thresholded.column("sales_rolling_mean_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean_abs_distance);
    const rolling_above_rate = try (try rolling_thresholded.column("sales_rolling_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_above_rate);
    const rolling_below_rate = try (try rolling_thresholded.column("sales_rolling_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_below_rate);
    const rolling_at_rate = try (try rolling_thresholded.column("sales_rolling_at_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_at_rate);
    const rolling_threshold_validity = try (try rolling_thresholded.column("sales_rolling_mean_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_threshold_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 2 }, rolling_threshold_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_threshold_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -5.0), rolling_mean_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -5.0 / 3.0), rolling_mean_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.0), rolling_mean_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.5), rolling_mean_distance[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), rolling_mean_abs_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), rolling_mean_abs_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 25.0 / 3.0), rolling_mean_abs_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.5), rolling_mean_abs_distance[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_above_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_below_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_at_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_at_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_at_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_at_rate[4], 1e-12);

    var expanding_thresholded = try lag_table.expandingThresholdProfile("sales", "sales", 10.0, .{ .min_periods = 2 });
    defer expanding_thresholded.deinit();
    try std.testing.expectEqual(@as(usize, 8), expanding_thresholded.width());
    const expanding_threshold_count = try (try expanding_thresholded.column("sales_expanding_threshold_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_threshold_count);
    const expanding_mean_distance = try (try expanding_thresholded.column("sales_expanding_mean_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean_distance);
    const expanding_mean_abs_distance = try (try expanding_thresholded.column("sales_expanding_mean_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean_abs_distance);
    const expanding_above_rate = try (try expanding_thresholded.column("sales_expanding_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_above_rate);
    const expanding_below_rate = try (try expanding_thresholded.column("sales_expanding_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_below_rate);
    const expanding_at_rate = try (try expanding_thresholded.column("sales_expanding_at_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_at_rate);
    const expanding_threshold_validity = try (try expanding_thresholded.column("sales_expanding_mean_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_threshold_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_threshold_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_threshold_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -5.0), expanding_mean_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -5.0 / 3.0), expanding_mean_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), expanding_mean_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), expanding_mean_distance[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), expanding_mean_abs_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), expanding_mean_abs_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.25), expanding_mean_abs_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.25), expanding_mean_abs_distance[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_above_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_below_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_at_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_at_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_at_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_at_rate[4], 1e-12);

    var scaled = try lag_table.standardizeProfile("sales", "sales", .{ .min_periods = 3 });
    defer scaled.deinit();
    try std.testing.expectEqual(@as(usize, 5), scaled.width());
    const centered = try (try scaled.column("sales_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(centered);
    const zscore = try (try scaled.column("sales_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(zscore);
    const minmax = try (try scaled.column("sales_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(minmax);
    const scaled_validity = try (try scaled.column("sales_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(scaled_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false }, scaled_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.25), centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -11.25), centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.75), centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 8.75), centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.1690308509457033), zscore[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5212776585113297), zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.50709255283711), zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.1832159566199232), zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), minmax[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), minmax[3], 1e-12);
}
