const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("dataframe_lazy_test_helpers.zig").lazyCollectTable;

test "device lazy frame collects corr operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var corr_plan = try DeviceLazyFrame.init(gpa, table);
    defer corr_plan.deinit();
    try corr_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try corr_plan.rollingCorrelationProfile("sales_minus1", "sales", "sales_corr", .{ .window = 2, .min_periods = 2 });
    try corr_plan.select(&.{ "sales", "sales_corr_rolling_pair_count", "sales_corr_rolling_covariance", "sales_corr_rolling_correlation", "sales_corr_rolling_beta" });
    const corr_explain = try corr_plan.explain(gpa);
    defer gpa.free(corr_explain);
    try std.testing.expect(std.mem.indexOf(u8, corr_explain, "rolling_correlation_profile(sales_minus1,sales") != null);
    var rolling_corr = try corr_plan.collect();
    defer rolling_corr.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_corr.height());
    try std.testing.expectEqual(@as(usize, 5), rolling_corr.width());
    const lazy_pair_count = try (try rolling_corr.column("sales_corr_rolling_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_pair_count);
    const lazy_covariance = try (try rolling_corr.column("sales_corr_rolling_covariance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_covariance);
    const lazy_correlation = try (try rolling_corr.column("sales_corr_rolling_correlation")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_correlation);
    const lazy_beta = try (try rolling_corr.column("sales_corr_rolling_beta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_beta);
    const lazy_corr_validity = try (try rolling_corr.column("sales_corr_rolling_correlation")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_corr_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_pair_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_corr_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_covariance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_covariance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_covariance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_correlation[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_correlation[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_correlation[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_beta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_beta[3], 1e-12);
}

test "device lazy frame collects expanding corr operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_corr_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_corr_plan.deinit();
    try expanding_corr_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try expanding_corr_plan.expandingCorrelationProfile("sales_minus1", "sales", "sales_corr", .{ .min_periods = 2 });
    try expanding_corr_plan.select(&.{ "sales", "sales_corr_expanding_pair_count", "sales_corr_expanding_covariance", "sales_corr_expanding_correlation", "sales_corr_expanding_beta" });
    const expanding_corr_explain = try expanding_corr_plan.explain(gpa);
    defer gpa.free(expanding_corr_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_corr_explain, "expanding_correlation_profile(sales_minus1,sales") != null);
    var expanding_corr = try expanding_corr_plan.collect();
    defer expanding_corr.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_corr.height());
    try std.testing.expectEqual(@as(usize, 5), expanding_corr.width());
    const lazy_expanding_pair_count = try (try expanding_corr.column("sales_corr_expanding_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_pair_count);
    const lazy_expanding_covariance = try (try expanding_corr.column("sales_corr_expanding_covariance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_covariance);
    const lazy_expanding_correlation = try (try expanding_corr.column("sales_corr_expanding_correlation")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_correlation);
    const lazy_expanding_beta = try (try expanding_corr.column("sales_corr_expanding_beta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_beta);
    const lazy_expanding_corr_validity = try (try expanding_corr.column("sales_corr_expanding_correlation")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_corr_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_pair_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_corr_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_covariance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5555555555555554), lazy_expanding_covariance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.6875), lazy_expanding_covariance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_correlation[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_correlation[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_correlation[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_beta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_beta[3], 1e-12);
}

test "device lazy frame collects expanding fit operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_fit_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_fit_plan.deinit();
    try expanding_fit_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try expanding_fit_plan.expandingLinearFitProfile("sales_minus1", "sales", "sales_fit", .{ .min_periods = 2 });
    try expanding_fit_plan.select(&.{ "sales", "sales_fit_expanding_pair_count", "sales_fit_expanding_slope", "sales_fit_expanding_intercept", "sales_fit_expanding_fitted", "sales_fit_expanding_residual" });
    const expanding_fit_explain = try expanding_fit_plan.explain(gpa);
    defer gpa.free(expanding_fit_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_fit_explain, "expanding_linear_fit_profile(sales_minus1->sales") != null);
    var expanding_fit = try expanding_fit_plan.collect();
    defer expanding_fit.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_fit.height());
    try std.testing.expectEqual(@as(usize, 6), expanding_fit.width());
    const lazy_expanding_fit_count = try (try expanding_fit.column("sales_fit_expanding_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_count);
    const lazy_expanding_fit_slope = try (try expanding_fit.column("sales_fit_expanding_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_slope);
    const lazy_expanding_fit_intercept = try (try expanding_fit.column("sales_fit_expanding_intercept")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_intercept);
    const lazy_expanding_fit_fitted = try (try expanding_fit.column("sales_fit_expanding_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_fitted);
    const lazy_expanding_fit_residual = try (try expanding_fit.column("sales_fit_expanding_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_residual);
    const lazy_expanding_fit_validity = try (try expanding_fit.column("sales_fit_expanding_slope")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_fit_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_fit_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_slope[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_slope[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_slope[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_intercept[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_intercept[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_fit_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_expanding_fit_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_expanding_fit_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_fit_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_fit_residual[3], 1e-12);
}

test "device lazy frame collects rolling fit operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_fit_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_fit_plan.deinit();
    try rolling_fit_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try rolling_fit_plan.rollingLinearFitProfile("sales_minus1", "sales", "sales_fit", .{ .window = 2, .min_periods = 2 });
    try rolling_fit_plan.select(&.{ "sales", "sales_fit_rolling_pair_count", "sales_fit_rolling_slope", "sales_fit_rolling_intercept", "sales_fit_rolling_fitted", "sales_fit_rolling_residual" });
    const rolling_fit_explain = try rolling_fit_plan.explain(gpa);
    defer gpa.free(rolling_fit_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_fit_explain, "rolling_linear_fit_profile(sales_minus1->sales") != null);
    var rolling_fit = try rolling_fit_plan.collect();
    defer rolling_fit.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_fit.height());
    try std.testing.expectEqual(@as(usize, 6), rolling_fit.width());
    const lazy_fit_count = try (try rolling_fit.column("sales_fit_rolling_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_count);
    const lazy_rolling_fit_slope = try (try rolling_fit.column("sales_fit_rolling_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_slope);
    const lazy_rolling_fit_intercept = try (try rolling_fit.column("sales_fit_rolling_intercept")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_intercept);
    const lazy_rolling_fit_fitted = try (try rolling_fit.column("sales_fit_rolling_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_fitted);
    const lazy_rolling_fit_residual = try (try rolling_fit.column("sales_fit_rolling_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_residual);
    const lazy_fit_validity = try (try rolling_fit.column("sales_fit_rolling_slope")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_fit_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_fit_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_slope[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_slope[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_slope[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_intercept[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_intercept[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_intercept[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_fit_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_fit_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_rolling_fit_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_fit_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_fit_residual[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_fit_residual[3], 1e-12);
}
