const std = @import("std");
const vectra = @import("vectra");

const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;

test "device dataframe classification and transition profile methods" {
    const gpa = std.testing.allocator;

    var actual_label = try DeviceColumn.fromSliceWithValidity(bool, gpa, &.{ true, false, true, false, true }, &.{ true, true, true, false, true }, .cpu);
    defer actual_label.deinit();
    var predicted_label = try DeviceColumn.fromSlice(bool, gpa, &.{ true, true, false, false, true }, .cpu);
    defer predicted_label.deinit();
    var label_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "actual", .data = actual_label },
        .{ .name = "predicted", .data = predicted_label },
    });
    defer label_table.deinit();

    var classes = try label_table.classificationProfile("actual", "predicted", "cls");
    defer classes.deinit();
    try std.testing.expectEqual(@as(usize, 7), classes.width());
    const tp = try (try classes.column("cls_tp")).bool.toOwnedSlice(gpa);
    defer gpa.free(tp);
    const fp = try (try classes.column("cls_fp")).bool.toOwnedSlice(gpa);
    defer gpa.free(fp);
    const tn = try (try classes.column("cls_tn")).bool.toOwnedSlice(gpa);
    defer gpa.free(tn);
    const fn_values = try (try classes.column("cls_fn")).bool.toOwnedSlice(gpa);
    defer gpa.free(fn_values);
    const correct = try (try classes.column("cls_correct")).bool.toOwnedSlice(gpa);
    defer gpa.free(correct);
    const class_validity = try (try classes.column("cls_correct")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(class_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, false, true }, class_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false, true }, tp);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false, false }, fp);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false, false }, tn);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false, false }, fn_values);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false, true }, correct);

    var rolling_classes = try label_table.rollingClassificationProfile("actual", "predicted", "cls_roll", .{ .window = 3, .min_periods = 2 });
    defer rolling_classes.deinit();
    try std.testing.expectEqual(@as(usize, 10), rolling_classes.width());
    const rolling_class_count = try (try rolling_classes.column("cls_roll_rolling_class_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_class_count);
    const rolling_tp_count = try (try rolling_classes.column("cls_roll_rolling_tp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_tp_count);
    const rolling_fp_count = try (try rolling_classes.column("cls_roll_rolling_fp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_fp_count);
    const rolling_tn_count = try (try rolling_classes.column("cls_roll_rolling_tn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_tn_count);
    const rolling_fn_count = try (try rolling_classes.column("cls_roll_rolling_fn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_fn_count);
    const rolling_accuracy = try (try rolling_classes.column("cls_roll_rolling_accuracy")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_accuracy);
    const rolling_precision = try (try rolling_classes.column("cls_roll_rolling_precision")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_precision);
    const rolling_recall = try (try rolling_classes.column("cls_roll_rolling_recall")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_recall);
    const rolling_class_validity = try (try rolling_classes.column("cls_roll_rolling_accuracy")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_class_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 2, 2 }, rolling_class_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 0, 1 }, rolling_tp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 0 }, rolling_fp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0 }, rolling_tn_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1, 1 }, rolling_fn_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_class_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_accuracy[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_accuracy[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_accuracy[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_accuracy[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_precision[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_precision[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_precision[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_precision[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_recall[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_recall[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_recall[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_recall[4], 1e-12);

    var expanding_classes = try label_table.expandingClassificationProfile("actual", "predicted", "cls_expand", .{ .min_periods = 2 });
    defer expanding_classes.deinit();
    try std.testing.expectEqual(@as(usize, 10), expanding_classes.width());
    const expanding_class_count = try (try expanding_classes.column("cls_expand_expanding_class_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_class_count);
    const expanding_tp_count = try (try expanding_classes.column("cls_expand_expanding_tp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_tp_count);
    const expanding_fp_count = try (try expanding_classes.column("cls_expand_expanding_fp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_fp_count);
    const expanding_tn_count = try (try expanding_classes.column("cls_expand_expanding_tn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_tn_count);
    const expanding_fn_count = try (try expanding_classes.column("cls_expand_expanding_fn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_fn_count);
    const expanding_accuracy = try (try expanding_classes.column("cls_expand_expanding_accuracy")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_accuracy);
    const expanding_precision = try (try expanding_classes.column("cls_expand_expanding_precision")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_precision);
    const expanding_recall = try (try expanding_classes.column("cls_expand_expanding_recall")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_recall);
    const expanding_class_validity = try (try expanding_classes.column("cls_expand_expanding_accuracy")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_class_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 4 }, expanding_class_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 1, 2 }, expanding_tp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 1 }, expanding_fp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0 }, expanding_tn_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1, 1 }, expanding_fn_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_class_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_accuracy[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_accuracy[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_accuracy[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_precision[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_precision[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), expanding_precision[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_recall[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_recall[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), expanding_recall[4], 1e-12);

    var transitions = try label_table.boolTransitionProfile("actual", "actual", .{ .periods = 1 });
    defer transitions.deinit();
    try std.testing.expectEqual(@as(usize, 7), transitions.width());
    const rising = try (try transitions.column("actual_rising")).bool.toOwnedSlice(gpa);
    defer gpa.free(rising);
    const falling = try (try transitions.column("actual_falling")).bool.toOwnedSlice(gpa);
    defer gpa.free(falling);
    const toggled = try (try transitions.column("actual_toggled")).bool.toOwnedSlice(gpa);
    defer gpa.free(toggled);
    const true_streak = try (try transitions.column("actual_true_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(true_streak);
    const false_streak = try (try transitions.column("actual_false_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(false_streak);
    const transition_validity = try (try transitions.column("actual_toggled")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(transition_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, false, false }, transition_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false, false }, rising);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false, false }, falling);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, false, false }, toggled);
    try std.testing.expectEqualSlices(i64, &.{ 1, 0, 1, 0, 1 }, true_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 0, 0, 0 }, false_streak);

    var rolling_transitions = try label_table.rollingBoolTransitionProfile("actual", "actual", .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_transitions.deinit();
    try std.testing.expectEqual(@as(usize, 9), rolling_transitions.width());
    const rolling_transition_count = try (try rolling_transitions.column("actual_rolling_transition_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_transition_count);
    const rolling_rising_count = try (try rolling_transitions.column("actual_rolling_rising_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_rising_count);
    const rolling_falling_count = try (try rolling_transitions.column("actual_rolling_falling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_falling_count);
    const rolling_toggle_count = try (try rolling_transitions.column("actual_rolling_toggle_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_toggle_count);
    const rolling_rising_rate = try (try rolling_transitions.column("actual_rolling_rising_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_rising_rate);
    const rolling_falling_rate = try (try rolling_transitions.column("actual_rolling_falling_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_falling_rate);
    const rolling_toggle_rate = try (try rolling_transitions.column("actual_rolling_toggle_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_toggle_rate);
    const rolling_transition_validity = try (try rolling_transitions.column("actual_rolling_toggle_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_transition_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2, 1 }, rolling_transition_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1, 1 }, rolling_rising_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 0 }, rolling_falling_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2, 1 }, rolling_toggle_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, false }, rolling_transition_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_rising_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_rising_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_falling_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_falling_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_toggle_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_toggle_rate[3], 1e-12);

    var expanding_transitions = try label_table.expandingBoolTransitionProfile("actual", "actual", .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_transitions.deinit();
    try std.testing.expectEqual(@as(usize, 9), expanding_transitions.width());
    const expanding_transition_count = try (try expanding_transitions.column("actual_expanding_transition_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_transition_count);
    const expanding_rising_count = try (try expanding_transitions.column("actual_expanding_rising_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_rising_count);
    const expanding_falling_count = try (try expanding_transitions.column("actual_expanding_falling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_falling_count);
    const expanding_toggle_count = try (try expanding_transitions.column("actual_expanding_toggle_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_toggle_count);
    const expanding_rising_rate = try (try expanding_transitions.column("actual_expanding_rising_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_rising_rate);
    const expanding_falling_rate = try (try expanding_transitions.column("actual_expanding_falling_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_falling_rate);
    const expanding_toggle_rate = try (try expanding_transitions.column("actual_expanding_toggle_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_toggle_rate);
    const expanding_transition_validity = try (try expanding_transitions.column("actual_expanding_toggle_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_transition_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2, 2 }, expanding_transition_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1, 1 }, expanding_rising_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 1 }, expanding_falling_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2, 2 }, expanding_toggle_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true }, expanding_transition_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_rising_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_rising_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_rising_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_falling_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_falling_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_falling_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_toggle_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_toggle_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_toggle_rate[4], 1e-12);
}
