const std = @import("std");
const boltha = @import("boltha");
const vectra = @import("vectra");

const DataFrame = vectra.DataFrame;
const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;
const DeviceLazyFrame = vectra.DeviceLazyFrame;
const DeviceDType = vectra.DeviceDType;
const DeviceValidityEncoding = vectra.DeviceValidityEncoding;
const DeviceParquetScan = vectra.DeviceParquetScan;

fn lazyCollectTable(gpa: std.mem.Allocator) !DeviceDataFrame {
    var sales = try DeviceColumn.fromSlice(f64, gpa, &.{ 2.0, 3.0, 5.0, 7.0 }, .cpu);
    defer sales.deinit();
    var units = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4 }, .cpu);
    defer units.deinit();
    var active = try DeviceColumn.fromSlice(bool, gpa, &.{ true, false, true, true }, .cpu);
    defer active.deinit();

    return DeviceDataFrame.init(gpa, &.{
        .{ .name = "sales", .data = sales },
        .{ .name = "units", .data = units },
        .{ .name = "active", .data = active },
    });
}

test "device lazy frame collects lag operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var lag_plan = try DeviceLazyFrame.init(gpa, table);
    defer lag_plan.deinit();
    try lag_plan.lagProfile("sales", "sales", .{ .periods = 1 });
    try lag_plan.select(&.{ "sales", "sales_lag", "sales_diff", "sales_pct_change" });
    const lag_explain = try lag_plan.explain(gpa);
    defer gpa.free(lag_explain);
    try std.testing.expect(std.mem.indexOf(u8, lag_explain, "lag_profile(sales") != null);
    var lagged = try lag_plan.collect();
    defer lagged.deinit();
    try std.testing.expectEqual(@as(usize, 4), lagged.height());
    try std.testing.expectEqual(@as(usize, 4), lagged.width());
    const lazy_lag = try (try lagged.column("sales_lag")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_lag);
    const lazy_diff = try (try lagged.column("sales_diff")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_diff);
    const lazy_pct = try (try lagged.column("sales_pct_change")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_pct);
    const lazy_lag_validity = try (try lagged.column("sales_lag")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_lag_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_lag_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_lag[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_lag[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_lag[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_diff[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_diff[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_diff[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.4), lazy_pct[3], 1e-12);
}

test "device lazy frame collects lead operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var lead_plan = try DeviceLazyFrame.init(gpa, table);
    defer lead_plan.deinit();
    try lead_plan.leadProfile("sales", "sales", .{ .periods = 1 });
    try lead_plan.select(&.{ "sales", "sales_lead", "sales_forward_diff", "sales_forward_pct_change" });
    const lead_explain = try lead_plan.explain(gpa);
    defer gpa.free(lead_explain);
    try std.testing.expect(std.mem.indexOf(u8, lead_explain, "lead_profile(sales") != null);
    var leaded = try lead_plan.collect();
    defer leaded.deinit();
    try std.testing.expectEqual(@as(usize, 4), leaded.height());
    try std.testing.expectEqual(@as(usize, 4), leaded.width());
    const lazy_lead = try (try leaded.column("sales_lead")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_lead);
    const lazy_forward_diff = try (try leaded.column("sales_forward_diff")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_forward_diff);
    const lazy_forward_pct = try (try leaded.column("sales_forward_pct_change")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_forward_pct);
    const lazy_lead_validity = try (try leaded.column("sales_lead")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_lead_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, false }, lazy_lead_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_lead[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_lead[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_lead[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_forward_diff[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_forward_diff[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_forward_diff[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_forward_pct[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_forward_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.4), lazy_forward_pct[2], 1e-12);
}

test "device lazy frame collects clip operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var clip_plan = try DeviceLazyFrame.init(gpa, table);
    defer clip_plan.deinit();
    try clip_plan.clipProfile("sales", "sales", .{ .lower = 3.0, .upper = 5.0 });
    try clip_plan.select(&.{ "sales", "sales_clipped", "sales_below", "sales_above", "sales_in_range" });
    const clip_explain = try clip_plan.explain(gpa);
    defer gpa.free(clip_explain);
    try std.testing.expect(std.mem.indexOf(u8, clip_explain, "clip_profile(sales") != null);
    var lazy_clip = try clip_plan.collect();
    defer lazy_clip.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_clip.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_clip.width());
    const lazy_clipped = try (try lazy_clip.column("sales_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_clipped);
    const lazy_below = try (try lazy_clip.column("sales_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_below);
    const lazy_above = try (try lazy_clip.column("sales_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_above);
    const lazy_in_range = try (try lazy_clip.column("sales_in_range")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_in_range);
    try std.testing.expectEqualSlices(f64, &.{ 3.0, 3.0, 5.0, 5.0 }, lazy_clipped);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false }, lazy_below);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true }, lazy_above);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, false }, lazy_in_range);
}

test "device lazy frame collects rolling clip operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_clip_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_clip_plan.deinit();
    try rolling_clip_plan.rollingClipProfile("sales", "sales", .{ .lower = 3.0, .upper = 5.0 }, .{ .window = 2, .min_periods = 2 });
    try rolling_clip_plan.select(&.{ "sales", "sales_rolling_clip_count", "sales_rolling_mean_clipped", "sales_rolling_clipped_rate", "sales_rolling_clip_below_rate", "sales_rolling_clip_above_rate", "sales_rolling_clip_in_range_rate" });
    const rolling_clip_explain = try rolling_clip_plan.explain(gpa);
    defer gpa.free(rolling_clip_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_clip_explain, "rolling_clip_profile(sales") != null);
    var lazy_rolling_clip = try rolling_clip_plan.collect();
    defer lazy_rolling_clip.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_clip.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_rolling_clip.width());
    const lazy_rolling_clip_count = try (try lazy_rolling_clip.column("sales_rolling_clip_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_count);
    const lazy_rolling_mean_clipped = try (try lazy_rolling_clip.column("sales_rolling_mean_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_clipped);
    const lazy_rolling_clipped_rate = try (try lazy_rolling_clip.column("sales_rolling_clipped_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clipped_rate);
    const lazy_rolling_clip_below_rate = try (try lazy_rolling_clip.column("sales_rolling_clip_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_below_rate);
    const lazy_rolling_clip_above_rate = try (try lazy_rolling_clip.column("sales_rolling_clip_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_above_rate);
    const lazy_rolling_clip_in_range_rate = try (try lazy_rolling_clip.column("sales_rolling_clip_in_range_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_in_range_rate);
    const lazy_rolling_clip_validity = try (try lazy_rolling_clip.column("sales_rolling_mean_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_clip_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_mean_clipped[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_rolling_mean_clipped[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_mean_clipped[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clipped_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clipped_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clipped_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_in_range_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_clip_in_range_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_in_range_rate[3], 1e-12);
}

test "device lazy frame collects expanding clip operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_clip_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_clip_plan.deinit();
    try expanding_clip_plan.expandingClipProfile("sales", "sales", .{ .lower = 3.0, .upper = 5.0 }, .{ .min_periods = 2 });
    try expanding_clip_plan.select(&.{ "sales", "sales_expanding_clip_count", "sales_expanding_mean_clipped", "sales_expanding_clipped_rate", "sales_expanding_clip_below_rate", "sales_expanding_clip_above_rate", "sales_expanding_clip_in_range_rate" });
    const expanding_clip_explain = try expanding_clip_plan.explain(gpa);
    defer gpa.free(expanding_clip_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_clip_explain, "expanding_clip_profile(sales") != null);
    var lazy_expanding_clip = try expanding_clip_plan.collect();
    defer lazy_expanding_clip.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_clip.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_expanding_clip.width());
    const lazy_expanding_clip_count = try (try lazy_expanding_clip.column("sales_expanding_clip_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_count);
    const lazy_expanding_mean_clipped = try (try lazy_expanding_clip.column("sales_expanding_mean_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_clipped);
    const lazy_expanding_clipped_rate = try (try lazy_expanding_clip.column("sales_expanding_clipped_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clipped_rate);
    const lazy_expanding_clip_below_rate = try (try lazy_expanding_clip.column("sales_expanding_clip_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_below_rate);
    const lazy_expanding_clip_above_rate = try (try lazy_expanding_clip.column("sales_expanding_clip_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_above_rate);
    const lazy_expanding_clip_in_range_rate = try (try lazy_expanding_clip.column("sales_expanding_clip_in_range_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_in_range_rate);
    const lazy_expanding_clip_validity = try (try lazy_expanding_clip.column("sales_expanding_mean_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_clip_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_mean_clipped[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 11.0 / 3.0), lazy_expanding_mean_clipped[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_expanding_mean_clipped[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clipped_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_clipped_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clipped_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clip_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_clip_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_clip_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_clip_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_clip_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_clip_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clip_in_range_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_clip_in_range_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clip_in_range_rate[3], 1e-12);
}

test "device lazy frame collects threshold operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var threshold_plan = try DeviceLazyFrame.init(gpa, table);
    defer threshold_plan.deinit();
    try threshold_plan.thresholdProfile("sales", "sales", .{ .threshold = 5.0 });
    try threshold_plan.select(&.{ "sales", "sales_distance", "sales_abs_distance", "sales_above", "sales_below", "sales_at" });
    const threshold_explain = try threshold_plan.explain(gpa);
    defer gpa.free(threshold_explain);
    try std.testing.expect(std.mem.indexOf(u8, threshold_explain, "threshold_profile(sales") != null);
    var lazy_threshold = try threshold_plan.collect();
    defer lazy_threshold.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_threshold.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_threshold.width());
    const lazy_distance = try (try lazy_threshold.column("sales_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_distance);
    const lazy_abs_distance = try (try lazy_threshold.column("sales_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_abs_distance);
    const lazy_above_threshold = try (try lazy_threshold.column("sales_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_above_threshold);
    const lazy_below_threshold = try (try lazy_threshold.column("sales_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_below_threshold);
    const lazy_at_threshold = try (try lazy_threshold.column("sales_at")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_at_threshold);
    try std.testing.expectEqualSlices(f64, &.{ -3.0, -2.0, 0.0, 2.0 }, lazy_distance);
    try std.testing.expectEqualSlices(f64, &.{ 3.0, 2.0, 0.0, 2.0 }, lazy_abs_distance);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true }, lazy_above_threshold);
    try std.testing.expectEqualSlices(bool, &.{ true, true, false, false }, lazy_below_threshold);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false }, lazy_at_threshold);
}

test "device lazy frame collects rolling threshold operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_threshold_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_threshold_plan.deinit();
    try rolling_threshold_plan.rollingThresholdProfile("sales", "sales", 4.0, .{ .window = 2, .min_periods = 2 });
    try rolling_threshold_plan.select(&.{ "sales", "sales_rolling_threshold_count", "sales_rolling_mean_distance", "sales_rolling_mean_abs_distance", "sales_rolling_above_rate", "sales_rolling_below_rate", "sales_rolling_at_rate" });
    const rolling_threshold_explain = try rolling_threshold_plan.explain(gpa);
    defer gpa.free(rolling_threshold_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_threshold_explain, "rolling_threshold_profile(sales") != null);
    var lazy_rolling_threshold = try rolling_threshold_plan.collect();
    defer lazy_rolling_threshold.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_threshold.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_rolling_threshold.width());
    const lazy_rolling_threshold_count = try (try lazy_rolling_threshold.column("sales_rolling_threshold_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_threshold_count);
    const lazy_rolling_mean_distance = try (try lazy_rolling_threshold.column("sales_rolling_mean_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_distance);
    const lazy_rolling_mean_abs_distance = try (try lazy_rolling_threshold.column("sales_rolling_mean_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_abs_distance);
    const lazy_rolling_above_rate = try (try lazy_rolling_threshold.column("sales_rolling_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_above_rate);
    const lazy_rolling_below_rate = try (try lazy_rolling_threshold.column("sales_rolling_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_below_rate);
    const lazy_rolling_at_rate = try (try lazy_rolling_threshold.column("sales_rolling_at_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_at_rate);
    const lazy_rolling_threshold_validity = try (try lazy_rolling_threshold.column("sales_rolling_mean_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_threshold_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_threshold_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_threshold_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), lazy_rolling_mean_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_mean_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_rolling_mean_abs_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_mean_abs_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_abs_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_below_rate[3], 1e-12);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 0.0, 0.0, 0.0 }, lazy_rolling_at_rate);
}

test "device lazy frame collects expanding threshold operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_threshold_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_threshold_plan.deinit();
    try expanding_threshold_plan.expandingThresholdProfile("sales", "sales", 4.0, .{ .min_periods = 2 });
    try expanding_threshold_plan.select(&.{ "sales", "sales_expanding_threshold_count", "sales_expanding_mean_distance", "sales_expanding_mean_abs_distance", "sales_expanding_above_rate", "sales_expanding_below_rate", "sales_expanding_at_rate" });
    const expanding_threshold_explain = try expanding_threshold_plan.explain(gpa);
    defer gpa.free(expanding_threshold_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_threshold_explain, "expanding_threshold_profile(sales") != null);
    var lazy_expanding_threshold = try expanding_threshold_plan.collect();
    defer lazy_expanding_threshold.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_threshold.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_expanding_threshold.width());
    const lazy_expanding_threshold_count = try (try lazy_expanding_threshold.column("sales_expanding_threshold_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_threshold_count);
    const lazy_expanding_mean_distance = try (try lazy_expanding_threshold.column("sales_expanding_mean_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_distance);
    const lazy_expanding_mean_abs_distance = try (try lazy_expanding_threshold.column("sales_expanding_mean_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_abs_distance);
    const lazy_expanding_above_rate = try (try lazy_expanding_threshold.column("sales_expanding_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_above_rate);
    const lazy_expanding_below_rate = try (try lazy_expanding_threshold.column("sales_expanding_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_below_rate);
    const lazy_expanding_at_rate = try (try lazy_expanding_threshold.column("sales_expanding_at_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_at_rate);
    const lazy_expanding_threshold_validity = try (try lazy_expanding_threshold.column("sales_expanding_mean_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_threshold_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_threshold_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_threshold_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), lazy_expanding_mean_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0 / 3.0), lazy_expanding_mean_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_mean_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_mean_abs_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), lazy_expanding_mean_abs_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), lazy_expanding_mean_abs_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_below_rate[3], 1e-12);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 0.0, 0.0, 0.0 }, lazy_expanding_at_rate);
}

test "device lazy frame collects expanding operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_plan.deinit();
    try expanding_plan.expandingProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_plan.select(&.{ "sales", "sales_expanding_count", "sales_expanding_mean", "sales_expanding_max" });
    const expanding_explain = try expanding_plan.explain(gpa);
    defer gpa.free(expanding_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_explain, "expanding_profile(sales") != null);
    var expanding = try expanding_plan.collect();
    defer expanding.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding.height());
    try std.testing.expectEqual(@as(usize, 4), expanding.width());
    const expanding_count = try (try expanding.column("sales_expanding_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_count);
    const expanding_mean = try (try expanding.column("sales_expanding_mean")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean);
    const expanding_max = try (try expanding.column("sales_expanding_max")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_max);
    const expanding_validity = try (try expanding.column("sales_expanding_mean")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, expanding_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, expanding_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), expanding_mean[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0 / 3.0), expanding_mean[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.25), expanding_mean[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_max[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), expanding_max[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), expanding_max[3], 1e-12);
}

test "device lazy frame collects expanding norm operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_norm_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_norm_plan.deinit();
    try expanding_norm_plan.expandingNormalizeProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_norm_plan.select(&.{ "sales", "sales_expanding_centered", "sales_expanding_zscore", "sales_expanding_minmax" });
    const expanding_norm_explain = try expanding_norm_plan.explain(gpa);
    defer gpa.free(expanding_norm_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_norm_explain, "expanding_normalize_profile(sales") != null);
    var expanding_norm = try expanding_norm_plan.collect();
    defer expanding_norm.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_norm.height());
    try std.testing.expectEqual(@as(usize, 4), expanding_norm.width());
    const lazy_expanding_centered = try (try expanding_norm.column("sales_expanding_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_centered);
    const lazy_expanding_zscore = try (try expanding_norm.column("sales_expanding_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_zscore);
    const lazy_expanding_minmax = try (try expanding_norm.column("sales_expanding_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_minmax);
    const lazy_expanding_norm_validity = try (try expanding_norm.column("sales_expanding_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_norm_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_norm_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.0), lazy_expanding_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_expanding_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3363062095621219), lazy_expanding_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.4320780207890627), lazy_expanding_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_minmax[3], 1e-12);
}

test "device lazy frame collects expanding moment operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_moment_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_moment_plan.deinit();
    try expanding_moment_plan.expandingMomentProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_moment_plan.select(&.{ "sales", "sales_expanding_moment_count", "sales_expanding_m3", "sales_expanding_m4", "sales_expanding_skewness", "sales_expanding_kurtosis" });
    const expanding_moment_explain = try expanding_moment_plan.explain(gpa);
    defer gpa.free(expanding_moment_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_moment_explain, "expanding_moment_profile(sales") != null);
    var expanding_moments = try expanding_moment_plan.collect();
    defer expanding_moments.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_moments.height());
    try std.testing.expectEqual(@as(usize, 6), expanding_moments.width());
    const lazy_expanding_moment_count = try (try expanding_moments.column("sales_expanding_moment_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_moment_count);
    const lazy_expanding_m3 = try (try expanding_moments.column("sales_expanding_m3")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_m3);
    const lazy_expanding_m4 = try (try expanding_moments.column("sales_expanding_m4")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_m4);
    const lazy_expanding_skewness = try (try expanding_moments.column("sales_expanding_skewness")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_skewness);
    const lazy_expanding_kurtosis = try (try expanding_moments.column("sales_expanding_kurtosis")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_kurtosis);
    const lazy_expanding_moment_validity = try (try expanding_moments.column("sales_expanding_skewness")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_moment_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_moment_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_moment_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_m3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.7407407407407399), lazy_expanding_m3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.96875), lazy_expanding_m3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0625), lazy_expanding_m4[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.6296296296296293), lazy_expanding_m4[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 21.39453125), lazy_expanding_m4[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_skewness[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.3818017741606058), lazy_expanding_skewness[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.27803055565396284), lazy_expanding_skewness[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_expanding_kurtosis[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), lazy_expanding_kurtosis[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.4266015512783683), lazy_expanding_kurtosis[3], 1e-12);
}

test "device lazy frame collects standardize operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var standardize_plan = try DeviceLazyFrame.init(gpa, table);
    defer standardize_plan.deinit();
    try standardize_plan.standardizeProfile("sales", "sales", .{});
    try standardize_plan.select(&.{ "sales", "sales_centered", "sales_zscore", "sales_minmax" });
    const standardize_explain = try standardize_plan.explain(gpa);
    defer gpa.free(standardize_explain);
    try std.testing.expect(std.mem.indexOf(u8, standardize_explain, "standardize_profile(sales") != null);
    var standardized = try standardize_plan.collect();
    defer standardized.deinit();
    try std.testing.expectEqual(@as(usize, 4), standardized.height());
    try std.testing.expectEqual(@as(usize, 4), standardized.width());
    const lazy_centered = try (try standardized.column("sales_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_centered);
    const lazy_zscore = try (try standardized.column("sales_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_zscore);
    const lazy_minmax = try (try standardized.column("sales_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_minmax);
    const lazy_standardized_validity = try (try standardized.column("sales_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_standardized_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_standardized_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -2.25), lazy_centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.25), lazy_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.171700198827415), lazy_zscore[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.6509445549041194), lazy_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.39056673294247163), lazy_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.4320780207890627), lazy_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_minmax[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), lazy_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), lazy_minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_minmax[3], 1e-12);
}

test "device lazy frame collects robust operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var robust_plan = try DeviceLazyFrame.init(gpa, table);
    defer robust_plan.deinit();
    try robust_plan.robustProfile("sales", "sales", .{});
    try robust_plan.select(&.{ "sales", "sales_median_centered", "sales_mad_zscore", "sales_iqr_outlier", "sales_winsorized" });
    const robust_explain = try robust_plan.explain(gpa);
    defer gpa.free(robust_explain);
    try std.testing.expect(std.mem.indexOf(u8, robust_explain, "robust_profile(sales") != null);
    var robust = try robust_plan.collect();
    defer robust.deinit();
    try std.testing.expectEqual(@as(usize, 4), robust.height());
    try std.testing.expectEqual(@as(usize, 5), robust.width());
    const lazy_median_centered = try (try robust.column("sales_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_median_centered);
    const lazy_mad_zscore = try (try robust.column("sales_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_mad_zscore);
    const lazy_iqr_outlier = try (try robust.column("sales_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_iqr_outlier);
    const lazy_winsorized = try (try robust.column("sales_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_winsorized);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_median_centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), lazy_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.8993196669281089), lazy_mad_zscore[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.44965983346405447), lazy_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.44965983346405447), lazy_mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3489795003921634), lazy_mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_iqr_outlier);
    try std.testing.expectEqualSlices(f64, &.{ 2.0, 3.0, 5.0, 7.0 }, lazy_winsorized);
}

test "device lazy frame collects expanding robust operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_robust_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_robust_plan.deinit();
    try expanding_robust_plan.expandingRobustProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_robust_plan.select(&.{ "sales", "sales_expanding_median_centered", "sales_expanding_mad_zscore", "sales_expanding_iqr_outlier", "sales_expanding_winsorized" });
    const expanding_robust_explain = try expanding_robust_plan.explain(gpa);
    defer gpa.free(expanding_robust_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_robust_explain, "expanding_robust_profile(sales") != null);
    var expanding_robust = try expanding_robust_plan.collect();
    defer expanding_robust.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_robust.height());
    try std.testing.expectEqual(@as(usize, 5), expanding_robust.width());
    const lazy_expanding_median_centered = try (try expanding_robust.column("sales_expanding_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_median_centered);
    const lazy_expanding_mad_zscore = try (try expanding_robust.column("sales_expanding_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mad_zscore);
    const lazy_expanding_iqr_outlier = try (try expanding_robust.column("sales_expanding_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_iqr_outlier);
    const lazy_expanding_winsorized = try (try expanding_robust.column("sales_expanding_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_winsorized);
    const lazy_expanding_robust_validity = try (try expanding_robust.column("sales_expanding_mad_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_robust_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_robust_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_expanding_median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), lazy_expanding_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3489795003921634), lazy_expanding_mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3489795003921634), lazy_expanding_mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_expanding_iqr_outlier);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_winsorized[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_expanding_winsorized[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_expanding_winsorized[3], 1e-12);
}

test "device lazy frame collects drawdown operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var drawdown_plan = try DeviceLazyFrame.init(gpa, table);
    defer drawdown_plan.deinit();
    try drawdown_plan.drawdownProfile("sales", "sales", .{ .min_periods = 2 });
    try drawdown_plan.select(&.{ "sales", "sales_running_peak", "sales_drawdown", "sales_drawdown_pct" });
    const drawdown_explain = try drawdown_plan.explain(gpa);
    defer gpa.free(drawdown_explain);
    try std.testing.expect(std.mem.indexOf(u8, drawdown_explain, "drawdown_profile(sales") != null);
    var drawdown = try drawdown_plan.collect();
    defer drawdown.deinit();
    try std.testing.expectEqual(@as(usize, 4), drawdown.height());
    try std.testing.expectEqual(@as(usize, 4), drawdown.width());
    const lazy_peak = try (try drawdown.column("sales_running_peak")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_peak);
    const lazy_drawdown = try (try drawdown.column("sales_drawdown")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_drawdown);
    const lazy_drawdown_pct = try (try drawdown.column("sales_drawdown_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_drawdown_pct);
    const lazy_drawdown_validity = try (try drawdown.column("sales_drawdown")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_drawdown_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_drawdown_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_peak[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_peak[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_peak[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_drawdown[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_drawdown[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_drawdown[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_drawdown_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_drawdown_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_drawdown_pct[3], 1e-12);
}

test "device lazy frame collects rolling drawdown operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_drawdown_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_drawdown_plan.deinit();
    try rolling_drawdown_plan.rollingDrawdownProfile("sales", "sales", .{ .window = 2, .min_periods = 1 });
    try rolling_drawdown_plan.select(&.{ "sales", "sales_rolling_peak", "sales_rolling_drawdown", "sales_rolling_drawdown_pct", "sales_rolling_peak_age" });
    const rolling_drawdown_explain = try rolling_drawdown_plan.explain(gpa);
    defer gpa.free(rolling_drawdown_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_drawdown_explain, "rolling_drawdown_profile(sales") != null);
    var lazy_rolling_drawdown = try rolling_drawdown_plan.collect();
    defer lazy_rolling_drawdown.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_drawdown.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_rolling_drawdown.width());
    const lazy_rolling_peak = try (try lazy_rolling_drawdown.column("sales_rolling_peak")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_peak);
    const lazy_rolling_drawdown_values = try (try lazy_rolling_drawdown.column("sales_rolling_drawdown")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_drawdown_values);
    const lazy_rolling_drawdown_pct = try (try lazy_rolling_drawdown.column("sales_rolling_drawdown_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_drawdown_pct);
    const lazy_rolling_peak_age = try (try lazy_rolling_drawdown.column("sales_rolling_peak_age")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_peak_age);
    try std.testing.expectEqualSlices(f64, &.{ 2.0, 3.0, 5.0, 7.0 }, lazy_rolling_peak);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 0.0, 0.0, 0.0 }, lazy_rolling_drawdown_values);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 0.0, 0.0, 0.0 }, lazy_rolling_drawdown_pct);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_rolling_peak_age);
}

test "device lazy frame collects extrema operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var extrema_plan = try DeviceLazyFrame.init(gpa, table);
    defer extrema_plan.deinit();
    try extrema_plan.extremaProfile("sales", "sales", .{ .min_periods = 1 });
    try extrema_plan.select(&.{ "sales", "sales_running_low", "sales_running_high", "sales_new_low", "sales_new_high" });
    const extrema_explain = try extrema_plan.explain(gpa);
    defer gpa.free(extrema_explain);
    try std.testing.expect(std.mem.indexOf(u8, extrema_explain, "extrema_profile(sales") != null);
    var lazy_extrema = try extrema_plan.collect();
    defer lazy_extrema.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_extrema.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_extrema.width());
    const lazy_running_low = try (try lazy_extrema.column("sales_running_low")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_running_low);
    const lazy_running_high = try (try lazy_extrema.column("sales_running_high")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_running_high);
    const lazy_new_low = try (try lazy_extrema.column("sales_new_low")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_new_low);
    const lazy_new_high = try (try lazy_extrema.column("sales_new_high")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_new_high);
    try std.testing.expectEqualSlices(f64, &.{ 2.0, 2.0, 2.0, 2.0 }, lazy_running_low);
    try std.testing.expectEqualSlices(f64, &.{ 2.0, 3.0, 5.0, 7.0 }, lazy_running_high);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false }, lazy_new_low);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_new_high);
}

test "device lazy frame collects trend operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var trend_plan = try DeviceLazyFrame.init(gpa, table);
    defer trend_plan.deinit();
    try trend_plan.trendProfile("sales", "sales", .{ .periods = 1 });
    try trend_plan.select(&.{ "sales", "sales_trend", "sales_up_streak", "sales_reversal" });
    const trend_explain = try trend_plan.explain(gpa);
    defer gpa.free(trend_explain);
    try std.testing.expect(std.mem.indexOf(u8, trend_explain, "trend_profile(sales") != null);
    var trend = try trend_plan.collect();
    defer trend.deinit();
    try std.testing.expectEqual(@as(usize, 4), trend.height());
    try std.testing.expectEqual(@as(usize, 4), trend.width());
    const lazy_trend = try (try trend.column("sales_trend")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_trend);
    const lazy_up_streak = try (try trend.column("sales_up_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_up_streak);
    const lazy_reversal = try (try trend.column("sales_reversal")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_reversal);
    const lazy_trend_validity = try (try trend.column("sales_trend")).i64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_trend_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_trend);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3 }, lazy_up_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_reversal);
}

test "device lazy frame collects rolling trend operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_trend_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_trend_plan.deinit();
    try rolling_trend_plan.rollingTrendProfile("sales", "sales", .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_trend_plan.select(&.{ "sales", "sales_rolling_trend_count", "sales_rolling_up_rate", "sales_rolling_down_rate", "sales_rolling_flat_rate", "sales_rolling_reversal_rate" });
    const rolling_trend_explain = try rolling_trend_plan.explain(gpa);
    defer gpa.free(rolling_trend_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_trend_explain, "rolling_trend_profile(sales") != null);
    var lazy_rolling_trend = try rolling_trend_plan.collect();
    defer lazy_rolling_trend.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_trend.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_trend.width());
    const lazy_rolling_trend_count = try (try lazy_rolling_trend.column("sales_rolling_trend_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_trend_count);
    const lazy_rolling_up_rate = try (try lazy_rolling_trend.column("sales_rolling_up_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_up_rate);
    const lazy_rolling_down_rate = try (try lazy_rolling_trend.column("sales_rolling_down_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_down_rate);
    const lazy_rolling_flat_rate = try (try lazy_rolling_trend.column("sales_rolling_flat_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_flat_rate);
    const lazy_rolling_reversal_rate = try (try lazy_rolling_trend.column("sales_rolling_reversal_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_reversal_rate);
    const lazy_rolling_trend_validity = try (try lazy_rolling_trend.column("sales_rolling_up_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_rolling_trend_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_trend_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_up_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_up_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_up_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_down_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_flat_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_reversal_rate[3], 1e-12);
}

test "device lazy frame collects expanding trend operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_trend_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_trend_plan.deinit();
    try expanding_trend_plan.expandingTrendProfile("sales", "sales", .{ .periods = 1 }, .{ .min_periods = 1 });
    try expanding_trend_plan.select(&.{ "sales", "sales_expanding_trend_count", "sales_expanding_up_rate", "sales_expanding_down_rate", "sales_expanding_flat_rate", "sales_expanding_reversal_rate" });
    const expanding_trend_explain = try expanding_trend_plan.explain(gpa);
    defer gpa.free(expanding_trend_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_trend_explain, "expanding_trend_profile(sales") != null);
    var lazy_expanding_trend = try expanding_trend_plan.collect();
    defer lazy_expanding_trend.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_trend.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_trend.width());
    const lazy_expanding_trend_count = try (try lazy_expanding_trend.column("sales_expanding_trend_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_trend_count);
    const lazy_expanding_up_rate = try (try lazy_expanding_trend.column("sales_expanding_up_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_up_rate);
    const lazy_expanding_down_rate = try (try lazy_expanding_trend.column("sales_expanding_down_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_down_rate);
    const lazy_expanding_flat_rate = try (try lazy_expanding_trend.column("sales_expanding_flat_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_flat_rate);
    const lazy_expanding_reversal_rate = try (try lazy_expanding_trend.column("sales_expanding_reversal_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_reversal_rate);
    const lazy_expanding_trend_validity = try (try lazy_expanding_trend.column("sales_expanding_up_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3 }, lazy_expanding_trend_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_trend_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_up_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_up_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_up_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_down_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_flat_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_reversal_rate[3], 1e-12);
}
