const std = @import("std");
const boltha = @import("boltha");
const vectra = @import("vectra");

const DataFrame = vectra.DataFrame;
const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;
const DeviceLazyFrame = vectra.DeviceLazyFrame;
const DeviceDType = vectra.DeviceDType;
const DeviceValidityEncoding = vectra.DeviceValidityEncoding;
const DeviceParquetScan = vectra.DeviceParquetScan;

test "device dataframe event profile methods" {
    const gpa = std.testing.allocator;

    var robust_source = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 2.0, 3.0, 100.0, 0.0 }, &.{ true, true, true, true, false }, .cpu);
    defer robust_source.deinit();
    var robust_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5 }, .cpu);
    defer robust_id.deinit();
    var robust_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "value", .data = robust_source },
        .{ .name = "id", .data = robust_id },
    });
    defer robust_table.deinit();

    var robust = try robust_table.robustProfile("value", "value", .{ .min_periods = 4 });
    defer robust.deinit();
    try std.testing.expectEqual(@as(usize, 6), robust.width());
    const median_centered = try (try robust.column("value_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(median_centered);
    const mad_zscore = try (try robust.column("value_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(mad_zscore);
    const iqr_outlier = try (try robust.column("value_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(iqr_outlier);
    const winsorized = try (try robust.column("value_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(winsorized);
    const robust_validity = try (try robust.column("value_mad_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(robust_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false }, robust_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), median_centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.5), median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 97.5), median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0117346252941226), mad_zscore[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.33724487509804085), mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.33724487509804085), mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 65.76275064411797), mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true, false }, iqr_outlier);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), winsorized[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), winsorized[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), winsorized[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 65.5), winsorized[3], 1e-12);

    var expanding_robust = try robust_table.expandingRobustProfile("value", "value", .{ .min_periods = 2 });
    defer expanding_robust.deinit();
    try std.testing.expectEqual(@as(usize, 6), expanding_robust.width());
    const expanding_median_centered = try (try expanding_robust.column("value_expanding_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_median_centered);
    const expanding_mad_zscore = try (try expanding_robust.column("value_expanding_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mad_zscore);
    const expanding_iqr_outlier = try (try expanding_robust.column("value_expanding_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(expanding_iqr_outlier);
    const expanding_winsorized = try (try expanding_robust.column("value_expanding_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_winsorized);
    const expanding_robust_validity = try (try expanding_robust.column("value_expanding_mad_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_robust_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, false }, expanding_robust_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 97.5), expanding_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), expanding_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), expanding_mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 65.76275064411797), expanding_mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true, false }, expanding_iqr_outlier);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_winsorized[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_winsorized[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 65.5), expanding_winsorized[3], 1e-12);

    var equity = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 100.0, 120.0, 90.0, 130.0, 80.0, 0.0 }, &.{ true, true, true, true, true, false }, .cpu);
    defer equity.deinit();
    var equity_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5, 6 }, .cpu);
    defer equity_id.deinit();
    var equity_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "equity", .data = equity },
        .{ .name = "id", .data = equity_id },
    });
    defer equity_table.deinit();

    var drawdown = try equity_table.drawdownProfile("equity", "equity", .{ .min_periods = 2 });
    defer drawdown.deinit();
    try std.testing.expectEqual(@as(usize, 5), drawdown.width());
    const running_peak = try (try drawdown.column("equity_running_peak")).f64.toOwnedSlice(gpa);
    defer gpa.free(running_peak);
    const drawdown_values = try (try drawdown.column("equity_drawdown")).f64.toOwnedSlice(gpa);
    defer gpa.free(drawdown_values);
    const drawdown_pct = try (try drawdown.column("equity_drawdown_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(drawdown_pct);
    const drawdown_validity = try (try drawdown.column("equity_drawdown")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(drawdown_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false }, drawdown_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 120.0), running_peak[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 120.0), running_peak[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 130.0), running_peak[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 130.0), running_peak[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), drawdown_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -30.0), drawdown_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), drawdown_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -50.0), drawdown_values[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), drawdown_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.25), drawdown_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), drawdown_pct[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -50.0 / 130.0), drawdown_pct[4], 1e-12);

    var rolling_drawdown = try equity_table.rollingDrawdownProfile("equity", "equity", .{ .window = 3, .min_periods = 2 });
    defer rolling_drawdown.deinit();
    try std.testing.expectEqual(@as(usize, 6), rolling_drawdown.width());
    const rolling_peak = try (try rolling_drawdown.column("equity_rolling_peak")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_peak);
    const rolling_drawdown_values = try (try rolling_drawdown.column("equity_rolling_drawdown")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_drawdown_values);
    const rolling_drawdown_pct = try (try rolling_drawdown.column("equity_rolling_drawdown_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_drawdown_pct);
    const rolling_peak_age = try (try rolling_drawdown.column("equity_rolling_peak_age")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_peak_age);
    const rolling_drawdown_validity = try (try rolling_drawdown.column("equity_rolling_drawdown")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_drawdown_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false }, rolling_drawdown_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 120.0), rolling_peak[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 120.0), rolling_peak[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 130.0), rolling_peak[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 130.0), rolling_peak[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_drawdown_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -30.0), rolling_drawdown_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_drawdown_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -50.0), rolling_drawdown_values[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_drawdown_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.25), rolling_drawdown_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_drawdown_pct[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -50.0 / 130.0), rolling_drawdown_pct[4], 1e-12);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 0, 1, 0 }, rolling_peak_age);

    var extrema = try equity_table.extremaProfile("equity", "equity", .{ .min_periods = 2 });
    defer extrema.deinit();
    try std.testing.expectEqual(@as(usize, 6), extrema.width());
    const running_low = try (try extrema.column("equity_running_low")).f64.toOwnedSlice(gpa);
    defer gpa.free(running_low);
    const running_high = try (try extrema.column("equity_running_high")).f64.toOwnedSlice(gpa);
    defer gpa.free(running_high);
    const new_low = try (try extrema.column("equity_new_low")).bool.toOwnedSlice(gpa);
    defer gpa.free(new_low);
    const new_high = try (try extrema.column("equity_new_high")).bool.toOwnedSlice(gpa);
    defer gpa.free(new_high);
    const extrema_validity = try (try extrema.column("equity_running_low")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(extrema_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false }, extrema_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 100.0), running_low[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 90.0), running_low[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 90.0), running_low[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 80.0), running_low[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 120.0), running_high[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 120.0), running_high[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 130.0), running_high[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 130.0), running_high[4], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false, true, false }, new_low);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, false, false }, new_high);

    var trend_source = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 3.0, 2.0, 2.0, 5.0, 0.0, 4.0 }, &.{ true, true, true, true, true, false, true }, .cpu);
    defer trend_source.deinit();
    var trend_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5, 6, 7 }, .cpu);
    defer trend_id.deinit();
    var trend_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "price", .data = trend_source },
        .{ .name = "id", .data = trend_id },
    });
    defer trend_table.deinit();

    var trend = try trend_table.trendProfile("price", "price", .{ .periods = 1 });
    defer trend.deinit();
    try std.testing.expectEqual(@as(usize, 7), trend.width());
    const trend_values = try (try trend.column("price_trend")).i64.toOwnedSlice(gpa);
    defer gpa.free(trend_values);
    const up_streak = try (try trend.column("price_up_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(up_streak);
    const down_streak = try (try trend.column("price_down_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(down_streak);
    const flat_streak = try (try trend.column("price_flat_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(flat_streak);
    const reversal = try (try trend.column("price_reversal")).bool.toOwnedSlice(gpa);
    defer gpa.free(reversal);
    const trend_validity = try (try trend.column("price_trend")).i64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(trend_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false, false }, trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, -1, 0, 1, 0, 0 }, trend_values);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 0, 0, 1, 0, 0 }, up_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 0, 0, 0, 0 }, down_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 1, 0, 0, 0 }, flat_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false, true, false, false }, reversal);

    var rolling_trends = try trend_table.rollingTrendProfile("price", "price", .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_trends.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_trends.width());
    const rolling_trend_count = try (try rolling_trends.column("price_rolling_trend_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_trend_count);
    const rolling_up_rate = try (try rolling_trends.column("price_rolling_up_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_up_rate);
    const rolling_down_rate = try (try rolling_trends.column("price_rolling_down_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_down_rate);
    const rolling_flat_rate = try (try rolling_trends.column("price_rolling_flat_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_flat_rate);
    const rolling_reversal_rate = try (try rolling_trends.column("price_rolling_reversal_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_reversal_rate);
    const rolling_trend_validity = try (try rolling_trends.column("price_rolling_up_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 3, 2, 1 }, rolling_trend_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, false }, rolling_trend_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_up_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_up_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_up_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_up_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_down_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_down_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_flat_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_reversal_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_reversal_rate[5], 1e-12);

    var expanding_trends = try trend_table.expandingTrendProfile("price", "price", .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_trends.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_trends.width());
    const expanding_trend_count = try (try expanding_trends.column("price_expanding_trend_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_trend_count);
    const expanding_up_rate = try (try expanding_trends.column("price_expanding_up_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_up_rate);
    const expanding_down_rate = try (try expanding_trends.column("price_expanding_down_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_down_rate);
    const expanding_flat_rate = try (try expanding_trends.column("price_expanding_flat_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_flat_rate);
    const expanding_reversal_rate = try (try expanding_trends.column("price_expanding_reversal_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_reversal_rate);
    const expanding_trend_validity = try (try expanding_trends.column("price_expanding_up_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 4, 4, 4 }, expanding_trend_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, true }, expanding_trend_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_up_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_up_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_up_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_down_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_down_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_down_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_flat_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_flat_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_reversal_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_reversal_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_reversal_rate[4], 1e-12);

    var changes = try trend_table.changePointProfile("price", "price", 2.0, .{ .periods = 1 });
    defer changes.deinit();
    try std.testing.expectEqual(@as(usize, 6), changes.width());
    const change_delta = try (try changes.column("price_change_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(change_delta);
    const change_abs_delta = try (try changes.column("price_change_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(change_abs_delta);
    const change_pct = try (try changes.column("price_change_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(change_pct);
    const change_point = try (try changes.column("price_change_point")).bool.toOwnedSlice(gpa);
    defer gpa.free(change_point);
    const change_validity = try (try changes.column("price_change_delta")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(change_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false, false }, change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), change_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), change_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), change_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), change_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), change_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), change_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), change_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), change_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), change_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0 / 3.0), change_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), change_pct[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), change_pct[4], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false, true, false, false }, change_point);

    var rolling_changes = try trend_table.rollingChangePointProfile("price", "price", 2.0, .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_changes.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_changes.width());
    const rolling_change_count = try (try rolling_changes.column("price_rolling_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_count);
    const rolling_change_point_count = try (try rolling_changes.column("price_rolling_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_point_count);
    const rolling_change_rate = try (try rolling_changes.column("price_rolling_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_rate);
    const rolling_mean_abs_delta = try (try rolling_changes.column("price_rolling_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean_abs_delta);
    const rolling_max_abs_delta = try (try rolling_changes.column("price_rolling_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_max_abs_delta);
    const rolling_change_validity = try (try rolling_changes.column("price_rolling_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 3, 2, 1 }, rolling_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 1, 1, 1 }, rolling_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, false }, rolling_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_change_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_change_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), rolling_mean_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_mean_abs_delta[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_max_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_max_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_max_abs_delta[5], 1e-12);

    var expanding_changes = try trend_table.expandingChangePointProfile("price", "price", 2.0, .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_changes.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_changes.width());
    const expanding_change_count = try (try expanding_changes.column("price_expanding_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_count);
    const expanding_change_point_count = try (try expanding_changes.column("price_expanding_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_point_count);
    const expanding_change_rate = try (try expanding_changes.column("price_expanding_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_rate);
    const expanding_mean_abs_delta = try (try expanding_changes.column("price_expanding_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean_abs_delta);
    const expanding_max_abs_delta = try (try expanding_changes.column("price_expanding_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_max_abs_delta);
    const expanding_change_validity = try (try expanding_changes.column("price_expanding_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 4, 4, 4 }, expanding_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 2, 2, 2 }, expanding_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, true }, expanding_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_change_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_mean_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_max_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_max_abs_delta[4], 1e-12);

    var signed_values_col = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ -1.0, -2.0, 0.0, 3.0, -4.0, 0.0, 5.0 }, &.{ true, true, true, true, true, false, true }, .cpu);
    defer signed_values_col.deinit();
    var signed_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "signal", .data = signed_values_col },
    });
    defer signed_table.deinit();
    var sign = try signed_table.signProfile("signal", "signal", .{ .periods = 1 });
    defer sign.deinit();
    try std.testing.expectEqual(@as(usize, 6), sign.width());
    const sign_values = try (try sign.column("signal_sign")).i64.toOwnedSlice(gpa);
    defer gpa.free(sign_values);
    const sign_flip = try (try sign.column("signal_sign_flip")).bool.toOwnedSlice(gpa);
    defer gpa.free(sign_flip);
    const positive_streak = try (try sign.column("signal_positive_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(positive_streak);
    const negative_streak = try (try sign.column("signal_negative_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(negative_streak);
    const zero_streak = try (try sign.column("signal_zero_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(zero_streak);
    const sign_validity = try (try sign.column("signal_sign")).i64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(sign_validity);
    const flip_validity = try (try sign.column("signal_sign_flip")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(flip_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, true, false, true }, sign_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false, false }, flip_validity);
    try std.testing.expectEqualSlices(i64, &.{ -1, -1, 0, 1, -1, 0, 1 }, sign_values);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, false, false }, sign_flip);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 1, 0, 0, 1 }, positive_streak);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 0, 0, 1, 0, 0 }, negative_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 0, 0, 0, 0 }, zero_streak);

    var rolling_sign = try signed_table.rollingSignProfile("signal", "signal", .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_sign.deinit();
    try std.testing.expectEqual(@as(usize, 6), rolling_sign.width());
    const rolling_sign_count = try (try rolling_sign.column("signal_rolling_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_sign_count);
    const rolling_positive_rate = try (try rolling_sign.column("signal_rolling_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_positive_rate);
    const rolling_negative_rate = try (try rolling_sign.column("signal_rolling_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_negative_rate);
    const rolling_zero_rate = try (try rolling_sign.column("signal_rolling_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_zero_rate);
    const rolling_flip_rate = try (try rolling_sign.column("signal_rolling_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_flip_rate);
    const rolling_sign_rate_validity = try (try rolling_sign.column("signal_rolling_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_sign_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 3, 2, 2 }, rolling_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, rolling_sign_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_positive_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_positive_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_negative_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_zero_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_zero_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_flip_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_flip_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_flip_rate[6], 1e-12);

    var expanding_sign = try signed_table.expandingSignProfile("signal", "signal", .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_sign.deinit();
    try std.testing.expectEqual(@as(usize, 6), expanding_sign.width());
    const expanding_sign_count = try (try expanding_sign.column("signal_expanding_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_sign_count);
    const expanding_positive_rate = try (try expanding_sign.column("signal_expanding_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_positive_rate);
    const expanding_negative_rate = try (try expanding_sign.column("signal_expanding_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_negative_rate);
    const expanding_zero_rate = try (try expanding_sign.column("signal_expanding_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_zero_rate);
    const expanding_flip_rate = try (try expanding_sign.column("signal_expanding_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_flip_rate);
    const expanding_sign_rate_validity = try (try expanding_sign.column("signal_expanding_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_sign_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 5, 6 }, expanding_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, expanding_sign_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), expanding_positive_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_positive_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_negative_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), expanding_negative_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_negative_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_zero_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), expanding_zero_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_flip_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_flip_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), expanding_flip_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_flip_rate[6], 1e-12);

    var validity = try trend_table.validityProfile("price", "price");
    defer validity.deinit();
    try std.testing.expectEqual(@as(usize, 6), validity.width());
    const is_null = try (try validity.column("price_is_null")).bool.toOwnedSlice(gpa);
    defer gpa.free(is_null);
    const is_valid = try (try validity.column("price_is_valid")).bool.toOwnedSlice(gpa);
    defer gpa.free(is_valid);
    const valid_streak = try (try validity.column("price_valid_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(valid_streak);
    const null_streak = try (try validity.column("price_null_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(null_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false, false, true, false }, is_null);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, true, false, true }, is_valid);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 0, 1 }, valid_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 1, 0 }, null_streak);

    var rolling_quality = try trend_table.rollingValidityProfile("price", "price", .{ .window = 3, .min_periods = 2 });
    defer rolling_quality.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_quality.width());
    const rolling_validity_count = try (try rolling_quality.column("price_rolling_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_validity_count);
    const rolling_valid_count = try (try rolling_quality.column("price_rolling_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_valid_count);
    const rolling_null_count = try (try rolling_quality.column("price_rolling_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_null_count);
    const rolling_valid_rate = try (try rolling_quality.column("price_rolling_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_valid_rate);
    const rolling_null_rate = try (try rolling_quality.column("price_rolling_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_null_rate);
    const rolling_validity_rate_validity = try (try rolling_quality.column("price_rolling_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_validity_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 3, 3, 3 }, rolling_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 3, 2, 2 }, rolling_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 1, 1 }, rolling_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, rolling_validity_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_valid_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_valid_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_valid_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_null_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_null_rate[6], 1e-12);

    var expanding_quality = try trend_table.expandingValidityProfile("price", "price", .{ .min_periods = 2 });
    defer expanding_quality.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_quality.width());
    const expanding_validity_count = try (try expanding_quality.column("price_expanding_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity_count);
    const expanding_valid_count = try (try expanding_quality.column("price_expanding_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_valid_count);
    const expanding_null_count = try (try expanding_quality.column("price_expanding_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_null_count);
    const expanding_valid_rate = try (try expanding_quality.column("price_expanding_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_valid_rate);
    const expanding_null_rate = try (try expanding_quality.column("price_expanding_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_null_rate);
    const expanding_validity_rate_validity = try (try expanding_quality.column("price_expanding_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity_rate_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 6, 7 }, expanding_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 5, 5, 6 }, expanding_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0, 0, 1, 1 }, expanding_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, true, true }, expanding_validity_rate_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_valid_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 6.0), expanding_valid_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.0 / 7.0), expanding_valid_rate[6], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 6.0), expanding_null_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 7.0), expanding_null_rate[6], 1e-12);
}
