const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("dataframe_lazy_test_helpers.zig").lazyCollectTable;

test "device lazy frame collects clip operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var clip_plan = try DeviceLazyFrame.init(gpa, table);
    defer clip_plan.deinit();
    try clip_plan.clipProfile("sales", "sales", .{ .lower = 3.0, .upper = 5.0 });
    try clip_plan.select(&.{ "sales", "sales_clipped", "sales_below", "sales_above", "sales_in_range" });
    const clip_explain = try clip_plan.explain(gpa);
    defer gpa.free(clip_explain);
    try std.testing.expect(std.mem.indexOf(u8, clip_explain, "clip_profile(sales") != null);
    var lazy_clip = try clip_plan.collect();
    defer lazy_clip.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_clip.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_clip.width());
    const lazy_clipped = try (try lazy_clip.column("sales_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_clipped);
    const lazy_below = try (try lazy_clip.column("sales_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_below);
    const lazy_above = try (try lazy_clip.column("sales_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_above);
    const lazy_in_range = try (try lazy_clip.column("sales_in_range")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_in_range);
    try std.testing.expectEqualSlices(f64, &.{ 3.0, 3.0, 5.0, 5.0 }, lazy_clipped);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false }, lazy_below);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true }, lazy_above);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, false }, lazy_in_range);
}

test "device lazy frame collects rolling clip operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_clip_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_clip_plan.deinit();
    try rolling_clip_plan.rollingClipProfile("sales", "sales", .{ .lower = 3.0, .upper = 5.0 }, .{ .window = 2, .min_periods = 2 });
    try rolling_clip_plan.select(&.{ "sales", "sales_rolling_clip_count", "sales_rolling_mean_clipped", "sales_rolling_clipped_rate", "sales_rolling_clip_below_rate", "sales_rolling_clip_above_rate", "sales_rolling_clip_in_range_rate" });
    const rolling_clip_explain = try rolling_clip_plan.explain(gpa);
    defer gpa.free(rolling_clip_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_clip_explain, "rolling_clip_profile(sales") != null);
    var lazy_rolling_clip = try rolling_clip_plan.collect();
    defer lazy_rolling_clip.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_clip.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_rolling_clip.width());
    const lazy_rolling_clip_count = try (try lazy_rolling_clip.column("sales_rolling_clip_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_count);
    const lazy_rolling_mean_clipped = try (try lazy_rolling_clip.column("sales_rolling_mean_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_clipped);
    const lazy_rolling_clipped_rate = try (try lazy_rolling_clip.column("sales_rolling_clipped_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clipped_rate);
    const lazy_rolling_clip_below_rate = try (try lazy_rolling_clip.column("sales_rolling_clip_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_below_rate);
    const lazy_rolling_clip_above_rate = try (try lazy_rolling_clip.column("sales_rolling_clip_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_above_rate);
    const lazy_rolling_clip_in_range_rate = try (try lazy_rolling_clip.column("sales_rolling_clip_in_range_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_in_range_rate);
    const lazy_rolling_clip_validity = try (try lazy_rolling_clip.column("sales_rolling_mean_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_clip_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_clip_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_mean_clipped[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_rolling_mean_clipped[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_mean_clipped[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clipped_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clipped_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clipped_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_clip_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_in_range_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_clip_in_range_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_clip_in_range_rate[3], 1e-12);
}

test "device lazy frame collects expanding clip operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_clip_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_clip_plan.deinit();
    try expanding_clip_plan.expandingClipProfile("sales", "sales", .{ .lower = 3.0, .upper = 5.0 }, .{ .min_periods = 2 });
    try expanding_clip_plan.select(&.{ "sales", "sales_expanding_clip_count", "sales_expanding_mean_clipped", "sales_expanding_clipped_rate", "sales_expanding_clip_below_rate", "sales_expanding_clip_above_rate", "sales_expanding_clip_in_range_rate" });
    const expanding_clip_explain = try expanding_clip_plan.explain(gpa);
    defer gpa.free(expanding_clip_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_clip_explain, "expanding_clip_profile(sales") != null);
    var lazy_expanding_clip = try expanding_clip_plan.collect();
    defer lazy_expanding_clip.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_clip.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_expanding_clip.width());
    const lazy_expanding_clip_count = try (try lazy_expanding_clip.column("sales_expanding_clip_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_count);
    const lazy_expanding_mean_clipped = try (try lazy_expanding_clip.column("sales_expanding_mean_clipped")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_clipped);
    const lazy_expanding_clipped_rate = try (try lazy_expanding_clip.column("sales_expanding_clipped_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clipped_rate);
    const lazy_expanding_clip_below_rate = try (try lazy_expanding_clip.column("sales_expanding_clip_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_below_rate);
    const lazy_expanding_clip_above_rate = try (try lazy_expanding_clip.column("sales_expanding_clip_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_above_rate);
    const lazy_expanding_clip_in_range_rate = try (try lazy_expanding_clip.column("sales_expanding_clip_in_range_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_in_range_rate);
    const lazy_expanding_clip_validity = try (try lazy_expanding_clip.column("sales_expanding_mean_clipped")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_clip_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_clip_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_clip_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_mean_clipped[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 11.0 / 3.0), lazy_expanding_mean_clipped[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), lazy_expanding_mean_clipped[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clipped_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_clipped_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clipped_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clip_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_clip_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_clip_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_clip_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_clip_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_clip_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clip_in_range_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_clip_in_range_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_clip_in_range_rate[3], 1e-12);
}

test "device lazy frame collects threshold operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var threshold_plan = try DeviceLazyFrame.init(gpa, table);
    defer threshold_plan.deinit();
    try threshold_plan.thresholdProfile("sales", "sales", .{ .threshold = 5.0 });
    try threshold_plan.select(&.{ "sales", "sales_distance", "sales_abs_distance", "sales_above", "sales_below", "sales_at" });
    const threshold_explain = try threshold_plan.explain(gpa);
    defer gpa.free(threshold_explain);
    try std.testing.expect(std.mem.indexOf(u8, threshold_explain, "threshold_profile(sales") != null);
    var lazy_threshold = try threshold_plan.collect();
    defer lazy_threshold.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_threshold.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_threshold.width());
    const lazy_distance = try (try lazy_threshold.column("sales_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_distance);
    const lazy_abs_distance = try (try lazy_threshold.column("sales_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_abs_distance);
    const lazy_above_threshold = try (try lazy_threshold.column("sales_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_above_threshold);
    const lazy_below_threshold = try (try lazy_threshold.column("sales_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_below_threshold);
    const lazy_at_threshold = try (try lazy_threshold.column("sales_at")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_at_threshold);
    try std.testing.expectEqualSlices(f64, &.{ -3.0, -2.0, 0.0, 2.0 }, lazy_distance);
    try std.testing.expectEqualSlices(f64, &.{ 3.0, 2.0, 0.0, 2.0 }, lazy_abs_distance);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, true }, lazy_above_threshold);
    try std.testing.expectEqualSlices(bool, &.{ true, true, false, false }, lazy_below_threshold);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false }, lazy_at_threshold);
}

test "device lazy frame collects rolling threshold operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_threshold_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_threshold_plan.deinit();
    try rolling_threshold_plan.rollingThresholdProfile("sales", "sales", 4.0, .{ .window = 2, .min_periods = 2 });
    try rolling_threshold_plan.select(&.{ "sales", "sales_rolling_threshold_count", "sales_rolling_mean_distance", "sales_rolling_mean_abs_distance", "sales_rolling_above_rate", "sales_rolling_below_rate", "sales_rolling_at_rate" });
    const rolling_threshold_explain = try rolling_threshold_plan.explain(gpa);
    defer gpa.free(rolling_threshold_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_threshold_explain, "rolling_threshold_profile(sales") != null);
    var lazy_rolling_threshold = try rolling_threshold_plan.collect();
    defer lazy_rolling_threshold.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_threshold.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_rolling_threshold.width());
    const lazy_rolling_threshold_count = try (try lazy_rolling_threshold.column("sales_rolling_threshold_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_threshold_count);
    const lazy_rolling_mean_distance = try (try lazy_rolling_threshold.column("sales_rolling_mean_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_distance);
    const lazy_rolling_mean_abs_distance = try (try lazy_rolling_threshold.column("sales_rolling_mean_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_abs_distance);
    const lazy_rolling_above_rate = try (try lazy_rolling_threshold.column("sales_rolling_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_above_rate);
    const lazy_rolling_below_rate = try (try lazy_rolling_threshold.column("sales_rolling_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_below_rate);
    const lazy_rolling_at_rate = try (try lazy_rolling_threshold.column("sales_rolling_at_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_at_rate);
    const lazy_rolling_threshold_validity = try (try lazy_rolling_threshold.column("sales_rolling_mean_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_threshold_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_threshold_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_threshold_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), lazy_rolling_mean_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_mean_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_rolling_mean_abs_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_mean_abs_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_abs_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_below_rate[3], 1e-12);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 0.0, 0.0, 0.0 }, lazy_rolling_at_rate);
}

test "device lazy frame collects expanding threshold operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_threshold_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_threshold_plan.deinit();
    try expanding_threshold_plan.expandingThresholdProfile("sales", "sales", 4.0, .{ .min_periods = 2 });
    try expanding_threshold_plan.select(&.{ "sales", "sales_expanding_threshold_count", "sales_expanding_mean_distance", "sales_expanding_mean_abs_distance", "sales_expanding_above_rate", "sales_expanding_below_rate", "sales_expanding_at_rate" });
    const expanding_threshold_explain = try expanding_threshold_plan.explain(gpa);
    defer gpa.free(expanding_threshold_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_threshold_explain, "expanding_threshold_profile(sales") != null);
    var lazy_expanding_threshold = try expanding_threshold_plan.collect();
    defer lazy_expanding_threshold.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_threshold.height());
    try std.testing.expectEqual(@as(usize, 7), lazy_expanding_threshold.width());
    const lazy_expanding_threshold_count = try (try lazy_expanding_threshold.column("sales_expanding_threshold_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_threshold_count);
    const lazy_expanding_mean_distance = try (try lazy_expanding_threshold.column("sales_expanding_mean_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_distance);
    const lazy_expanding_mean_abs_distance = try (try lazy_expanding_threshold.column("sales_expanding_mean_abs_distance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_abs_distance);
    const lazy_expanding_above_rate = try (try lazy_expanding_threshold.column("sales_expanding_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_above_rate);
    const lazy_expanding_below_rate = try (try lazy_expanding_threshold.column("sales_expanding_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_below_rate);
    const lazy_expanding_at_rate = try (try lazy_expanding_threshold.column("sales_expanding_at_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_at_rate);
    const lazy_expanding_threshold_validity = try (try lazy_expanding_threshold.column("sales_expanding_mean_distance")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_threshold_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_threshold_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_threshold_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), lazy_expanding_mean_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0 / 3.0), lazy_expanding_mean_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_mean_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_mean_abs_distance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), lazy_expanding_mean_abs_distance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), lazy_expanding_mean_abs_distance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_below_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_below_rate[3], 1e-12);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 0.0, 0.0, 0.0 }, lazy_expanding_at_rate);
}
