const std = @import("std");
const boltha = @import("boltha");
const vectra = @import("vectra");

const DataFrame = vectra.DataFrame;
const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;
const DeviceLazyFrame = vectra.DeviceLazyFrame;
const DeviceDType = vectra.DeviceDType;
const DeviceValidityEncoding = vectra.DeviceValidityEncoding;
const DeviceParquetScan = vectra.DeviceParquetScan;

test "device dataframe rolling profile methods" {
    const gpa = std.testing.allocator;

    var rolling_sales = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 2.0, 100.0, 4.0, 5.0 }, &.{ true, true, false, true, true }, .cpu);
    defer rolling_sales.deinit();
    var rolling_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5 }, .cpu);
    defer rolling_id.deinit();
    var rolling_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "sales", .data = rolling_sales },
        .{ .name = "id", .data = rolling_id },
    });
    defer rolling_table.deinit();

    var rolling = try rolling_table.rollingProfile("sales", "sales", .{ .window = 3, .min_periods = 2 });
    defer rolling.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling.width());
    const rolling_count = try (try rolling.column("sales_rolling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_count);
    const rolling_sum = try (try rolling.column("sales_rolling_sum")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_sum);
    const rolling_mean = try (try rolling.column("sales_rolling_mean")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean);
    const rolling_variance = try (try rolling.column("sales_rolling_variance")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_variance);
    const rolling_stddev = try (try rolling.column("sales_rolling_stddev")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_stddev);
    const rolling_validity = try (try rolling.column("sales_rolling_mean")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2, 2 }, rolling_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_sum[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_sum[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 6.0), rolling_sum[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 9.0), rolling_sum[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_mean[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_mean[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_mean[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.5), rolling_mean[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), rolling_variance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), rolling_variance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_variance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), rolling_variance[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_stddev[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_stddev[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_stddev[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_stddev[4], 1e-12);

    var rolling_moments = try rolling_table.rollingMomentProfile("sales", "sales", .{ .window = 3, .min_periods = 2 });
    defer rolling_moments.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_moments.width());
    const rolling_moment_count = try (try rolling_moments.column("sales_rolling_moment_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_moment_count);
    const rolling_m3 = try (try rolling_moments.column("sales_rolling_m3")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_m3);
    const rolling_m4 = try (try rolling_moments.column("sales_rolling_m4")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_m4);
    const rolling_skewness = try (try rolling_moments.column("sales_rolling_skewness")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_skewness);
    const rolling_kurtosis = try (try rolling_moments.column("sales_rolling_kurtosis")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_kurtosis);
    const rolling_moment_validity = try (try rolling_moments.column("sales_rolling_skewness")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_moment_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2, 2 }, rolling_moment_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_moment_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_m3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_m3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0625), rolling_m4[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_m4[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_skewness[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_skewness[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), rolling_kurtosis[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), rolling_kurtosis[3], 1e-12);

    var rolling_robust = try rolling_table.rollingRobustProfile("sales", "sales", .{ .window = 3, .min_periods = 2 });
    defer rolling_robust.deinit();
    try std.testing.expectEqual(@as(usize, 6), rolling_robust.width());
    const rolling_median_centered = try (try rolling_robust.column("sales_rolling_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_median_centered);
    const rolling_mad_zscore = try (try rolling_robust.column("sales_rolling_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mad_zscore);
    const rolling_iqr_outlier = try (try rolling_robust.column("sales_rolling_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(rolling_iqr_outlier);
    const rolling_winsorized = try (try rolling_robust.column("sales_rolling_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_winsorized);
    const rolling_robust_validity = try (try rolling_robust.column("sales_rolling_median_centered")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_robust_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, true }, rolling_robust_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_median_centered[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), rolling_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), rolling_mad_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), rolling_mad_zscore[4], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false, false }, rolling_iqr_outlier);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_winsorized[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), rolling_winsorized[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), rolling_winsorized[4], 1e-12);

    var ema = try rolling_table.emaProfile("sales", "sales", .{ .alpha = 0.5, .min_periods = 2 });
    defer ema.deinit();
    try std.testing.expectEqual(@as(usize, 5), ema.width());
    const ema_values = try (try ema.column("sales_ema")).f64.toOwnedSlice(gpa);
    defer gpa.free(ema_values);
    const ema_residual = try (try ema.column("sales_ema_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(ema_residual);
    const ema_ratio = try (try ema.column("sales_ema_ratio")).f64.toOwnedSlice(gpa);
    defer gpa.free(ema_ratio);
    const ema_validity = try (try ema.column("sales_ema")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(ema_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, true }, ema_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), ema_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), ema_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.875), ema_values[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), ema_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), ema_residual[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.125), ema_residual[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 1.5), ema_ratio[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 2.75), ema_ratio[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.875), ema_ratio[4], 1e-12);

    var rolling_range = try rolling_table.rollingRangeProfile("sales", "sales", .{ .window = 3, .min_periods = 2 });
    defer rolling_range.deinit();
    try std.testing.expectEqual(@as(usize, 6), rolling_range.width());
    const rolling_low = try (try rolling_range.column("sales_rolling_low")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_low);
    const rolling_high = try (try rolling_range.column("sales_rolling_high")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_high);
    const rolling_spread = try (try rolling_range.column("sales_rolling_range")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_spread);
    const rolling_position = try (try rolling_range.column("sales_rolling_position")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_position);
    const rolling_range_validity = try (try rolling_range.column("sales_rolling_range")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_range_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, true }, rolling_range_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_low[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_low[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), rolling_low[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_high[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0), rolling_high[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), rolling_high[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_spread[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_spread[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_position[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_position[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_position[4], 1e-12);

    var rolling_normalized = try rolling_table.rollingNormalizeProfile("sales", "sales", .{ .window = 3, .min_periods = 2 });
    defer rolling_normalized.deinit();
    try std.testing.expectEqual(@as(usize, 5), rolling_normalized.width());
    const rolling_centered = try (try rolling_normalized.column("sales_rolling_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_centered);
    const rolling_zscore = try (try rolling_normalized.column("sales_rolling_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_zscore);
    const rolling_minmax = try (try rolling_normalized.column("sales_rolling_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_minmax);
    const rolling_norm_validity = try (try rolling_normalized.column("sales_rolling_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_norm_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, true }, rolling_norm_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_centered[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_zscore[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_minmax[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_minmax[4], 1e-12);

    var rolling_quantiles = try rolling_table.rollingQuantileProfile("sales", "sales", .{ .window = 3, .min_periods = 2 });
    defer rolling_quantiles.deinit();
    try std.testing.expectEqual(@as(usize, 6), rolling_quantiles.width());
    const rolling_q1 = try (try rolling_quantiles.column("sales_rolling_q1")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_q1);
    const rolling_median = try (try rolling_quantiles.column("sales_rolling_median")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_median);
    const rolling_q3 = try (try rolling_quantiles.column("sales_rolling_q3")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_q3);
    const rolling_iqr = try (try rolling_quantiles.column("sales_rolling_iqr")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_iqr);
    const rolling_quantile_validity = try (try rolling_quantiles.column("sales_rolling_median")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_quantile_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, true, true }, rolling_quantile_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), rolling_q1[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), rolling_q1[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.25), rolling_q1[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_median[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_median[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.5), rolling_median[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), rolling_q3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.5), rolling_q3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.75), rolling_q3[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_iqr[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_iqr[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_iqr[4], 1e-12);

    var expanding_quantiles = try rolling_table.expandingQuantileProfile("sales", "sales", .{ .min_periods = 2 });
    defer expanding_quantiles.deinit();
    try std.testing.expectEqual(@as(usize, 6), expanding_quantiles.width());
    const expanding_q1 = try (try expanding_quantiles.column("sales_expanding_q1")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_q1);
    const expanding_median = try (try expanding_quantiles.column("sales_expanding_median")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_median);
    const expanding_q3 = try (try expanding_quantiles.column("sales_expanding_q3")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_q3);
    const expanding_iqr = try (try expanding_quantiles.column("sales_expanding_iqr")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_iqr);
    const expanding_quantile_validity = try (try expanding_quantiles.column("sales_expanding_median")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_quantile_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_quantile_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), expanding_q1[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), expanding_q1[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_q1[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), expanding_q1[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_median[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_median[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_median[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_median[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), expanding_q3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), expanding_q3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_q3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.25), expanding_q3[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_iqr[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_iqr[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_iqr[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), expanding_iqr[4], 1e-12);
}
