//! Lazy dataframe operation tags and ownership helpers.
//!
//! `DeviceLazyOp` carries many operation payload variants and therefore used to
//! dominate the public dataframe facade. Keeping the union generic over the
//! concrete dataframe/column types avoids an import cycle while moving the
//! clone/deinit ownership rules into a focused module.

const std = @import("std");
const array_mod = @import("array.zig");
const ownership_mod = @import("dataframe_lazy_op_ownership.zig");
const payloads_mod = @import("dataframe_lazy_op_payloads.zig");
const series_mod = @import("series.zig");

const DeviceDataError = series_mod.DataError || array_mod.ArrayError;

pub const DeviceLazyGroupByAggregation = payloads_mod.DeviceLazyGroupByAggregation;
pub const DeviceLazyWeightedGroupByAggregation = payloads_mod.DeviceLazyWeightedGroupByAggregation;
pub const DeviceLazyPairGroupByAggregation = payloads_mod.DeviceLazyPairGroupByAggregation;
pub const DeviceLazyWeightedPairGroupByAggregation = payloads_mod.DeviceLazyWeightedPairGroupByAggregation;
pub const DeviceLazyJoinKind = payloads_mod.DeviceLazyJoinKind;

pub fn DeviceLazyOp(comptime DeviceDataFrame: type, comptime DeviceColumn: type) type {
    const Payloads = payloads_mod.DeviceLazyPayloads(DeviceDataFrame, DeviceColumn);
    return union(enum) {
        const Self = @This();
        select: Payloads.Select,
        select_column_indices: Payloads.ColumnIndices,
        select_column_range: Payloads.ColumnRange,
        select_last_columns: Payloads.HeadTail,
        drop_column_indices: Payloads.ColumnIndices,
        drop_column_range: Payloads.ColumnRange,
        drop_last_columns: Payloads.HeadTail,
        reverse_columns,
        sort_columns_by_name: Payloads.SortColumnsByName,
        select_name_prefix: Payloads.NamePattern,
        select_name_suffix: Payloads.NamePattern,
        select_name_contains: Payloads.NamePattern,
        select_name_glob: Payloads.NamePattern,
        drop_name_prefix: Payloads.NamePattern,
        drop_name_suffix: Payloads.NamePattern,
        drop_name_contains: Payloads.NamePattern,
        drop_name_glob: Payloads.NamePattern,
        select_dtypes: Payloads.DTypes,
        select_dtype_class: Payloads.DTypeClass,
        drop_dtypes: Payloads.DTypes,
        drop_dtype_class: Payloads.DTypeClass,
        select_nullable_columns,
        select_non_nullable_columns,
        select_columns_with_nulls,
        select_columns_without_nulls,
        drop_nullable_columns,
        drop_non_nullable_columns,
        drop_columns_with_nulls,
        drop_columns_without_nulls,
        select_columns_with_nans,
        select_columns_without_nans,
        drop_columns_with_nans,
        drop_columns_without_nans,
        select_columns_with_infs,
        select_columns_without_infs,
        drop_columns_with_infs,
        drop_columns_without_infs,
        select_columns_with_positive_infs,
        select_columns_without_positive_infs,
        drop_columns_with_positive_infs,
        drop_columns_without_positive_infs,
        select_columns_with_negative_infs,
        select_columns_without_negative_infs,
        drop_columns_with_negative_infs,
        drop_columns_without_negative_infs,
        select_columns_with_zeros,
        select_columns_without_zeros,
        drop_columns_with_zeros,
        drop_columns_without_zeros,
        select_columns_with_positive_zeros,
        select_columns_without_positive_zeros,
        drop_columns_with_positive_zeros,
        drop_columns_without_positive_zeros,
        select_columns_with_negative_zeros,
        select_columns_without_negative_zeros,
        drop_columns_with_negative_zeros,
        drop_columns_without_negative_zeros,
        select_columns_with_non_zeros,
        select_columns_without_non_zeros,
        drop_columns_with_non_zeros,
        drop_columns_without_non_zeros,
        select_columns_with_positives,
        select_columns_without_positives,
        drop_columns_with_positives,
        drop_columns_without_positives,
        select_columns_with_signbits,
        select_columns_without_signbits,
        drop_columns_with_signbits,
        drop_columns_without_signbits,
        select_columns_with_negatives,
        select_columns_without_negatives,
        drop_columns_with_negatives,
        drop_columns_without_negatives,
        select_columns_with_finites,
        select_columns_without_finites,
        drop_columns_with_finites,
        drop_columns_without_finites,
        select_columns_with_normals,
        select_columns_without_normals,
        drop_columns_with_normals,
        drop_columns_without_normals,
        select_columns_with_subnormals,
        select_columns_without_subnormals,
        drop_columns_with_subnormals,
        drop_columns_without_subnormals,
        select_columns_with_non_finites,
        select_columns_without_non_finites,
        drop_columns_with_non_finites,
        drop_columns_without_non_finites,
        with_row_index: Payloads.RowIndex,
        rename_column: Payloads.RenameColumn,
        rename_columns: Payloads.RenameColumns,
        add_column_name_prefix: Payloads.RenameNamePattern,
        add_column_name_suffix: Payloads.RenameNamePattern,
        strip_column_name_prefix: Payloads.RenameNamePattern,
        strip_column_name_suffix: Payloads.RenameNamePattern,
        replace_column_name_prefix: Payloads.RenameNameReplacement,
        replace_column_name_suffix: Payloads.RenameNameReplacement,
        move_column: Payloads.MoveColumn,
        move_column_before: Payloads.MoveColumnRelative,
        move_column_after: Payloads.MoveColumnRelative,
        copy_column: Payloads.CopyColumn,
        copy_column_at: Payloads.CopyColumnAt,
        copy_column_before: Payloads.CopyColumnRelative,
        copy_column_after: Payloads.CopyColumnRelative,
        drop_columns: Payloads.DropColumns,
        drop_nulls: Payloads.DropNulls,
        drop_all_nulls: Payloads.DropNulls,
        filter_all_nulls: Payloads.DropNulls,
        filter_nulls_column: Payloads.FilterColumn,
        filter_between_column: Payloads.RangeFilterColumn,
        filter_isin_column: Payloads.MembershipFilterColumn,
        filter_isin_values: Payloads.FilterIsInValues,
        drop_nans: Payloads.DropNulls,
        filter_nans_column: Payloads.FilterColumn,
        drop_infs: Payloads.DropNulls,
        filter_infs_column: Payloads.FilterColumn,
        drop_positive_infs: Payloads.DropNulls,
        filter_positive_infs_column: Payloads.FilterColumn,
        drop_negative_infs: Payloads.DropNulls,
        filter_negative_infs_column: Payloads.FilterColumn,
        drop_zeros: Payloads.DropNulls,
        filter_zeros_column: Payloads.FilterColumn,
        drop_positive_zeros: Payloads.DropNulls,
        filter_positive_zeros_column: Payloads.FilterColumn,
        drop_negative_zeros: Payloads.DropNulls,
        filter_negative_zeros_column: Payloads.FilterColumn,
        drop_non_zeros: Payloads.DropNulls,
        filter_non_zeros_column: Payloads.FilterColumn,
        drop_positives: Payloads.DropNulls,
        filter_positives_column: Payloads.FilterColumn,
        drop_signbits: Payloads.DropNulls,
        filter_signbits_column: Payloads.FilterColumn,
        drop_negatives: Payloads.DropNulls,
        filter_negatives_column: Payloads.FilterColumn,
        drop_finites: Payloads.DropNulls,
        filter_finites_column: Payloads.FilterColumn,
        drop_normals: Payloads.DropNulls,
        filter_normals_column: Payloads.FilterColumn,
        drop_subnormals: Payloads.DropNulls,
        filter_subnormals_column: Payloads.FilterColumn,
        drop_non_finites: Payloads.DropNulls,
        filter_non_finites_column: Payloads.FilterColumn,
        with_column_abs: Payloads.WithColumnUnary,
        with_column_neg: Payloads.WithColumnUnary,
        with_column_square: Payloads.WithColumnUnary,
        with_column_reciprocal: Payloads.WithColumnUnary,
        with_column_sign: Payloads.WithColumnUnary,
        with_column_sqrt: Payloads.WithColumnUnary,
        with_column_rsqrt: Payloads.WithColumnUnary,
        with_column_cbrt: Payloads.WithColumnUnary,
        with_column_floor: Payloads.WithColumnUnary,
        with_column_ceil: Payloads.WithColumnUnary,
        with_column_round: Payloads.WithColumnUnary,
        with_column_trunc: Payloads.WithColumnUnary,
        with_column_deg2rad: Payloads.WithColumnUnary,
        with_column_rad2deg: Payloads.WithColumnUnary,
        with_column_expit: Payloads.WithColumnUnary,
        with_column_logit: Payloads.WithColumnUnary,
        with_column_softplus: Payloads.WithColumnUnary,
        with_column_logsigmoid: Payloads.WithColumnUnary,
        with_column_relu: Payloads.WithColumnUnary,
        with_column_leaky_relu: Payloads.WithColumnParamUnary,
        with_column_relu6: Payloads.WithColumnUnary,
        with_column_pow_scalar: Payloads.WithColumnParamUnary,
        with_column_floor_div_scalar: Payloads.WithColumnParamUnary,
        with_column_mod_scalar: Payloads.WithColumnParamUnary,
        with_column_remainder_scalar: Payloads.WithColumnParamUnary,
        with_column_log_add_exp_scalar: Payloads.WithColumnParamUnary,
        with_column_log_add_exp2_scalar: Payloads.WithColumnParamUnary,
        with_column_xlogy_scalar: Payloads.WithColumnParamUnary,
        with_column_fmax_scalar: Payloads.WithColumnParamUnary,
        with_column_fmin_scalar: Payloads.WithColumnParamUnary,
        with_column_hypot_scalar: Payloads.WithColumnParamUnary,
        with_column_atan2_scalar: Payloads.WithColumnParamUnary,
        with_column_next_after_scalar: Payloads.WithColumnParamUnary,
        with_column_copysign_scalar: Payloads.WithColumnParamUnary,
        with_column_heaviside_scalar: Payloads.WithColumnParamUnary,
        with_column_ldexp_scalar: Payloads.WithColumnLdexpScalar,
        with_column_threshold: Payloads.WithColumnParamUnary2,
        with_column_hardtanh: Payloads.WithColumnParamUnary2,
        with_column_between: Payloads.WithColumnBetween,
        with_column_maximum_scalar: Payloads.WithColumnParamUnary,
        with_column_minimum_scalar: Payloads.WithColumnParamUnary,
        with_column_clip_min: Payloads.WithColumnParamUnary,
        with_column_clip_max: Payloads.WithColumnParamUnary,
        with_column_hardshrink: Payloads.WithColumnParamUnary,
        with_column_softshrink: Payloads.WithColumnParamUnary,
        with_column_tanhshrink: Payloads.WithColumnUnary,
        with_column_elu: Payloads.WithColumnParamUnary,
        with_column_celu: Payloads.WithColumnParamUnary,
        with_column_softsign: Payloads.WithColumnUnary,
        with_column_hardsigmoid: Payloads.WithColumnUnary,
        with_column_hardswish: Payloads.WithColumnUnary,
        with_column_silu: Payloads.WithColumnUnary,
        with_column_swish: Payloads.WithColumnUnary,
        with_column_mish: Payloads.WithColumnUnary,
        with_column_gelu: Payloads.WithColumnUnary,
        with_column_selu: Payloads.WithColumnUnary,
        with_column_exp: Payloads.WithColumnUnary,
        with_column_exp2: Payloads.WithColumnUnary,
        with_column_expm1: Payloads.WithColumnUnary,
        with_column_sin: Payloads.WithColumnUnary,
        with_column_cos: Payloads.WithColumnUnary,
        with_column_tan: Payloads.WithColumnUnary,
        with_column_asin: Payloads.WithColumnUnary,
        with_column_acos: Payloads.WithColumnUnary,
        with_column_atan: Payloads.WithColumnUnary,
        with_column_sinh: Payloads.WithColumnUnary,
        with_column_cosh: Payloads.WithColumnUnary,
        with_column_tanh: Payloads.WithColumnUnary,
        with_column_asinh: Payloads.WithColumnUnary,
        with_column_acosh: Payloads.WithColumnUnary,
        with_column_atanh: Payloads.WithColumnUnary,
        with_column_log: Payloads.WithColumnUnary,
        with_column_log1p: Payloads.WithColumnUnary,
        with_column_lgamma: Payloads.WithColumnUnary,
        with_column_sinc: Payloads.WithColumnUnary,
        with_column_log2: Payloads.WithColumnUnary,
        with_column_log10: Payloads.WithColumnUnary,
        with_column_binary: Payloads.WithColumnBinary,
        with_column_scalar: Payloads.WithColumnScalar,
        with_column_lerp_scalar: Payloads.WithColumnBinaryParam,
        with_column_addcmul_scalar: Payloads.WithColumnTernaryParam,
        with_column_addcdiv_scalar: Payloads.WithColumnTernaryParam,
        with_column_clip_array: Payloads.WithColumnTernary,
        with_column_where: Payloads.WithColumnTernary,
        with_column_where_scalar: Payloads.WithColumnWhereScalar,
        with_column_isin: Payloads.WithColumnIsIn,
        with_column_isin_values: Payloads.WithColumnIsInValues,
        with_column_masked_put_scalar: Payloads.WithColumnWhereScalar,
        with_column_put_flat_scalar: Payloads.WithColumnPutFlatScalar,
        with_column_put_flat: Payloads.WithColumnPutFlat,
        with_column_put_flat_scalar_mode: Payloads.WithColumnPutFlatScalarMode,
        with_column_put_flat_scalar_signed: Payloads.WithColumnPutFlatScalarSigned,
        with_column_isclose_scalar: Payloads.WithColumnIsCloseScalar,
        with_column_logical: Payloads.WithColumnLogical,
        with_column_logical_scalar: Payloads.WithColumnLogicalScalar,
        with_column_literal: Payloads.WithColumnLiteral,
        with_column_literal_at: Payloads.WithColumnLiteralAt,
        with_column_literal_before: Payloads.WithColumnLiteralRelative,
        with_column_literal_after: Payloads.WithColumnLiteralRelative,
        cast_column: Payloads.CastColumn,
        fill_null_column: Payloads.FillNullColumn,
        fill_nan_column: Payloads.FillNullColumn,
        fill_inf_column: Payloads.FillNullColumn,
        fill_positive_inf_column: Payloads.FillNullColumn,
        fill_negative_inf_column: Payloads.FillNullColumn,
        fill_zero_column: Payloads.FillNullColumn,
        fill_positive_zero_column: Payloads.FillNullColumn,
        fill_negative_zero_column: Payloads.FillNullColumn,
        fill_non_zero_column: Payloads.FillNullColumn,
        fill_positive_column: Payloads.FillNullColumn,
        fill_signbit_column: Payloads.FillNullColumn,
        fill_negative_column: Payloads.FillNullColumn,
        fill_finite_column: Payloads.FillNullColumn,
        fill_normal_column: Payloads.FillNullColumn,
        fill_subnormal_column: Payloads.FillNullColumn,
        fill_non_finite_column: Payloads.FillNullColumn,
        fill_null_forward_column: Payloads.FilterColumn,
        fill_null_backward_column: Payloads.FilterColumn,
        null_if_column: Payloads.FillNullColumn,
        null_if_values_column: Payloads.NullIfValues,
        null_if_nan_column: Payloads.FilterColumn,
        null_if_inf_column: Payloads.FilterColumn,
        null_if_positive_inf_column: Payloads.FilterColumn,
        null_if_negative_inf_column: Payloads.FilterColumn,
        null_if_zero_column: Payloads.FilterColumn,
        null_if_positive_zero_column: Payloads.FilterColumn,
        null_if_negative_zero_column: Payloads.FilterColumn,
        null_if_non_zero_column: Payloads.FilterColumn,
        null_if_positive_column: Payloads.FilterColumn,
        null_if_signbit_column: Payloads.FilterColumn,
        null_if_negative_column: Payloads.FilterColumn,
        null_if_finite_column: Payloads.FilterColumn,
        null_if_normal_column: Payloads.FilterColumn,
        null_if_subnormal_column: Payloads.FilterColumn,
        null_if_non_finite_column: Payloads.FilterColumn,
        coalesce_columns: Payloads.CoalesceColumns,
        coalesce_columns_many: Payloads.RowValidityCount,
        is_null_column: Payloads.NullPredicateColumn,
        is_valid_column: Payloads.NullPredicateColumn,
        is_nan_column: Payloads.NullPredicateColumn,
        is_zero_column: Payloads.NullPredicateColumn,
        is_positive_zero_column: Payloads.NullPredicateColumn,
        is_negative_zero_column: Payloads.NullPredicateColumn,
        is_non_zero_column: Payloads.NullPredicateColumn,
        is_positive_column: Payloads.NullPredicateColumn,
        is_signbit_column: Payloads.NullPredicateColumn,
        is_negative_column: Payloads.NullPredicateColumn,
        is_finite_column: Payloads.NullPredicateColumn,
        is_normal_column: Payloads.NullPredicateColumn,
        is_subnormal_column: Payloads.NullPredicateColumn,
        is_non_finite_column: Payloads.NullPredicateColumn,
        is_inf_column: Payloads.NullPredicateColumn,
        is_positive_inf_column: Payloads.NullPredicateColumn,
        is_negative_inf_column: Payloads.NullPredicateColumn,
        row_null_count: Payloads.RowValidityCount,
        row_valid_count: Payloads.RowValidityCount,
        row_cumulative_null_count: Payloads.RowColumnOutputs,
        row_cumulative_valid_count: Payloads.RowColumnOutputs,
        row_cumulative_null_ratio: Payloads.RowColumnOutputs,
        row_cumulative_valid_ratio: Payloads.RowColumnOutputs,
        row_null_ratio: Payloads.RowValidityCount,
        row_valid_ratio: Payloads.RowValidityCount,
        row_first_valid_index: Payloads.RowValidityCount,
        row_last_valid_index: Payloads.RowValidityCount,
        row_first_null_index: Payloads.RowValidityCount,
        row_last_null_index: Payloads.RowValidityCount,
        row_cumulative_first_valid_index: Payloads.RowColumnOutputs,
        row_cumulative_last_valid_index: Payloads.RowColumnOutputs,
        row_cumulative_first_null_index: Payloads.RowColumnOutputs,
        row_cumulative_last_null_index: Payloads.RowColumnOutputs,
        row_pair_count: Payloads.RowWeightedMean,
        row_weighted_mean: Payloads.RowWeightedMean,
        row_weighted_variance: Payloads.RowWeightedDispersion,
        row_weighted_stddev: Payloads.RowWeightedDispersion,
        row_weighted_covariance: Payloads.RowWeightedPair,
        row_weighted_correlation: Payloads.RowWeightedPair,
        row_weighted_beta: Payloads.RowWeightedPair,
        row_weighted_quantile: Payloads.RowWeightedQuantile,
        row_weighted_median: Payloads.RowWeightedMean,
        row_weighted_iqr: Payloads.RowWeightedMean,
        row_weighted_mad: Payloads.RowWeightedMean,
        row_weighted_mode: Payloads.RowWeightedMean,
        row_weighted_mode_weight: Payloads.RowWeightedMean,
        row_weighted_mode_ratio: Payloads.RowWeightedMean,
        row_weighted_mode_margin: Payloads.RowWeightedMean,
        row_weighted_mode_margin_ratio: Payloads.RowWeightedMean,
        row_weighted_entropy: Payloads.RowWeightedMean,
        row_weighted_gini_impurity: Payloads.RowWeightedMean,
        row_weighted_perplexity: Payloads.RowWeightedMean,
        row_weighted_inverse_simpson: Payloads.RowWeightedMean,
        row_weighted_simpson_concentration: Payloads.RowWeightedMean,
        row_weighted_evenness: Payloads.RowWeightedMean,
        row_dot: Payloads.RowWeightedMean,
        row_cosine_similarity: Payloads.RowWeightedMean,
        row_squared_euclidean_distance: Payloads.RowWeightedMean,
        row_euclidean_distance: Payloads.RowWeightedMean,
        row_manhattan_distance: Payloads.RowWeightedMean,
        row_chebyshev_distance: Payloads.RowWeightedMean,
        row_canberra_distance: Payloads.RowWeightedMean,
        row_bray_curtis_distance: Payloads.RowWeightedMean,
        row_mean_error: Payloads.RowWeightedMean,
        row_mae: Payloads.RowWeightedMean,
        row_mse: Payloads.RowWeightedMean,
        row_rmse: Payloads.RowWeightedMean,
        row_mape: Payloads.RowWeightedMean,
        row_smape: Payloads.RowWeightedMean,
        row_covariance: Payloads.RowWeightedMean,
        row_correlation: Payloads.RowWeightedMean,
        row_beta: Payloads.RowWeightedMean,
        row_argmin: Payloads.RowValidityCount,
        row_argmax: Payloads.RowValidityCount,
        row_cumulative_argmin: Payloads.RowColumnOutputs,
        row_cumulative_argmax: Payloads.RowColumnOutputs,
        row_quantile: Payloads.RowQuantile,
        row_quantile_range: Payloads.RowQuantileRange,
        row_trimmed_mean: Payloads.RowTrimmedMean,
        row_winsorized_mean: Payloads.RowWinsorizedMean,
        row_median: Payloads.RowValidityCount,
        row_iqr: Payloads.RowValidityCount,
        row_interdecile_range: Payloads.RowValidityCount,
        row_midhinge: Payloads.RowValidityCount,
        row_trimean: Payloads.RowValidityCount,
        row_bowley_skewness: Payloads.RowValidityCount,
        row_quartile_coeff_dispersion: Payloads.RowValidityCount,
        row_kelley_skewness: Payloads.RowValidityCount,
        row_mad: Payloads.RowValidityCount,
        row_mode: Payloads.RowValidityCount,
        row_cumulative_mode: Payloads.RowColumnOutputs,
        row_cumulative_mode_count: Payloads.RowColumnOutputs,
        row_cumulative_mode_ratio: Payloads.RowColumnOutputs,
        row_cumulative_mode_margin: Payloads.RowColumnOutputs,
        row_cumulative_mode_margin_ratio: Payloads.RowColumnOutputs,
        row_entropy: Payloads.RowValidityCount,
        row_gini_impurity: Payloads.RowValidityCount,
        row_perplexity: Payloads.RowValidityCount,
        row_inverse_simpson: Payloads.RowValidityCount,
        row_simpson_concentration: Payloads.RowValidityCount,
        row_evenness: Payloads.RowValidityCount,
        row_mode_count: Payloads.RowValidityCount,
        row_mode_ratio: Payloads.RowValidityCount,
        row_mode_margin: Payloads.RowValidityCount,
        row_mode_margin_ratio: Payloads.RowValidityCount,
        row_count_distinct: Payloads.RowValidityCount,
        row_n_unique: Payloads.RowValidityCount,
        row_is_duplicated: Payloads.RowValidityCount,
        row_is_unique: Payloads.RowValidityCount,
        row_cumulative_distinct_count: Payloads.RowColumnOutputs,
        row_cumulative_n_unique: Payloads.RowColumnOutputs,
        row_sum: Payloads.RowValidityCount,
        row_mean: Payloads.RowValidityCount,
        row_logsumexp: Payloads.RowValidityCount,
        row_logmeanexp: Payloads.RowValidityCount,
        row_centered: Payloads.RowColumnOutputs,
        row_zscore: Payloads.RowColumnOutputs,
        row_robust_zscore: Payloads.RowColumnOutputs,
        row_average_rank: Payloads.RowColumnOutputs,
        row_ordinal_rank: Payloads.RowColumnOutputs,
        row_dense_rank: Payloads.RowColumnOutputs,
        row_competition_rank: Payloads.RowColumnOutputs,
        row_percent_rank: Payloads.RowColumnOutputs,
        row_cume_dist: Payloads.RowColumnOutputs,
        row_cumulative_sum: Payloads.RowColumnOutputs,
        row_cumulative_mean: Payloads.RowColumnOutputs,
        row_cumulative_logsumexp: Payloads.RowColumnOutputs,
        row_cumulative_logmeanexp: Payloads.RowColumnOutputs,
        row_cumulative_geometric_mean: Payloads.RowColumnOutputs,
        row_cumulative_harmonic_mean: Payloads.RowColumnOutputs,
        row_cumulative_variance: Payloads.RowColumnOutputsDispersion,
        row_cumulative_stddev: Payloads.RowColumnOutputsDispersion,
        row_cumulative_sem: Payloads.RowColumnOutputsDispersion,
        row_cumulative_cv: Payloads.RowColumnOutputsDispersion,
        row_cumulative_fano: Payloads.RowColumnOutputsDispersion,
        row_cumulative_skewness: Payloads.RowColumnOutputs,
        row_cumulative_kurtosis: Payloads.RowColumnOutputs,
        row_cumulative_rms: Payloads.RowColumnOutputs,
        row_cumulative_mean_abs: Payloads.RowColumnOutputs,
        row_cumulative_mean_square: Payloads.RowColumnOutputs,
        row_cumulative_max_abs: Payloads.RowColumnOutputs,
        row_cumulative_min_abs: Payloads.RowColumnOutputs,
        row_cumulative_l1_norm: Payloads.RowColumnOutputs,
        row_cumulative_l2_norm: Payloads.RowColumnOutputs,
        row_cumulative_product: Payloads.RowColumnOutputs,
        row_cumulative_max: Payloads.RowColumnOutputs,
        row_cumulative_min: Payloads.RowColumnOutputs,
        row_cumulative_range: Payloads.RowColumnOutputs,
        row_iqr_outlier: Payloads.RowColumnOutputs,
        row_tukey_winsorize: Payloads.RowColumnOutputs,
        row_max_indicator: Payloads.RowColumnOutputs,
        row_min_indicator: Payloads.RowColumnOutputs,
        row_minmax_scale: Payloads.RowColumnOutputs,
        row_l2_normalize: Payloads.RowColumnOutputs,
        row_l1_normalize: Payloads.RowColumnOutputs,
        row_sum_normalize: Payloads.RowColumnOutputs,
        row_mean_normalize: Payloads.RowColumnOutputs,
        row_max_abs_normalize: Payloads.RowColumnOutputs,
        row_softmax: Payloads.RowColumnOutputs,
        row_log_softmax: Payloads.RowColumnOutputs,
        row_softmin: Payloads.RowColumnOutputs,
        row_log_softmin: Payloads.RowColumnOutputs,
        row_softmax_entropy: Payloads.RowValidityCount,
        row_softmax_perplexity: Payloads.RowValidityCount,
        row_softmax_confidence: Payloads.RowValidityCount,
        row_softmax_margin: Payloads.RowValidityCount,
        row_softmax_evenness: Payloads.RowValidityCount,
        row_softmax_concentration: Payloads.RowValidityCount,
        row_softmax_normalized_hhi: Payloads.RowValidityCount,
        row_softmax_gini_impurity: Payloads.RowValidityCount,
        row_softmax_inverse_simpson: Payloads.RowValidityCount,
        row_softmax_simpson_evenness: Payloads.RowValidityCount,
        row_logit_margin: Payloads.RowValidityCount,
        row_geometric_mean: Payloads.RowValidityCount,
        row_magnitude_geometric_mean: Payloads.RowValidityCount,
        row_harmonic_mean: Payloads.RowValidityCount,
        row_prod: Payloads.RowValidityCount,
        row_min: Payloads.RowValidityCount,
        row_max: Payloads.RowValidityCount,
        row_ptp: Payloads.RowValidityCount,
        row_magnitude_ptp: Payloads.RowValidityCount,
        row_midrange: Payloads.RowValidityCount,
        row_magnitude_midrange: Payloads.RowValidityCount,
        row_range_coeff: Payloads.RowValidityCount,
        row_magnitude_range_coeff: Payloads.RowValidityCount,
        row_mean_abs: Payloads.RowValidityCount,
        row_hhi: Payloads.RowValidityCount,
        row_magnitude_normalized_hhi: Payloads.RowValidityCount,
        row_magnitude_sparsity: Payloads.RowValidityCount,
        row_magnitude_inverse_simpson: Payloads.RowValidityCount,
        row_magnitude_simpson_evenness: Payloads.RowValidityCount,
        row_magnitude_dominance: Payloads.RowValidityCount,
        row_magnitude_dominance_margin: Payloads.RowValidityCount,
        row_magnitude_entropy: Payloads.RowValidityCount,
        row_magnitude_perplexity: Payloads.RowValidityCount,
        row_magnitude_evenness: Payloads.RowValidityCount,
        row_mean_abs_dev: Payloads.RowValidityCount,
        row_gini_mean_diff: Payloads.RowValidityCount,
        row_gini_coefficient: Payloads.RowValidityCount,
        row_mean_abs_dev_ratio: Payloads.RowValidityCount,
        row_rms: Payloads.RowValidityCount,
        row_l1_norm: Payloads.RowValidityCount,
        row_l2_norm: Payloads.RowValidityCount,
        row_variance: Payloads.RowNumericDispersion,
        row_magnitude_variance: Payloads.RowNumericDispersion,
        row_stddev: Payloads.RowNumericDispersion,
        row_magnitude_stddev: Payloads.RowNumericDispersion,
        row_sem: Payloads.RowNumericDispersion,
        row_magnitude_sem: Payloads.RowNumericDispersion,
        row_cv: Payloads.RowNumericDispersion,
        row_magnitude_cv: Payloads.RowNumericDispersion,
        row_magnitude_fano: Payloads.RowNumericDispersion,
        row_fano: Payloads.RowNumericDispersion,
        row_skewness: Payloads.RowValidityCount,
        row_magnitude_skewness: Payloads.RowValidityCount,
        row_kurtosis: Payloads.RowValidityCount,
        row_magnitude_kurtosis: Payloads.RowValidityCount,
        row_any_null: Payloads.RowValidityCount,
        row_all_null: Payloads.RowValidityCount,
        row_any_valid: Payloads.RowValidityCount,
        row_all_valid: Payloads.RowValidityCount,
        row_true_count: Payloads.RowValidityCount,
        row_false_count: Payloads.RowValidityCount,
        row_cumulative_true_count: Payloads.RowColumnOutputs,
        row_cumulative_false_count: Payloads.RowColumnOutputs,
        row_cumulative_any_null: Payloads.RowColumnOutputs,
        row_cumulative_all_null: Payloads.RowColumnOutputs,
        row_cumulative_any_valid: Payloads.RowColumnOutputs,
        row_cumulative_all_valid: Payloads.RowColumnOutputs,
        row_cumulative_true_ratio: Payloads.RowColumnOutputs,
        row_cumulative_false_ratio: Payloads.RowColumnOutputs,
        row_any_true: Payloads.RowValidityCount,
        row_all_true: Payloads.RowValidityCount,
        row_any_false: Payloads.RowValidityCount,
        row_all_false: Payloads.RowValidityCount,
        row_cumulative_any_true: Payloads.RowColumnOutputs,
        row_cumulative_all_true: Payloads.RowColumnOutputs,
        row_cumulative_any_false: Payloads.RowColumnOutputs,
        row_cumulative_all_false: Payloads.RowColumnOutputs,
        row_first_true_index: Payloads.RowValidityCount,
        row_last_true_index: Payloads.RowValidityCount,
        row_first_false_index: Payloads.RowValidityCount,
        row_last_false_index: Payloads.RowValidityCount,
        row_cumulative_first_true_index: Payloads.RowColumnOutputs,
        row_cumulative_last_true_index: Payloads.RowColumnOutputs,
        row_cumulative_first_false_index: Payloads.RowColumnOutputs,
        row_cumulative_last_false_index: Payloads.RowColumnOutputs,
        row_true_ratio: Payloads.RowValidityCount,
        row_false_ratio: Payloads.RowValidityCount,
        row_any_zero: Payloads.RowValidityCount,
        row_all_zero: Payloads.RowValidityCount,
        row_any_non_zero: Payloads.RowValidityCount,
        row_all_non_zero: Payloads.RowValidityCount,
        row_any_positive_zero: Payloads.RowValidityCount,
        row_all_positive_zero: Payloads.RowValidityCount,
        row_any_negative_zero: Payloads.RowValidityCount,
        row_all_negative_zero: Payloads.RowValidityCount,
        row_any_positive: Payloads.RowValidityCount,
        row_all_positive: Payloads.RowValidityCount,
        row_any_signbit: Payloads.RowValidityCount,
        row_all_signbit: Payloads.RowValidityCount,
        row_any_negative: Payloads.RowValidityCount,
        row_all_negative: Payloads.RowValidityCount,
        row_any_nan: Payloads.RowValidityCount,
        row_all_nan: Payloads.RowValidityCount,
        row_any_inf: Payloads.RowValidityCount,
        row_all_inf: Payloads.RowValidityCount,
        row_any_positive_inf: Payloads.RowValidityCount,
        row_all_positive_inf: Payloads.RowValidityCount,
        row_any_negative_inf: Payloads.RowValidityCount,
        row_all_negative_inf: Payloads.RowValidityCount,
        row_any_finite: Payloads.RowValidityCount,
        row_all_finite: Payloads.RowValidityCount,
        row_any_normal: Payloads.RowValidityCount,
        row_all_normal: Payloads.RowValidityCount,
        row_any_subnormal: Payloads.RowValidityCount,
        row_all_subnormal: Payloads.RowValidityCount,
        row_any_non_finite: Payloads.RowValidityCount,
        row_all_non_finite: Payloads.RowValidityCount,
        row_nan_count: Payloads.RowValidityCount,
        row_nan_ratio: Payloads.RowValidityCount,
        row_inf_count: Payloads.RowValidityCount,
        row_inf_ratio: Payloads.RowValidityCount,
        row_positive_inf_count: Payloads.RowValidityCount,
        row_negative_inf_count: Payloads.RowValidityCount,
        row_positive_inf_ratio: Payloads.RowValidityCount,
        row_negative_inf_ratio: Payloads.RowValidityCount,
        row_zero_count: Payloads.RowValidityCount,
        row_zero_ratio: Payloads.RowValidityCount,
        row_positive_zero_count: Payloads.RowValidityCount,
        row_negative_zero_count: Payloads.RowValidityCount,
        row_positive_zero_ratio: Payloads.RowValidityCount,
        row_negative_zero_ratio: Payloads.RowValidityCount,
        row_non_zero_count: Payloads.RowValidityCount,
        row_non_zero_ratio: Payloads.RowValidityCount,
        row_first_nan_index: Payloads.RowValidityCount,
        row_last_nan_index: Payloads.RowValidityCount,
        row_first_inf_index: Payloads.RowValidityCount,
        row_last_inf_index: Payloads.RowValidityCount,
        row_first_positive_inf_index: Payloads.RowValidityCount,
        row_last_positive_inf_index: Payloads.RowValidityCount,
        row_first_negative_inf_index: Payloads.RowValidityCount,
        row_last_negative_inf_index: Payloads.RowValidityCount,
        row_first_finite_index: Payloads.RowValidityCount,
        row_last_finite_index: Payloads.RowValidityCount,
        row_first_normal_index: Payloads.RowValidityCount,
        row_last_normal_index: Payloads.RowValidityCount,
        row_first_subnormal_index: Payloads.RowValidityCount,
        row_last_subnormal_index: Payloads.RowValidityCount,
        row_first_non_finite_index: Payloads.RowValidityCount,
        row_last_non_finite_index: Payloads.RowValidityCount,
        row_first_positive_zero_index: Payloads.RowValidityCount,
        row_last_positive_zero_index: Payloads.RowValidityCount,
        row_first_negative_zero_index: Payloads.RowValidityCount,
        row_last_negative_zero_index: Payloads.RowValidityCount,
        row_first_signbit_index: Payloads.RowValidityCount,
        row_last_signbit_index: Payloads.RowValidityCount,
        row_first_zero_index: Payloads.RowValidityCount,
        row_last_zero_index: Payloads.RowValidityCount,
        row_first_non_zero_index: Payloads.RowValidityCount,
        row_last_non_zero_index: Payloads.RowValidityCount,
        row_first_positive_index: Payloads.RowValidityCount,
        row_last_positive_index: Payloads.RowValidityCount,
        row_first_negative_index: Payloads.RowValidityCount,
        row_last_negative_index: Payloads.RowValidityCount,
        row_positive_count: Payloads.RowValidityCount,
        row_positive_ratio: Payloads.RowValidityCount,
        row_signbit_count: Payloads.RowValidityCount,
        row_signbit_ratio: Payloads.RowValidityCount,
        row_negative_count: Payloads.RowValidityCount,
        row_negative_ratio: Payloads.RowValidityCount,
        row_cumulative_positive_zero_count: Payloads.RowColumnOutputs,
        row_cumulative_negative_zero_count: Payloads.RowColumnOutputs,
        row_cumulative_signbit_count: Payloads.RowColumnOutputs,
        row_cumulative_positive_zero_ratio: Payloads.RowColumnOutputs,
        row_cumulative_negative_zero_ratio: Payloads.RowColumnOutputs,
        row_cumulative_signbit_ratio: Payloads.RowColumnOutputs,
        row_cumulative_nan_count: Payloads.RowColumnOutputs,
        row_cumulative_inf_count: Payloads.RowColumnOutputs,
        row_cumulative_positive_inf_count: Payloads.RowColumnOutputs,
        row_cumulative_negative_inf_count: Payloads.RowColumnOutputs,
        row_cumulative_finite_count: Payloads.RowColumnOutputs,
        row_cumulative_normal_count: Payloads.RowColumnOutputs,
        row_cumulative_subnormal_count: Payloads.RowColumnOutputs,
        row_cumulative_non_finite_count: Payloads.RowColumnOutputs,
        row_cumulative_nan_ratio: Payloads.RowColumnOutputs,
        row_cumulative_inf_ratio: Payloads.RowColumnOutputs,
        row_cumulative_positive_inf_ratio: Payloads.RowColumnOutputs,
        row_cumulative_negative_inf_ratio: Payloads.RowColumnOutputs,
        row_cumulative_finite_ratio: Payloads.RowColumnOutputs,
        row_cumulative_normal_ratio: Payloads.RowColumnOutputs,
        row_cumulative_subnormal_ratio: Payloads.RowColumnOutputs,
        row_cumulative_non_finite_ratio: Payloads.RowColumnOutputs,
        row_cumulative_any_zero: Payloads.RowColumnOutputs,
        row_cumulative_all_zero: Payloads.RowColumnOutputs,
        row_cumulative_any_non_zero: Payloads.RowColumnOutputs,
        row_cumulative_all_non_zero: Payloads.RowColumnOutputs,
        row_cumulative_any_positive_zero: Payloads.RowColumnOutputs,
        row_cumulative_all_positive_zero: Payloads.RowColumnOutputs,
        row_cumulative_any_negative_zero: Payloads.RowColumnOutputs,
        row_cumulative_all_negative_zero: Payloads.RowColumnOutputs,
        row_cumulative_any_positive: Payloads.RowColumnOutputs,
        row_cumulative_all_positive: Payloads.RowColumnOutputs,
        row_cumulative_any_signbit: Payloads.RowColumnOutputs,
        row_cumulative_all_signbit: Payloads.RowColumnOutputs,
        row_cumulative_any_negative: Payloads.RowColumnOutputs,
        row_cumulative_all_negative: Payloads.RowColumnOutputs,
        row_cumulative_any_nan: Payloads.RowColumnOutputs,
        row_cumulative_all_nan: Payloads.RowColumnOutputs,
        row_cumulative_any_inf: Payloads.RowColumnOutputs,
        row_cumulative_all_inf: Payloads.RowColumnOutputs,
        row_cumulative_any_positive_inf: Payloads.RowColumnOutputs,
        row_cumulative_all_positive_inf: Payloads.RowColumnOutputs,
        row_cumulative_any_negative_inf: Payloads.RowColumnOutputs,
        row_cumulative_all_negative_inf: Payloads.RowColumnOutputs,
        row_cumulative_any_finite: Payloads.RowColumnOutputs,
        row_cumulative_all_finite: Payloads.RowColumnOutputs,
        row_cumulative_any_normal: Payloads.RowColumnOutputs,
        row_cumulative_all_normal: Payloads.RowColumnOutputs,
        row_cumulative_any_subnormal: Payloads.RowColumnOutputs,
        row_cumulative_all_subnormal: Payloads.RowColumnOutputs,
        row_cumulative_any_non_finite: Payloads.RowColumnOutputs,
        row_cumulative_all_non_finite: Payloads.RowColumnOutputs,
        row_cumulative_first_nan_index: Payloads.RowColumnOutputs,
        row_cumulative_last_nan_index: Payloads.RowColumnOutputs,
        row_cumulative_first_inf_index: Payloads.RowColumnOutputs,
        row_cumulative_last_inf_index: Payloads.RowColumnOutputs,
        row_cumulative_first_positive_inf_index: Payloads.RowColumnOutputs,
        row_cumulative_last_positive_inf_index: Payloads.RowColumnOutputs,
        row_cumulative_first_negative_inf_index: Payloads.RowColumnOutputs,
        row_cumulative_last_negative_inf_index: Payloads.RowColumnOutputs,
        row_cumulative_first_finite_index: Payloads.RowColumnOutputs,
        row_cumulative_last_finite_index: Payloads.RowColumnOutputs,
        row_cumulative_first_normal_index: Payloads.RowColumnOutputs,
        row_cumulative_last_normal_index: Payloads.RowColumnOutputs,
        row_cumulative_first_subnormal_index: Payloads.RowColumnOutputs,
        row_cumulative_last_subnormal_index: Payloads.RowColumnOutputs,
        row_cumulative_first_non_finite_index: Payloads.RowColumnOutputs,
        row_cumulative_last_non_finite_index: Payloads.RowColumnOutputs,
        row_cumulative_zero_count: Payloads.RowColumnOutputs,
        row_cumulative_first_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_last_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_first_positive_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_last_positive_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_first_negative_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_last_negative_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_non_zero_count: Payloads.RowColumnOutputs,
        row_cumulative_first_non_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_last_non_zero_index: Payloads.RowColumnOutputs,
        row_cumulative_first_positive_index: Payloads.RowColumnOutputs,
        row_cumulative_last_positive_index: Payloads.RowColumnOutputs,
        row_cumulative_first_signbit_index: Payloads.RowColumnOutputs,
        row_cumulative_last_signbit_index: Payloads.RowColumnOutputs,
        row_cumulative_first_negative_index: Payloads.RowColumnOutputs,
        row_cumulative_last_negative_index: Payloads.RowColumnOutputs,
        row_cumulative_positive_count: Payloads.RowColumnOutputs,
        row_cumulative_negative_count: Payloads.RowColumnOutputs,
        row_cumulative_zero_ratio: Payloads.RowColumnOutputs,
        row_cumulative_non_zero_ratio: Payloads.RowColumnOutputs,
        row_cumulative_positive_ratio: Payloads.RowColumnOutputs,
        row_cumulative_negative_ratio: Payloads.RowColumnOutputs,
        row_finite_count: Payloads.RowValidityCount,
        row_finite_ratio: Payloads.RowValidityCount,
        row_normal_count: Payloads.RowValidityCount,
        row_normal_ratio: Payloads.RowValidityCount,
        row_subnormal_count: Payloads.RowValidityCount,
        row_subnormal_ratio: Payloads.RowValidityCount,
        row_non_finite_count: Payloads.RowValidityCount,
        row_non_finite_ratio: Payloads.RowValidityCount,
        with_column_compare: Payloads.WithColumnCompare,
        with_column_compare_scalar: Payloads.WithColumnCompareScalar,
        filter_mask: Payloads.FilterMask,
        filter_column: Payloads.FilterColumn,
        drop_rows_by_mask_column: Payloads.FilterColumn,
        where_indices_column: Payloads.NullPredicateColumn,
        filter_scalar: Payloads.FilterScalar,
        group_row_number: Payloads.RowValidityCount,
        group_size: Payloads.RowValidityCount,
        group_by_count: Payloads.GroupByCount,
        group_by_count_on: Payloads.GroupByCountOn,
        group_by_rows: Payloads.GroupByRows,
        group_by_rows_on: Payloads.GroupByRowsOn,
        group_by_sorted_rows: Payloads.GroupBySortedRows,
        group_by_sorted_rows_on: Payloads.GroupBySortedRowsOn,
        group_by_sorted_rows_columns: Payloads.GroupBySortedRowsColumns,
        group_by_sorted_rows_columns_on: Payloads.GroupBySortedRowsColumnsOn,
        group_by_value: Payloads.GroupByValue,
        group_by_value_on: Payloads.GroupByValueOn,
        group_by_weighted: Payloads.GroupByWeighted,
        group_by_weighted_on: Payloads.GroupByWeightedOn,
        group_by_pair: Payloads.GroupByPair,
        group_by_pair_on: Payloads.GroupByPairOn,
        group_by_weighted_pair: Payloads.GroupByWeightedPair,
        group_by_weighted_pair_on: Payloads.GroupByWeightedPairOn,
        group_by_stats: Payloads.GroupByOutput,
        group_by_stats_on: Payloads.GroupByOutputOn,
        group_by_profile: Payloads.GroupByOutput,
        group_by_profile_on: Payloads.GroupByOutputOn,
        join_on: Payloads.JoinOn,
        asof_join: Payloads.AsofJoin,
        concat_rows: Payloads.ConcatRows,
        concat_columns: Payloads.ConcatRows,
        distinct_rows,
        distinct_rows_last,
        distinct_rows_none,
        distinct_on: Payloads.DistinctOn,
        distinct_on_last: Payloads.DistinctOn,
        distinct_on_none: Payloads.DistinctOn,
        sort_by: Payloads.SortBy,
        sort_by_columns: Payloads.SortByColumns,
        top_k: Payloads.TopK,
        top_k_columns: Payloads.TopKColumns,
        rank_profile_by: Payloads.RankProfileBy,
        rolling_profile: Payloads.RollingProfile,
        rolling_moment_profile: Payloads.RollingProfile,
        rolling_range_profile: Payloads.RollingProfile,
        rolling_normalize_profile: Payloads.RollingProfile,
        expanding_normalize_profile: Payloads.ExpandingProfile,
        rolling_quantile_profile: Payloads.RollingProfile,
        expanding_quantile_profile: Payloads.ExpandingProfile,
        rolling_bool_profile: Payloads.RollingProfile,
        rolling_drawdown_profile: Payloads.RollingProfile,
        rolling_robust_profile: Payloads.RollingRobustProfile,
        rolling_rank_profile: Payloads.RollingRankProfile,
        lag_profile: Payloads.LagProfile,
        lead_profile: Payloads.LagProfile,
        clip_profile: Payloads.ClipProfile,
        rolling_clip_profile: Payloads.RollingClipProfile,
        expanding_clip_profile: Payloads.ExpandingClipProfile,
        threshold_profile: Payloads.ThresholdProfile,
        rolling_threshold_profile: Payloads.RollingThresholdProfile,
        expanding_threshold_profile: Payloads.ExpandingThresholdProfile,
        expanding_profile: Payloads.ExpandingProfile,
        expanding_bool_profile: Payloads.ExpandingProfile,
        expanding_rank_profile: Payloads.ExpandingRankProfile,
        expanding_robust_profile: Payloads.ExpandingRobustProfile,
        expanding_moment_profile: Payloads.ExpandingProfile,
        standardize_profile: Payloads.StandardizeProfile,
        robust_profile: Payloads.RobustProfile,
        drawdown_profile: Payloads.DrawdownProfile,
        extrema_profile: Payloads.ExtremaProfile,
        trend_profile: Payloads.TrendProfile,
        rolling_trend_profile: Payloads.RollingTrendProfile,
        expanding_trend_profile: Payloads.ExpandingTrendProfile,
        change_point_profile: Payloads.ChangePointProfile,
        rolling_change_point_profile: Payloads.RollingChangePointProfile,
        expanding_change_point_profile: Payloads.ExpandingChangePointProfile,
        sign_profile: Payloads.TrendProfile,
        rolling_sign_profile: Payloads.RollingSignProfile,
        expanding_sign_profile: Payloads.ExpandingSignProfile,
        crossover_profile: Payloads.CrossoverProfile,
        rolling_crossover_profile: Payloads.RollingCrossoverProfile,
        expanding_crossover_profile: Payloads.ExpandingCrossoverProfile,
        bucket_profile: Payloads.BucketProfile,
        ema_profile: Payloads.EmaProfile,
        linear_fit_profile: Payloads.LinearFitProfile,
        error_profile: Payloads.PairOutput,
        rolling_error_profile: Payloads.RollingPairOutput,
        expanding_error_profile: Payloads.ExpandingPairOutput,
        classification_profile: Payloads.PairOutput,
        rolling_classification_profile: Payloads.RollingPairOutput,
        expanding_classification_profile: Payloads.ExpandingPairOutput,
        bool_transition_profile: Payloads.BoolTransitionProfile,
        rolling_bool_transition_profile: Payloads.RollingBoolTransitionProfile,
        expanding_bool_transition_profile: Payloads.ExpandingBoolTransitionProfile,
        rolling_correlation_profile: Payloads.RollingCorrelationProfile,
        expanding_correlation_profile: Payloads.ExpandingXYProfile,
        expanding_linear_fit_profile: Payloads.ExpandingXYProfile,
        rolling_linear_fit_profile: Payloads.RollingLinearFitProfile,
        validity_profile: Payloads.ValidityProfile,
        rolling_validity_profile: Payloads.RollingValidityProfile,
        expanding_validity_profile: Payloads.ExpandingValidityProfile,
        slice_rows: Payloads.RowSlice,
        slice_rows_signed: Payloads.RowSliceSigned,
        drop_rows: Payloads.RowTake,
        drop_rows_mode: Payloads.RowTakeMode,
        drop_rows_signed: Payloads.RowTakeSigned,
        drop_rows_signed_mode: Payloads.RowTakeSignedMode,
        drop_row_range: Payloads.RowSlice,
        drop_last_rows: Payloads.HeadTail,
        slice_rows_step: Payloads.RowSliceStep,
        slice_rows_signed_step: Payloads.RowSliceSignedStep,
        stride_rows: Payloads.RowStride,
        take_rows: Payloads.RowTake,
        take_rows_optional: Payloads.RowTakeOptional,
        take_rows_mode: Payloads.RowTakeMode,
        take_rows_signed: Payloads.RowTakeSigned,
        take_rows_signed_mode: Payloads.RowTakeSignedMode,
        take_rows_by_column: []const u8,
        take_rows_by_column_mode: Payloads.RowTakeByColumnMode,
        drop_rows_by_column: []const u8,
        drop_rows_by_column_mode: Payloads.RowTakeByColumnMode,
        repeat_rows: usize,
        tile_rows: usize,
        repeat_rows_by: []const u8,
        sample_rows: Payloads.RowSample,
        sample_rows_fraction: Payloads.RowSampleFraction,
        sample_rows_with_replacement: Payloads.RowSample,
        sample_rows_fraction_with_replacement: Payloads.RowSampleFraction,
        roll_rows: isize,
        shift_rows: isize,
        reverse_rows,
        head: Payloads.HeadTail,
        tail: Payloads.HeadTail,

        pub fn deinit(self: *Self, allocator: std.mem.Allocator) void {
            ownership_mod.deinit(Self, self, allocator);
        }

        pub fn clone(self: Self, allocator: std.mem.Allocator) DeviceDataError!Self {
            return ownership_mod.clone(Self, self, allocator);
        }
    };
}
