const std = @import("std");
const boltha = @import("boltha");
const vectra = @import("vectra");

const DataFrame = vectra.DataFrame;
const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;
const DeviceLazyFrame = vectra.DeviceLazyFrame;
const DeviceDType = vectra.DeviceDType;
const DeviceValidityEncoding = vectra.DeviceValidityEncoding;
const DeviceParquetScan = vectra.DeviceParquetScan;

fn lazyCollectTable(gpa: std.mem.Allocator) !DeviceDataFrame {
    var sales = try DeviceColumn.fromSlice(f64, gpa, &.{ 2.0, 3.0, 5.0, 7.0 }, .cpu);
    defer sales.deinit();
    var units = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4 }, .cpu);
    defer units.deinit();
    var active = try DeviceColumn.fromSlice(bool, gpa, &.{ true, false, true, true }, .cpu);
    defer active.deinit();

    return DeviceDataFrame.init(gpa, &.{
        .{ .name = "sales", .data = sales },
        .{ .name = "units", .data = units },
        .{ .name = "active", .data = active },
    });
}

fn lazyQualityTable(gpa: std.mem.Allocator) !DeviceDataFrame {
    var nullable_quality = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 2.0, 3.0, 4.0 }, &.{ true, false, true, true }, .cpu);
    defer nullable_quality.deinit();
    return DeviceDataFrame.init(gpa, &.{.{ .name = "quality", .data = nullable_quality }});
}

test "device lazy frame collects change operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var change_plan = try DeviceLazyFrame.init(gpa, table);
    defer change_plan.deinit();
    try change_plan.changePointProfile("sales", "sales", 2.0, .{ .periods = 1 });
    try change_plan.select(&.{ "sales", "sales_change_delta", "sales_change_abs_delta", "sales_change_pct", "sales_change_point" });
    const change_explain = try change_plan.explain(gpa);
    defer gpa.free(change_explain);
    try std.testing.expect(std.mem.indexOf(u8, change_explain, "change_point_profile(sales") != null);
    var lazy_change = try change_plan.collect();
    defer lazy_change.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_change.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_change.width());
    const lazy_change_delta = try (try lazy_change.column("sales_change_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_delta);
    const lazy_change_abs_delta = try (try lazy_change.column("sales_change_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_abs_delta);
    const lazy_change_pct = try (try lazy_change.column("sales_change_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_pct);
    const lazy_change_point = try (try lazy_change.column("sales_change_point")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_point);
    const lazy_change_validity = try (try lazy_change.column("sales_change_delta")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_change_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_change_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_change_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_change_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_change_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_change_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.4), lazy_change_pct[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_change_point);
}

test "device lazy frame collects rolling change operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_change_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_change_plan.deinit();
    try rolling_change_plan.rollingChangePointProfile("sales", "sales", 2.0, .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_change_plan.select(&.{ "sales", "sales_rolling_change_count", "sales_rolling_change_point_count", "sales_rolling_change_rate", "sales_rolling_mean_abs_delta", "sales_rolling_max_abs_delta" });
    const rolling_change_explain = try rolling_change_plan.explain(gpa);
    defer gpa.free(rolling_change_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_change_explain, "rolling_change_point_profile(sales") != null);
    var lazy_rolling_change = try rolling_change_plan.collect();
    defer lazy_rolling_change.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_change.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_change.width());
    const lazy_rolling_change_count = try (try lazy_rolling_change.column("sales_rolling_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_count);
    const lazy_rolling_change_point_count = try (try lazy_rolling_change.column("sales_rolling_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_point_count);
    const lazy_rolling_change_rate = try (try lazy_rolling_change.column("sales_rolling_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_rate);
    const lazy_rolling_mean_abs_delta = try (try lazy_rolling_change.column("sales_rolling_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_abs_delta);
    const lazy_rolling_max_abs_delta = try (try lazy_rolling_change.column("sales_rolling_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_max_abs_delta);
    const lazy_rolling_change_validity = try (try lazy_rolling_change.column("sales_rolling_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_rolling_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_rolling_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_change_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_mean_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_rolling_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_max_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_max_abs_delta[3], 1e-12);
}

test "device lazy frame collects expanding change operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_change_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_change_plan.deinit();
    try expanding_change_plan.expandingChangePointProfile("sales", "sales", 2.0, .{ .periods = 1 }, .{ .min_periods = 1 });
    try expanding_change_plan.select(&.{ "sales", "sales_expanding_change_count", "sales_expanding_change_point_count", "sales_expanding_change_rate", "sales_expanding_mean_abs_delta", "sales_expanding_max_abs_delta" });
    const expanding_change_explain = try expanding_change_plan.explain(gpa);
    defer gpa.free(expanding_change_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_change_explain, "expanding_change_point_profile(sales") != null);
    var lazy_expanding_change = try expanding_change_plan.collect();
    defer lazy_expanding_change.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_change.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_change.width());
    const lazy_expanding_change_count = try (try lazy_expanding_change.column("sales_expanding_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_count);
    const lazy_expanding_change_point_count = try (try lazy_expanding_change.column("sales_expanding_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_point_count);
    const lazy_expanding_change_rate = try (try lazy_expanding_change.column("sales_expanding_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_rate);
    const lazy_expanding_mean_abs_delta = try (try lazy_expanding_change.column("sales_expanding_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_abs_delta);
    const lazy_expanding_max_abs_delta = try (try lazy_expanding_change.column("sales_expanding_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_max_abs_delta);
    const lazy_expanding_change_validity = try (try lazy_expanding_change.column("sales_expanding_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3 }, lazy_expanding_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_expanding_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_change_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_mean_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.0), lazy_expanding_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_max_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_expanding_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_expanding_max_abs_delta[3], 1e-12);
}

test "device lazy frame collects sign operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var sign_plan = try DeviceLazyFrame.init(gpa, table);
    defer sign_plan.deinit();
    try sign_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try sign_plan.signProfile("sales_minus4", "sales", .{ .periods = 1 });
    try sign_plan.select(&.{ "sales_minus4", "sales_sign", "sales_sign_flip", "sales_positive_streak", "sales_negative_streak" });
    const sign_explain = try sign_plan.explain(gpa);
    defer gpa.free(sign_explain);
    try std.testing.expect(std.mem.indexOf(u8, sign_explain, "sign_profile(sales_minus4") != null);
    var lazy_sign = try sign_plan.collect();
    defer lazy_sign.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_sign.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_sign.width());
    const lazy_sign_values = try (try lazy_sign.column("sales_sign")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_sign_values);
    const lazy_sign_flip = try (try lazy_sign.column("sales_sign_flip")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_sign_flip);
    const lazy_positive_streak = try (try lazy_sign.column("sales_positive_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_positive_streak);
    const lazy_negative_streak = try (try lazy_sign.column("sales_negative_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_negative_streak);
    try std.testing.expectEqualSlices(i64, &.{ -1, -1, 1, 1 }, lazy_sign_values);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false }, lazy_sign_flip);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_positive_streak);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 0, 0 }, lazy_negative_streak);
}

test "device lazy frame collects rolling sign operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_sign_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_sign_plan.deinit();
    try rolling_sign_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try rolling_sign_plan.rollingSignProfile("sales_minus4", "sales", .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_sign_plan.select(&.{ "sales_minus4", "sales_rolling_sign_count", "sales_rolling_positive_rate", "sales_rolling_negative_rate", "sales_rolling_zero_rate", "sales_rolling_sign_flip_rate" });
    const rolling_sign_explain = try rolling_sign_plan.explain(gpa);
    defer gpa.free(rolling_sign_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_sign_explain, "rolling_sign_profile(sales_minus4") != null);
    var lazy_rolling_sign = try rolling_sign_plan.collect();
    defer lazy_rolling_sign.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_sign.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_sign.width());
    const lazy_rolling_sign_count = try (try lazy_rolling_sign.column("sales_rolling_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_sign_count);
    const lazy_rolling_positive_rate = try (try lazy_rolling_sign.column("sales_rolling_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_positive_rate);
    const lazy_rolling_negative_rate = try (try lazy_rolling_sign.column("sales_rolling_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_negative_rate);
    const lazy_rolling_zero_rate = try (try lazy_rolling_sign.column("sales_rolling_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_zero_rate);
    const lazy_rolling_sign_flip_rate = try (try lazy_rolling_sign.column("sales_rolling_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_sign_flip_rate);
    const lazy_rolling_sign_validity = try (try lazy_rolling_sign.column("sales_rolling_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_sign_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_rolling_sign_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_positive_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_positive_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_negative_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_negative_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_negative_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_zero_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_sign_flip_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_sign_flip_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_sign_flip_rate[3], 1e-12);
}

test "device lazy frame collects expanding sign operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_sign_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_sign_plan.deinit();
    try expanding_sign_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try expanding_sign_plan.expandingSignProfile("sales_minus4", "sales", .{ .periods = 1 }, .{ .min_periods = 1 });
    try expanding_sign_plan.select(&.{ "sales_minus4", "sales_expanding_sign_count", "sales_expanding_positive_rate", "sales_expanding_negative_rate", "sales_expanding_zero_rate", "sales_expanding_sign_flip_rate" });
    const expanding_sign_explain = try expanding_sign_plan.explain(gpa);
    defer gpa.free(expanding_sign_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_sign_explain, "expanding_sign_profile(sales_minus4") != null);
    var lazy_expanding_sign = try expanding_sign_plan.collect();
    defer lazy_expanding_sign.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_sign.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_sign.width());
    const lazy_expanding_sign_count = try (try lazy_expanding_sign.column("sales_expanding_sign_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_sign_count);
    const lazy_expanding_positive_rate = try (try lazy_expanding_sign.column("sales_expanding_positive_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_positive_rate);
    const lazy_expanding_negative_rate = try (try lazy_expanding_sign.column("sales_expanding_negative_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_negative_rate);
    const lazy_expanding_zero_rate = try (try lazy_expanding_sign.column("sales_expanding_zero_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_zero_rate);
    const lazy_expanding_sign_flip_rate = try (try lazy_expanding_sign.column("sales_expanding_sign_flip_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_sign_flip_rate);
    const lazy_expanding_sign_validity = try (try lazy_expanding_sign.column("sales_expanding_positive_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_sign_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_sign_count);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_expanding_sign_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_positive_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_positive_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_positive_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_positive_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_negative_rate[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_negative_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_negative_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_negative_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_zero_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_sign_flip_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_sign_flip_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_sign_flip_rate[3], 1e-12);
}

test "device lazy frame collects validity operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var validity_plan = try DeviceLazyFrame.init(gpa, table);
    defer validity_plan.deinit();
    try validity_plan.validityProfile("sales", "sales");
    try validity_plan.select(&.{ "sales", "sales_is_null", "sales_is_valid", "sales_valid_streak", "sales_null_streak" });
    const validity_explain = try validity_plan.explain(gpa);
    defer gpa.free(validity_explain);
    try std.testing.expect(std.mem.indexOf(u8, validity_explain, "validity_profile(sales") != null);
    var lazy_validity = try validity_plan.collect();
    defer lazy_validity.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_validity.height());
    try std.testing.expectEqual(@as(usize, 5), lazy_validity.width());
    const lazy_is_null = try (try lazy_validity.column("sales_is_null")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_is_null);
    const lazy_is_valid = try (try lazy_validity.column("sales_is_valid")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_is_valid);
    const lazy_valid_streak = try (try lazy_validity.column("sales_valid_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_valid_streak);
    const lazy_null_streak = try (try lazy_validity.column("sales_null_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_null_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_is_null);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_is_valid);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_valid_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_null_streak);
}

test "device lazy frame collects rolling validity operations" {
    const gpa = std.testing.allocator;
    var quality_table = try lazyQualityTable(gpa);
    defer quality_table.deinit();
    var rolling_validity_plan = try DeviceLazyFrame.init(gpa, quality_table);
    defer rolling_validity_plan.deinit();
    try rolling_validity_plan.rollingValidityProfile("quality", "quality", .{ .window = 2, .min_periods = 2 });
    try rolling_validity_plan.select(&.{ "quality", "quality_rolling_validity_count", "quality_rolling_valid_count", "quality_rolling_null_count", "quality_rolling_valid_rate", "quality_rolling_null_rate" });
    const rolling_validity_explain = try rolling_validity_plan.explain(gpa);
    defer gpa.free(rolling_validity_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_validity_explain, "rolling_validity_profile(quality") != null);
    var lazy_rolling_validity = try rolling_validity_plan.collect();
    defer lazy_rolling_validity.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_validity.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_rolling_validity.width());
    const lazy_rolling_validity_count = try (try lazy_rolling_validity.column("quality_rolling_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_validity_count);
    const lazy_rolling_valid_count = try (try lazy_rolling_validity.column("quality_rolling_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_valid_count);
    const lazy_rolling_null_count = try (try lazy_rolling_validity.column("quality_rolling_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_null_count);
    const lazy_rolling_valid_rate = try (try lazy_rolling_validity.column("quality_rolling_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_valid_rate);
    const lazy_rolling_null_rate = try (try lazy_rolling_validity.column("quality_rolling_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_null_rate);
    const lazy_rolling_validity_validity = try (try lazy_rolling_validity.column("quality_rolling_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_validity_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 2 }, lazy_rolling_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_rolling_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_validity_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_valid_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_valid_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_null_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_null_rate[3], 1e-12);
}

test "device lazy frame collects expanding validity operations" {
    const gpa = std.testing.allocator;
    var quality_table = try lazyQualityTable(gpa);
    defer quality_table.deinit();
    var expanding_validity_plan = try DeviceLazyFrame.init(gpa, quality_table);
    defer expanding_validity_plan.deinit();
    try expanding_validity_plan.expandingValidityProfile("quality", "quality", .{ .min_periods = 2 });
    try expanding_validity_plan.select(&.{ "quality", "quality_expanding_validity_count", "quality_expanding_valid_count", "quality_expanding_null_count", "quality_expanding_valid_rate", "quality_expanding_null_rate" });
    const expanding_validity_explain = try expanding_validity_plan.explain(gpa);
    defer gpa.free(expanding_validity_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_validity_explain, "expanding_validity_profile(quality") != null);
    var lazy_expanding_validity = try expanding_validity_plan.collect();
    defer lazy_expanding_validity.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_validity.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_expanding_validity.width());
    const lazy_expanding_validity_count = try (try lazy_expanding_validity.column("quality_expanding_validity_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_validity_count);
    const lazy_expanding_valid_count = try (try lazy_expanding_validity.column("quality_expanding_valid_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_valid_count);
    const lazy_expanding_null_count = try (try lazy_expanding_validity.column("quality_expanding_null_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_null_count);
    const lazy_expanding_valid_rate = try (try lazy_expanding_validity.column("quality_expanding_valid_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_valid_rate);
    const lazy_expanding_null_rate = try (try lazy_expanding_validity.column("quality_expanding_null_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_null_rate);
    const lazy_expanding_validity_validity = try (try lazy_expanding_validity.column("quality_expanding_valid_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_validity_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_validity_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 2, 3 }, lazy_expanding_valid_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_null_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_validity_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_valid_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_valid_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_expanding_valid_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_null_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_null_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_null_rate[3], 1e-12);
}

test "device lazy frame collects class operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var class_plan = try DeviceLazyFrame.init(gpa, table);
    defer class_plan.deinit();
    try class_plan.withColumnCompareScalar("predicted_active", "sales", f64, 4.0, .gt);
    try class_plan.classificationProfile("active", "predicted_active", "active_cls");
    try class_plan.select(&.{ "active", "predicted_active", "active_cls_tp", "active_cls_fp", "active_cls_tn", "active_cls_fn", "active_cls_correct" });
    const class_explain = try class_plan.explain(gpa);
    defer gpa.free(class_explain);
    try std.testing.expect(std.mem.indexOf(u8, class_explain, "classification_profile(actual=active, predicted=predicted_active") != null);
    var classed = try class_plan.collect();
    defer classed.deinit();
    try std.testing.expectEqual(@as(usize, 4), classed.height());
    try std.testing.expectEqual(@as(usize, 7), classed.width());
    const lazy_tp = try (try classed.column("active_cls_tp")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_tp);
    const lazy_fp = try (try classed.column("active_cls_fp")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_fp);
    const lazy_tn = try (try classed.column("active_cls_tn")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_tn);
    const lazy_fn = try (try classed.column("active_cls_fn")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_fn);
    const lazy_correct = try (try classed.column("active_cls_correct")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_correct);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_tp);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_fp);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false }, lazy_tn);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false }, lazy_fn);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_correct);
}

test "device lazy frame collects rolling class operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_class_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_class_plan.deinit();
    try rolling_class_plan.withColumnCompareScalar("predicted_active", "sales", f64, 4.0, .gt);
    try rolling_class_plan.rollingClassificationProfile("active", "predicted_active", "active_cls", .{ .window = 2, .min_periods = 2 });
    try rolling_class_plan.select(&.{ "active", "predicted_active", "active_cls_rolling_class_count", "active_cls_rolling_tp_count", "active_cls_rolling_fp_count", "active_cls_rolling_tn_count", "active_cls_rolling_fn_count", "active_cls_rolling_accuracy", "active_cls_rolling_precision", "active_cls_rolling_recall" });
    const rolling_class_explain = try rolling_class_plan.explain(gpa);
    defer gpa.free(rolling_class_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_class_explain, "rolling_classification_profile(actual=active, predicted=predicted_active") != null);
    var lazy_rolling_class = try rolling_class_plan.collect();
    defer lazy_rolling_class.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_class.height());
    try std.testing.expectEqual(@as(usize, 10), lazy_rolling_class.width());
    const lazy_rolling_class_count = try (try lazy_rolling_class.column("active_cls_rolling_class_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_class_count);
    const lazy_rolling_tp_count = try (try lazy_rolling_class.column("active_cls_rolling_tp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_tp_count);
    const lazy_rolling_fp_count = try (try lazy_rolling_class.column("active_cls_rolling_fp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fp_count);
    const lazy_rolling_tn_count = try (try lazy_rolling_class.column("active_cls_rolling_tn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_tn_count);
    const lazy_rolling_fn_count = try (try lazy_rolling_class.column("active_cls_rolling_fn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fn_count);
    const lazy_rolling_accuracy = try (try lazy_rolling_class.column("active_cls_rolling_accuracy")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_accuracy);
    const lazy_rolling_precision = try (try lazy_rolling_class.column("active_cls_rolling_precision")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_precision);
    const lazy_rolling_recall = try (try lazy_rolling_class.column("active_cls_rolling_recall")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_recall);
    const lazy_rolling_class_validity = try (try lazy_rolling_class.column("active_cls_rolling_accuracy")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_class_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_class_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_rolling_tp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_rolling_fp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_rolling_tn_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 0, 0 }, lazy_rolling_fn_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_class_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_accuracy[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_accuracy[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_accuracy[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_rolling_precision[1]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_precision[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_precision[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_recall[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_recall[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_recall[3], 1e-12);
}

test "device lazy frame collects expanding class operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_class_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_class_plan.deinit();
    try expanding_class_plan.withColumnCompareScalar("predicted_active", "sales", f64, 4.0, .gt);
    try expanding_class_plan.expandingClassificationProfile("active", "predicted_active", "active_cls", .{ .min_periods = 2 });
    try expanding_class_plan.select(&.{ "active", "predicted_active", "active_cls_expanding_class_count", "active_cls_expanding_tp_count", "active_cls_expanding_fp_count", "active_cls_expanding_tn_count", "active_cls_expanding_fn_count", "active_cls_expanding_accuracy", "active_cls_expanding_precision", "active_cls_expanding_recall" });
    const expanding_class_explain = try expanding_class_plan.explain(gpa);
    defer gpa.free(expanding_class_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_class_explain, "expanding_classification_profile(actual=active, predicted=predicted_active") != null);
    var lazy_expanding_class = try expanding_class_plan.collect();
    defer lazy_expanding_class.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_class.height());
    try std.testing.expectEqual(@as(usize, 10), lazy_expanding_class.width());
    const lazy_expanding_class_count = try (try lazy_expanding_class.column("active_cls_expanding_class_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_class_count);
    const lazy_expanding_tp_count = try (try lazy_expanding_class.column("active_cls_expanding_tp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_tp_count);
    const lazy_expanding_fp_count = try (try lazy_expanding_class.column("active_cls_expanding_fp_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fp_count);
    const lazy_expanding_tn_count = try (try lazy_expanding_class.column("active_cls_expanding_tn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_tn_count);
    const lazy_expanding_fn_count = try (try lazy_expanding_class.column("active_cls_expanding_fn_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fn_count);
    const lazy_expanding_accuracy = try (try lazy_expanding_class.column("active_cls_expanding_accuracy")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_accuracy);
    const lazy_expanding_precision = try (try lazy_expanding_class.column("active_cls_expanding_precision")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_precision);
    const lazy_expanding_recall = try (try lazy_expanding_class.column("active_cls_expanding_recall")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_recall);
    const lazy_expanding_class_validity = try (try lazy_expanding_class.column("active_cls_expanding_accuracy")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_class_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_class_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 2 }, lazy_expanding_tp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_expanding_fp_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_tn_count);
    try std.testing.expectEqualSlices(i64, &.{ 1, 1, 1, 1 }, lazy_expanding_fn_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_class_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_accuracy[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_accuracy[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_expanding_accuracy[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_expanding_precision[1]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_precision[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_precision[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_recall[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_recall[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_recall[3], 1e-12);
}

test "device lazy frame collects transition operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var transition_plan = try DeviceLazyFrame.init(gpa, table);
    defer transition_plan.deinit();
    try transition_plan.boolTransitionProfile("active", "active", .{ .periods = 1 });
    try transition_plan.select(&.{ "active", "active_rising", "active_falling", "active_toggled", "active_true_streak", "active_false_streak" });
    const transition_explain = try transition_plan.explain(gpa);
    defer gpa.free(transition_explain);
    try std.testing.expect(std.mem.indexOf(u8, transition_explain, "bool_transition_profile(active") != null);
    var lazy_transition = try transition_plan.collect();
    defer lazy_transition.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_transition.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_transition.width());
    const lazy_rising = try (try lazy_transition.column("active_rising")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_rising);
    const lazy_falling = try (try lazy_transition.column("active_falling")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_falling);
    const lazy_toggled = try (try lazy_transition.column("active_toggled")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_toggled);
    const lazy_true_streak = try (try lazy_transition.column("active_true_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_true_streak);
    const lazy_false_streak = try (try lazy_transition.column("active_false_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_false_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false }, lazy_rising);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false }, lazy_falling);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, false }, lazy_toggled);
    try std.testing.expectEqualSlices(i64, &.{ 1, 0, 1, 2 }, lazy_true_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 0, 0 }, lazy_false_streak);
}

test "device lazy frame collects rolling transition operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_transition_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_transition_plan.deinit();
    try rolling_transition_plan.rollingBoolTransitionProfile("active", "active", .{ .periods = 1 }, .{ .window = 2, .min_periods = 1 });
    try rolling_transition_plan.select(&.{ "active", "active_rolling_transition_count", "active_rolling_rising_count", "active_rolling_falling_count", "active_rolling_toggle_count", "active_rolling_rising_rate", "active_rolling_falling_rate", "active_rolling_toggle_rate" });
    const rolling_transition_explain = try rolling_transition_plan.explain(gpa);
    defer gpa.free(rolling_transition_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_transition_explain, "rolling_bool_transition_profile(active") != null);
    var lazy_rolling_transition = try rolling_transition_plan.collect();
    defer lazy_rolling_transition.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_rolling_transition.height());
    try std.testing.expectEqual(@as(usize, 8), lazy_rolling_transition.width());
    const lazy_rolling_transition_count = try (try lazy_rolling_transition.column("active_rolling_transition_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_transition_count);
    const lazy_rolling_rising_count = try (try lazy_rolling_transition.column("active_rolling_rising_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_rising_count);
    const lazy_rolling_falling_count = try (try lazy_rolling_transition.column("active_rolling_falling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_falling_count);
    const lazy_rolling_toggle_count = try (try lazy_rolling_transition.column("active_rolling_toggle_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_toggle_count);
    const lazy_rolling_rising_rate = try (try lazy_rolling_transition.column("active_rolling_rising_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_rising_rate);
    const lazy_rolling_falling_rate = try (try lazy_rolling_transition.column("active_rolling_falling_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_falling_rate);
    const lazy_rolling_toggle_rate = try (try lazy_rolling_transition.column("active_rolling_toggle_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_toggle_rate);
    const lazy_rolling_transition_validity = try (try lazy_rolling_transition.column("active_rolling_toggle_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_transition_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_rolling_transition_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_rolling_rising_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 0 }, lazy_rolling_falling_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 1 }, lazy_rolling_toggle_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_transition_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_rising_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_rising_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_rising_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_falling_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_falling_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_falling_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_toggle_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_toggle_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_toggle_rate[3], 1e-12);
}

test "device lazy frame collects expanding transition operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_transition_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_transition_plan.deinit();
    try expanding_transition_plan.expandingBoolTransitionProfile("active", "active", .{ .periods = 1 }, .{ .min_periods = 2 });
    try expanding_transition_plan.select(&.{ "active", "active_expanding_transition_count", "active_expanding_rising_count", "active_expanding_falling_count", "active_expanding_toggle_count", "active_expanding_rising_rate", "active_expanding_falling_rate", "active_expanding_toggle_rate" });
    const expanding_transition_explain = try expanding_transition_plan.explain(gpa);
    defer gpa.free(expanding_transition_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_transition_explain, "expanding_bool_transition_profile(active") != null);
    var lazy_expanding_transition = try expanding_transition_plan.collect();
    defer lazy_expanding_transition.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_expanding_transition.height());
    try std.testing.expectEqual(@as(usize, 8), lazy_expanding_transition.width());
    const lazy_expanding_transition_count = try (try lazy_expanding_transition.column("active_expanding_transition_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_transition_count);
    const lazy_expanding_rising_count = try (try lazy_expanding_transition.column("active_expanding_rising_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_rising_count);
    const lazy_expanding_falling_count = try (try lazy_expanding_transition.column("active_expanding_falling_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_falling_count);
    const lazy_expanding_toggle_count = try (try lazy_expanding_transition.column("active_expanding_toggle_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_toggle_count);
    const lazy_expanding_rising_rate = try (try lazy_expanding_transition.column("active_expanding_rising_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_rising_rate);
    const lazy_expanding_falling_rate = try (try lazy_expanding_transition.column("active_expanding_falling_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_falling_rate);
    const lazy_expanding_toggle_rate = try (try lazy_expanding_transition.column("active_expanding_toggle_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_toggle_rate);
    const lazy_expanding_transition_validity = try (try lazy_expanding_transition.column("active_expanding_toggle_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_transition_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3 }, lazy_expanding_transition_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_expanding_rising_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1 }, lazy_expanding_falling_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 2 }, lazy_expanding_toggle_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_expanding_transition_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_rising_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_rising_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_falling_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_falling_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_toggle_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_expanding_toggle_rate[3], 1e-12);
}
