const std = @import("std");
const vectra = @import("vectra");

const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;

test "device dataframe trend and change profile methods" {
    const gpa = std.testing.allocator;

    var trend_source = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 3.0, 2.0, 2.0, 5.0, 0.0, 4.0 }, &.{ true, true, true, true, true, false, true }, .cpu);
    defer trend_source.deinit();
    var trend_id = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4, 5, 6, 7 }, .cpu);
    defer trend_id.deinit();
    var trend_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "price", .data = trend_source },
        .{ .name = "id", .data = trend_id },
    });
    defer trend_table.deinit();

    var trend = try trend_table.trendProfile("price", "price", .{ .periods = 1 });
    defer trend.deinit();
    try std.testing.expectEqual(@as(usize, 7), trend.width());
    const trend_values = try (try trend.column("price_trend")).i64.toOwnedSlice(gpa);
    defer gpa.free(trend_values);
    const up_streak = try (try trend.column("price_up_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(up_streak);
    const down_streak = try (try trend.column("price_down_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(down_streak);
    const flat_streak = try (try trend.column("price_flat_streak")).i64.toOwnedSlice(gpa);
    defer gpa.free(flat_streak);
    const reversal = try (try trend.column("price_reversal")).bool.toOwnedSlice(gpa);
    defer gpa.free(reversal);
    const trend_validity = try (try trend.column("price_trend")).i64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(trend_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false, false }, trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, -1, 0, 1, 0, 0 }, trend_values);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 0, 0, 1, 0, 0 }, up_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 0, 0, 0, 0 }, down_streak);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 1, 0, 0, 0 }, flat_streak);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, false, true, false, false }, reversal);

    var rolling_trends = try trend_table.rollingTrendProfile("price", "price", .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_trends.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_trends.width());
    const rolling_trend_count = try (try rolling_trends.column("price_rolling_trend_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_trend_count);
    const rolling_up_rate = try (try rolling_trends.column("price_rolling_up_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_up_rate);
    const rolling_down_rate = try (try rolling_trends.column("price_rolling_down_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_down_rate);
    const rolling_flat_rate = try (try rolling_trends.column("price_rolling_flat_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_flat_rate);
    const rolling_reversal_rate = try (try rolling_trends.column("price_rolling_reversal_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_reversal_rate);
    const rolling_trend_validity = try (try rolling_trends.column("price_rolling_up_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 3, 2, 1 }, rolling_trend_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, false }, rolling_trend_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_up_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_up_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_up_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_up_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_down_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_down_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_flat_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), rolling_reversal_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_reversal_rate[5], 1e-12);

    var expanding_trends = try trend_table.expandingTrendProfile("price", "price", .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_trends.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_trends.width());
    const expanding_trend_count = try (try expanding_trends.column("price_expanding_trend_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_trend_count);
    const expanding_up_rate = try (try expanding_trends.column("price_expanding_up_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_up_rate);
    const expanding_down_rate = try (try expanding_trends.column("price_expanding_down_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_down_rate);
    const expanding_flat_rate = try (try expanding_trends.column("price_expanding_flat_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_flat_rate);
    const expanding_reversal_rate = try (try expanding_trends.column("price_expanding_reversal_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_reversal_rate);
    const expanding_trend_validity = try (try expanding_trends.column("price_expanding_up_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_trend_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 4, 4, 4 }, expanding_trend_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, true }, expanding_trend_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_up_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_up_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_up_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_down_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_down_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_down_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_flat_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), expanding_flat_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_reversal_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_reversal_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_reversal_rate[4], 1e-12);

    var changes = try trend_table.changePointProfile("price", "price", 2.0, .{ .periods = 1 });
    defer changes.deinit();
    try std.testing.expectEqual(@as(usize, 6), changes.width());
    const change_delta = try (try changes.column("price_change_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(change_delta);
    const change_abs_delta = try (try changes.column("price_change_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(change_abs_delta);
    const change_pct = try (try changes.column("price_change_pct")).f64.toOwnedSlice(gpa);
    defer gpa.free(change_pct);
    const change_point = try (try changes.column("price_change_point")).bool.toOwnedSlice(gpa);
    defer gpa.free(change_point);
    const change_validity = try (try changes.column("price_change_delta")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(change_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true, false, false }, change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), change_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), change_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), change_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), change_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), change_abs_delta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), change_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), change_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), change_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), change_pct[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0 / 3.0), change_pct[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), change_pct[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), change_pct[4], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, true, false, false, true, false, false }, change_point);

    var rolling_changes = try trend_table.rollingChangePointProfile("price", "price", 2.0, .{ .periods = 1 }, .{ .window = 3, .min_periods = 2 });
    defer rolling_changes.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_changes.width());
    const rolling_change_count = try (try rolling_changes.column("price_rolling_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_count);
    const rolling_change_point_count = try (try rolling_changes.column("price_rolling_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_point_count);
    const rolling_change_rate = try (try rolling_changes.column("price_rolling_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_rate);
    const rolling_mean_abs_delta = try (try rolling_changes.column("price_rolling_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mean_abs_delta);
    const rolling_max_abs_delta = try (try rolling_changes.column("price_rolling_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_max_abs_delta);
    const rolling_change_validity = try (try rolling_changes.column("price_rolling_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 3, 2, 1 }, rolling_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 1, 1, 1 }, rolling_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, false }, rolling_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_change_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), rolling_change_rate[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), rolling_mean_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), rolling_mean_abs_delta[5], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_max_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_max_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), rolling_max_abs_delta[5], 1e-12);

    var expanding_changes = try trend_table.expandingChangePointProfile("price", "price", 2.0, .{ .periods = 1 }, .{ .min_periods = 2 });
    defer expanding_changes.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_changes.width());
    const expanding_change_count = try (try expanding_changes.column("price_expanding_change_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_count);
    const expanding_change_point_count = try (try expanding_changes.column("price_expanding_change_point_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_point_count);
    const expanding_change_rate = try (try expanding_changes.column("price_expanding_change_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_rate);
    const expanding_mean_abs_delta = try (try expanding_changes.column("price_expanding_mean_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean_abs_delta);
    const expanding_max_abs_delta = try (try expanding_changes.column("price_expanding_max_abs_delta")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_max_abs_delta);
    const expanding_change_validity = try (try expanding_changes.column("price_expanding_change_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_change_validity);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 2, 3, 4, 4, 4 }, expanding_change_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 1, 1, 2, 2, 2 }, expanding_change_point_count);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true, true, true, true }, expanding_change_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_change_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_change_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_change_rate[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_mean_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_mean_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), expanding_mean_abs_delta[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_max_abs_delta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_max_abs_delta[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_max_abs_delta[4], 1e-12);
}
