//! Lazy dataframe operation tags and ownership helpers.
//!
//! `DeviceLazyOp` carries many operation payload variants and therefore used to
//! dominate the public dataframe facade. Keeping the union generic over the
//! concrete dataframe/column types avoids an import cycle while moving the
//! clone/deinit ownership rules into a focused module.

const std = @import("std");
const array_mod = @import("array.zig");
const ownership_mod = @import("dataframe_lazy_op_ownership.zig");
const payloads_mod = @import("dataframe_lazy_op_payloads.zig");
const series_mod = @import("series.zig");

const DeviceDataError = series_mod.DataError || array_mod.ArrayError;

pub const DeviceLazyGroupByAggregation = payloads_mod.DeviceLazyGroupByAggregation;
pub const DeviceLazyJoinKind = payloads_mod.DeviceLazyJoinKind;

pub fn DeviceLazyOp(comptime DeviceDataFrame: type, comptime DeviceColumn: type) type {
    const Payloads = payloads_mod.DeviceLazyPayloads(DeviceDataFrame, DeviceColumn);
    return union(enum) {
        const Self = @This();
        select: Payloads.Select,
        select_column_indices: Payloads.ColumnIndices,
        select_column_range: Payloads.ColumnRange,
        select_last_columns: Payloads.HeadTail,
        drop_column_indices: Payloads.ColumnIndices,
        drop_column_range: Payloads.ColumnRange,
        drop_last_columns: Payloads.HeadTail,
        reverse_columns,
        sort_columns_by_name: Payloads.SortColumnsByName,
        select_name_prefix: Payloads.NamePattern,
        select_name_suffix: Payloads.NamePattern,
        select_name_contains: Payloads.NamePattern,
        drop_name_prefix: Payloads.NamePattern,
        drop_name_suffix: Payloads.NamePattern,
        drop_name_contains: Payloads.NamePattern,
        select_dtypes: Payloads.DTypes,
        select_dtype_class: Payloads.DTypeClass,
        drop_dtypes: Payloads.DTypes,
        drop_dtype_class: Payloads.DTypeClass,
        select_nullable_columns,
        select_non_nullable_columns,
        select_columns_with_nulls,
        select_columns_without_nulls,
        drop_nullable_columns,
        drop_non_nullable_columns,
        drop_columns_with_nulls,
        drop_columns_without_nulls,
        with_row_index: Payloads.RowIndex,
        rename_column: Payloads.RenameColumn,
        rename_columns: Payloads.RenameColumns,
        add_column_name_prefix: Payloads.RenameNamePattern,
        add_column_name_suffix: Payloads.RenameNamePattern,
        move_column: Payloads.MoveColumn,
        move_column_before: Payloads.MoveColumnRelative,
        move_column_after: Payloads.MoveColumnRelative,
        copy_column: Payloads.CopyColumn,
        copy_column_at: Payloads.CopyColumnAt,
        copy_column_before: Payloads.CopyColumnRelative,
        copy_column_after: Payloads.CopyColumnRelative,
        drop_columns: Payloads.DropColumns,
        drop_nulls: Payloads.DropNulls,
        filter_nulls_column: Payloads.FilterColumn,
        drop_nans: Payloads.DropNulls,
        filter_nans_column: Payloads.FilterColumn,
        with_column_binary: Payloads.WithColumnBinary,
        with_column_scalar: Payloads.WithColumnScalar,
        with_column_literal: Payloads.WithColumnLiteral,
        with_column_literal_at: Payloads.WithColumnLiteralAt,
        with_column_literal_before: Payloads.WithColumnLiteralRelative,
        with_column_literal_after: Payloads.WithColumnLiteralRelative,
        cast_column: Payloads.CastColumn,
        fill_null_column: Payloads.FillNullColumn,
        fill_nan_column: Payloads.FillNullColumn,
        coalesce_columns: Payloads.CoalesceColumns,
        is_null_column: Payloads.NullPredicateColumn,
        is_valid_column: Payloads.NullPredicateColumn,
        is_nan_column: Payloads.NullPredicateColumn,
        is_finite_column: Payloads.NullPredicateColumn,
        is_inf_column: Payloads.NullPredicateColumn,
        row_null_count: Payloads.RowValidityCount,
        row_valid_count: Payloads.RowValidityCount,
        with_column_compare: Payloads.WithColumnCompare,
        with_column_compare_scalar: Payloads.WithColumnCompareScalar,
        filter_mask: Payloads.FilterMask,
        filter_column: Payloads.FilterColumn,
        filter_scalar: Payloads.FilterScalar,
        group_by_count: Payloads.GroupByCount,
        group_by_value: Payloads.GroupByValue,
        group_by_stats: Payloads.GroupByOutput,
        group_by_stats_on: Payloads.GroupByOutputOn,
        group_by_profile: Payloads.GroupByOutput,
        group_by_profile_on: Payloads.GroupByOutputOn,
        join_on: Payloads.JoinOn,
        asof_join: Payloads.AsofJoin,
        concat_rows: Payloads.ConcatRows,
        distinct_rows,
        distinct_on: Payloads.DistinctOn,
        sort_by: Payloads.SortBy,
        top_k: Payloads.TopK,
        rank_profile_by: Payloads.RankProfileBy,
        rolling_profile: Payloads.RollingProfile,
        rolling_moment_profile: Payloads.RollingProfile,
        rolling_range_profile: Payloads.RollingProfile,
        rolling_normalize_profile: Payloads.RollingProfile,
        expanding_normalize_profile: Payloads.ExpandingProfile,
        rolling_quantile_profile: Payloads.RollingProfile,
        expanding_quantile_profile: Payloads.ExpandingProfile,
        rolling_bool_profile: Payloads.RollingProfile,
        rolling_drawdown_profile: Payloads.RollingProfile,
        rolling_robust_profile: Payloads.RollingRobustProfile,
        rolling_rank_profile: Payloads.RollingRankProfile,
        lag_profile: Payloads.LagProfile,
        lead_profile: Payloads.LagProfile,
        clip_profile: Payloads.ClipProfile,
        rolling_clip_profile: Payloads.RollingClipProfile,
        expanding_clip_profile: Payloads.ExpandingClipProfile,
        threshold_profile: Payloads.ThresholdProfile,
        rolling_threshold_profile: Payloads.RollingThresholdProfile,
        expanding_threshold_profile: Payloads.ExpandingThresholdProfile,
        expanding_profile: Payloads.ExpandingProfile,
        expanding_bool_profile: Payloads.ExpandingProfile,
        expanding_rank_profile: Payloads.ExpandingRankProfile,
        expanding_robust_profile: Payloads.ExpandingRobustProfile,
        expanding_moment_profile: Payloads.ExpandingProfile,
        standardize_profile: Payloads.StandardizeProfile,
        robust_profile: Payloads.RobustProfile,
        drawdown_profile: Payloads.DrawdownProfile,
        extrema_profile: Payloads.ExtremaProfile,
        trend_profile: Payloads.TrendProfile,
        rolling_trend_profile: Payloads.RollingTrendProfile,
        expanding_trend_profile: Payloads.ExpandingTrendProfile,
        change_point_profile: Payloads.ChangePointProfile,
        rolling_change_point_profile: Payloads.RollingChangePointProfile,
        expanding_change_point_profile: Payloads.ExpandingChangePointProfile,
        sign_profile: Payloads.TrendProfile,
        rolling_sign_profile: Payloads.RollingSignProfile,
        expanding_sign_profile: Payloads.ExpandingSignProfile,
        crossover_profile: Payloads.CrossoverProfile,
        rolling_crossover_profile: Payloads.RollingCrossoverProfile,
        expanding_crossover_profile: Payloads.ExpandingCrossoverProfile,
        bucket_profile: Payloads.BucketProfile,
        ema_profile: Payloads.EmaProfile,
        linear_fit_profile: Payloads.LinearFitProfile,
        error_profile: Payloads.PairOutput,
        rolling_error_profile: Payloads.RollingPairOutput,
        expanding_error_profile: Payloads.ExpandingPairOutput,
        classification_profile: Payloads.PairOutput,
        rolling_classification_profile: Payloads.RollingPairOutput,
        expanding_classification_profile: Payloads.ExpandingPairOutput,
        bool_transition_profile: Payloads.BoolTransitionProfile,
        rolling_bool_transition_profile: Payloads.RollingBoolTransitionProfile,
        expanding_bool_transition_profile: Payloads.ExpandingBoolTransitionProfile,
        rolling_correlation_profile: Payloads.RollingCorrelationProfile,
        expanding_correlation_profile: Payloads.ExpandingXYProfile,
        expanding_linear_fit_profile: Payloads.ExpandingXYProfile,
        rolling_linear_fit_profile: Payloads.RollingLinearFitProfile,
        validity_profile: Payloads.ValidityProfile,
        rolling_validity_profile: Payloads.RollingValidityProfile,
        expanding_validity_profile: Payloads.ExpandingValidityProfile,
        slice_rows: Payloads.RowSlice,
        drop_rows: Payloads.RowTake,
        drop_row_range: Payloads.RowSlice,
        drop_last_rows: Payloads.HeadTail,
        slice_rows_step: Payloads.RowSliceStep,
        stride_rows: Payloads.RowStride,
        take_rows: Payloads.RowTake,
        sample_rows: Payloads.RowSample,
        sample_rows_with_replacement: Payloads.RowSample,
        reverse_rows,
        head: Payloads.HeadTail,
        tail: Payloads.HeadTail,

        pub fn deinit(self: *Self, allocator: std.mem.Allocator) void {
            ownership_mod.deinit(Self, self, allocator);
        }

        pub fn clone(self: Self, allocator: std.mem.Allocator) DeviceDataError!Self {
            return ownership_mod.clone(Self, self, allocator);
        }
    };
}
