const std = @import("std");
const vectra = @import("vectra");

const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;

test "device dataframe fit error and bucket profile methods" {
    const gpa = std.testing.allocator;

    var fit_x = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 2.0, 3.0, 4.0, 5.0 }, &.{ true, true, true, true, false }, .cpu);
    defer fit_x.deinit();
    var fit_y = try DeviceColumn.fromSlice(f64, gpa, &.{ 3.0, 5.0, 8.0, 9.0, 0.0 }, .cpu);
    defer fit_y.deinit();
    var fit_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "x", .data = fit_x },
        .{ .name = "y", .data = fit_y },
    });
    defer fit_table.deinit();

    var fitted_table = try fit_table.linearFitProfile("x", "y", "xy", .{ .min_periods = 3 });
    defer fitted_table.deinit();
    try std.testing.expectEqual(@as(usize, 6), fitted_table.width());
    const fitted = try (try fitted_table.column("xy_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(fitted);
    const residual = try (try fitted_table.column("xy_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(residual);
    const residual_z = try (try fitted_table.column("xy_residual_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(residual_z);
    const slope_values = try (try fitted_table.column("xy_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(slope_values);
    const fit_validity = try (try fitted_table.column("xy_fitted")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(fit_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false }, fit_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 3.1), fitted[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.2), fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.3), fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 9.4), fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.1), residual[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.2), residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.7), residual[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.4), residual[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.23904572186687895), residual_z[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.4780914437337579), residual_z[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.6733200530681511), residual_z[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.9561828874675167), residual_z[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.1), slope_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.1), slope_values[3], 1e-12);

    var rolling_fit = try fit_table.rollingLinearFitProfile("x", "y", "xy", .{ .window = 3, .min_periods = 2 });
    defer rolling_fit.deinit();
    try std.testing.expectEqual(@as(usize, 8), rolling_fit.width());
    const rolling_fit_count = try (try rolling_fit.column("xy_rolling_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_fit_count);
    const rolling_slope = try (try rolling_fit.column("xy_rolling_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_slope);
    const rolling_intercept = try (try rolling_fit.column("xy_rolling_intercept")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_intercept);
    const rolling_fitted = try (try rolling_fit.column("xy_rolling_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_fitted);
    const rolling_residual = try (try rolling_fit.column("xy_rolling_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_residual);
    const rolling_residual_z = try (try rolling_fit.column("xy_rolling_residual_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_residual_z);
    const rolling_slope_validity = try (try rolling_fit.column("xy_rolling_slope")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_slope_validity);
    const rolling_fitted_validity = try (try rolling_fit.column("xy_rolling_fitted")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_fitted_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 2 }, rolling_fit_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_slope_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, false }, rolling_fitted_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_slope[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), rolling_slope[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), rolling_slope[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_slope[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), rolling_intercept[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), rolling_intercept[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), rolling_intercept[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), rolling_intercept[4], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), rolling_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 47.0 / 6.0), rolling_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 28.0 / 3.0), rolling_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), rolling_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 6.0), rolling_residual[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0 / 3.0), rolling_residual[3], 1e-12);
    try std.testing.expect(std.math.isNan(rolling_residual_z[1]));
    try std.testing.expectApproxEqAbs(@as(f64, 0.7071067811865475), rolling_residual_z[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.7071067811865475), rolling_residual_z[3], 1e-12);

    var expanding_corr = try fit_table.expandingCorrelationProfile("x", "y", "xy_corr", .{ .min_periods = 2 });
    defer expanding_corr.deinit();
    try std.testing.expectEqual(@as(usize, 6), expanding_corr.width());
    const expanding_pair_count = try (try expanding_corr.column("xy_corr_expanding_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_pair_count);
    const expanding_cov = try (try expanding_corr.column("xy_corr_expanding_covariance")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_cov);
    const expanding_corr_values = try (try expanding_corr.column("xy_corr_expanding_correlation")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_corr_values);
    const expanding_beta = try (try expanding_corr.column("xy_corr_expanding_beta")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_beta);
    const expanding_corr_validity = try (try expanding_corr.column("xy_corr_expanding_correlation")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_corr_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_pair_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_corr_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), expanding_cov[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.6666666666666679), expanding_cov[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.625), expanding_cov[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_corr_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.9933992677987834), expanding_corr_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.9844951849708403), expanding_corr_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_beta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), expanding_beta[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.1), expanding_beta[3], 1e-12);

    var expanding_fit = try fit_table.expandingLinearFitProfile("x", "y", "xy_fit", .{ .min_periods = 2 });
    defer expanding_fit.deinit();
    try std.testing.expectEqual(@as(usize, 8), expanding_fit.width());
    const expanding_fit_count = try (try expanding_fit.column("xy_fit_expanding_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_fit_count);
    const expanding_slope = try (try expanding_fit.column("xy_fit_expanding_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_slope);
    const expanding_intercept = try (try expanding_fit.column("xy_fit_expanding_intercept")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_intercept);
    const expanding_fitted = try (try expanding_fit.column("xy_fit_expanding_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_fitted);
    const expanding_residual = try (try expanding_fit.column("xy_fit_expanding_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_residual);
    const expanding_residual_z = try (try expanding_fit.column("xy_fit_expanding_residual_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_residual_z);
    const expanding_fit_validity = try (try expanding_fit.column("xy_fit_expanding_slope")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_fit_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_fit_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_fit_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), expanding_slope[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), expanding_slope[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.1), expanding_slope[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_intercept[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), expanding_intercept[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), expanding_intercept[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), expanding_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 47.0 / 6.0), expanding_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 9.4), expanding_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), expanding_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 6.0), expanding_residual[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.4), expanding_residual[3], 1e-12);
    try std.testing.expect(std.math.isNan(expanding_residual_z[1]));
    try std.testing.expectApproxEqAbs(@as(f64, 0.7071067811865491), expanding_residual_z[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.9561828874675161), expanding_residual_z[3], 1e-12);

    var errors = try fit_table.errorProfile("y", "x", "yx");
    defer errors.deinit();
    try std.testing.expectEqual(@as(usize, 7), errors.width());
    const error_values = try (try errors.column("yx_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(error_values);
    const abs_error_values = try (try errors.column("yx_abs_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(abs_error_values);
    const squared_error_values = try (try errors.column("yx_squared_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(squared_error_values);
    const ape_values = try (try errors.column("yx_ape")).f64.toOwnedSlice(gpa);
    defer gpa.free(ape_values);
    const smape_values = try (try errors.column("yx_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(smape_values);
    const error_validity = try (try errors.column("yx_error")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(error_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false }, error_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), error_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), error_values[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), error_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), error_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), abs_error_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 25.0), squared_error_values[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), ape_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 9.0), ape_values[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), smape_values[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0 / 11.0), smape_values[2], 1e-12);

    var rolling_errors = try fit_table.rollingErrorProfile("y", "x", "yx_roll", .{ .window = 3, .min_periods = 2 });
    defer rolling_errors.deinit();
    try std.testing.expectEqual(@as(usize, 7), rolling_errors.width());
    const rolling_error_count = try (try rolling_errors.column("yx_roll_rolling_error_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(rolling_error_count);
    const rolling_mae = try (try rolling_errors.column("yx_roll_rolling_mae")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mae);
    const rolling_rmse = try (try rolling_errors.column("yx_roll_rolling_rmse")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_rmse);
    const rolling_mape = try (try rolling_errors.column("yx_roll_rolling_mape")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_mape);
    const rolling_smape = try (try rolling_errors.column("yx_roll_rolling_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(rolling_smape);
    const rolling_error_validity = try (try rolling_errors.column("yx_roll_rolling_mae")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(rolling_error_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 3, 2 }, rolling_error_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, rolling_error_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), rolling_mae[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0 / 3.0), rolling_mae[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 13.0 / 3.0), rolling_mae[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5495097567963922), rolling_rmse[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.559026084010437), rolling_rmse[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.43471156521669), rolling_rmse[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6333333333333333), rolling_mape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6305555555555555), rolling_mape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5935185185185184), rolling_mape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.9285714285714286), rolling_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.9220779220779219), rolling_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.8451548451548452), rolling_smape[3], 1e-12);

    var expanding_errors = try fit_table.expandingErrorProfile("y", "x", "yx_expand", .{ .min_periods = 2 });
    defer expanding_errors.deinit();
    try std.testing.expectEqual(@as(usize, 7), expanding_errors.width());
    const expanding_error_count = try (try expanding_errors.column("yx_expand_expanding_error_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_error_count);
    const expanding_mae = try (try expanding_errors.column("yx_expand_expanding_mae")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mae);
    const expanding_rmse = try (try expanding_errors.column("yx_expand_expanding_rmse")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_rmse);
    const expanding_mape = try (try expanding_errors.column("yx_expand_expanding_mape")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mape);
    const expanding_smape = try (try expanding_errors.column("yx_expand_expanding_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_smape);
    const expanding_error_validity = try (try expanding_errors.column("yx_expand_expanding_mae")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_error_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4, 4 }, expanding_error_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true, true }, expanding_error_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), expanding_mae[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0 / 3.0), expanding_mae[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.75), expanding_mae[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5495097567963922), expanding_rmse[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.559026084010437), expanding_rmse[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.968626966596886), expanding_rmse[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6333333333333333), expanding_mape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6305555555555555), expanding_mape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6118055555555555), expanding_mape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.9285714285714286), expanding_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.9220779220779219), expanding_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.8838661338661339), expanding_smape[3], 1e-12);

    var fast = try DeviceColumn.fromSliceWithValidity(f64, gpa, &.{ 1.0, 3.0, 2.0, 5.0, 4.0, 6.0 }, &.{ true, true, true, true, false, true }, .cpu);
    defer fast.deinit();
    var slow = try DeviceColumn.fromSlice(f64, gpa, &.{ 2.0, 2.0, 2.0, 4.0, 5.0, 0.0 }, .cpu);
    defer slow.deinit();
    var signal_table = try DeviceDataFrame.init(gpa, &.{
        .{ .name = "fast", .data = fast },
        .{ .name = "slow", .data = slow },
    });
    defer signal_table.deinit();

    var bucketed = try signal_table.bucketProfile("fast", "fast", .{ .buckets = 3, .lower_quantile = 0.34, .upper_quantile = 0.84 });
    defer bucketed.deinit();
    try std.testing.expectEqual(@as(usize, 6), bucketed.width());
    const ecdf = try (try bucketed.column("fast_ecdf")).f64.toOwnedSlice(gpa);
    defer gpa.free(ecdf);
    const bucket = try (try bucketed.column("fast_bucket")).i64.toOwnedSlice(gpa);
    defer gpa.free(bucket);
    const lower_tail = try (try bucketed.column("fast_lower_tail")).bool.toOwnedSlice(gpa);
    defer gpa.free(lower_tail);
    const upper_tail = try (try bucketed.column("fast_upper_tail")).bool.toOwnedSlice(gpa);
    defer gpa.free(upper_tail);
    const bucket_validity = try (try bucketed.column("fast_bucket")).i64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(bucket_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true, false, true }, bucket_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), ecdf[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), ecdf[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.4), ecdf[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.8), ecdf[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), ecdf[5], 1e-12);
    try std.testing.expectEqualSlices(i64, &.{ 0, 1, 0, 1, 0, 2 }, bucket);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false, false, false }, lower_tail);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false, false, true }, upper_tail);
}
