const std = @import("std");
const vectra = @import("vectra");

const DeviceLazyFrame = vectra.DeviceLazyFrame;
const lazyCollectTable = @import("dataframe_lazy_test_helpers.zig").lazyCollectTable;

test "device lazy frame collects expanding operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_plan.deinit();
    try expanding_plan.expandingProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_plan.select(&.{ "sales", "sales_expanding_count", "sales_expanding_mean", "sales_expanding_max" });
    const expanding_explain = try expanding_plan.explain(gpa);
    defer gpa.free(expanding_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_explain, "expanding_profile(sales") != null);
    var expanding = try expanding_plan.collect();
    defer expanding.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding.height());
    try std.testing.expectEqual(@as(usize, 4), expanding.width());
    const expanding_count = try (try expanding.column("sales_expanding_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(expanding_count);
    const expanding_mean = try (try expanding.column("sales_expanding_mean")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_mean);
    const expanding_max = try (try expanding.column("sales_expanding_max")).f64.toOwnedSlice(gpa);
    defer gpa.free(expanding_max);
    const expanding_validity = try (try expanding.column("sales_expanding_mean")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(expanding_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, expanding_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, expanding_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 2.5), expanding_mean[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 10.0 / 3.0), expanding_mean[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.25), expanding_mean[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), expanding_max[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), expanding_max[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), expanding_max[3], 1e-12);
}

test "device lazy frame collects expanding norm operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_norm_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_norm_plan.deinit();
    try expanding_norm_plan.expandingNormalizeProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_norm_plan.select(&.{ "sales", "sales_expanding_centered", "sales_expanding_zscore", "sales_expanding_minmax" });
    const expanding_norm_explain = try expanding_norm_plan.explain(gpa);
    defer gpa.free(expanding_norm_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_norm_explain, "expanding_normalize_profile(sales") != null);
    var expanding_norm = try expanding_norm_plan.collect();
    defer expanding_norm.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_norm.height());
    try std.testing.expectEqual(@as(usize, 4), expanding_norm.width());
    const lazy_expanding_centered = try (try expanding_norm.column("sales_expanding_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_centered);
    const lazy_expanding_zscore = try (try expanding_norm.column("sales_expanding_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_zscore);
    const lazy_expanding_minmax = try (try expanding_norm.column("sales_expanding_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_minmax);
    const lazy_expanding_norm_validity = try (try expanding_norm.column("sales_expanding_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_norm_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_norm_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0 / 3.0), lazy_expanding_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_expanding_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3363062095621219), lazy_expanding_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.4320780207890627), lazy_expanding_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_minmax[3], 1e-12);
}

test "device lazy frame collects expanding moment operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_moment_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_moment_plan.deinit();
    try expanding_moment_plan.expandingMomentProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_moment_plan.select(&.{ "sales", "sales_expanding_moment_count", "sales_expanding_m3", "sales_expanding_m4", "sales_expanding_skewness", "sales_expanding_kurtosis" });
    const expanding_moment_explain = try expanding_moment_plan.explain(gpa);
    defer gpa.free(expanding_moment_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_moment_explain, "expanding_moment_profile(sales") != null);
    var expanding_moments = try expanding_moment_plan.collect();
    defer expanding_moments.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_moments.height());
    try std.testing.expectEqual(@as(usize, 6), expanding_moments.width());
    const lazy_expanding_moment_count = try (try expanding_moments.column("sales_expanding_moment_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_moment_count);
    const lazy_expanding_m3 = try (try expanding_moments.column("sales_expanding_m3")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_m3);
    const lazy_expanding_m4 = try (try expanding_moments.column("sales_expanding_m4")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_m4);
    const lazy_expanding_skewness = try (try expanding_moments.column("sales_expanding_skewness")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_skewness);
    const lazy_expanding_kurtosis = try (try expanding_moments.column("sales_expanding_kurtosis")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_kurtosis);
    const lazy_expanding_moment_validity = try (try expanding_moments.column("sales_expanding_skewness")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_moment_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_moment_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_moment_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_m3[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.7407407407407399), lazy_expanding_m3[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.96875), lazy_expanding_m3[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0625), lazy_expanding_m4[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.6296296296296293), lazy_expanding_m4[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 21.39453125), lazy_expanding_m4[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_skewness[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.3818017741606058), lazy_expanding_skewness[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.27803055565396284), lazy_expanding_skewness[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_expanding_kurtosis[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.5), lazy_expanding_kurtosis[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.4266015512783683), lazy_expanding_kurtosis[3], 1e-12);
}

test "device lazy frame collects standardize operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var standardize_plan = try DeviceLazyFrame.init(gpa, table);
    defer standardize_plan.deinit();
    try standardize_plan.standardizeProfile("sales", "sales", .{});
    try standardize_plan.select(&.{ "sales", "sales_centered", "sales_zscore", "sales_minmax" });
    const standardize_explain = try standardize_plan.explain(gpa);
    defer gpa.free(standardize_explain);
    try std.testing.expect(std.mem.indexOf(u8, standardize_explain, "standardize_profile(sales") != null);
    var standardized = try standardize_plan.collect();
    defer standardized.deinit();
    try std.testing.expectEqual(@as(usize, 4), standardized.height());
    try std.testing.expectEqual(@as(usize, 4), standardized.width());
    const lazy_centered = try (try standardized.column("sales_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_centered);
    const lazy_zscore = try (try standardized.column("sales_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_zscore);
    const lazy_minmax = try (try standardized.column("sales_minmax")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_minmax);
    const lazy_standardized_validity = try (try standardized.column("sales_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_standardized_validity);
    try std.testing.expectEqualSlices(bool, &.{ true, true, true, true }, lazy_standardized_validity);
    try std.testing.expectApproxEqAbs(@as(f64, -2.25), lazy_centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.25), lazy_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.75), lazy_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.171700198827415), lazy_zscore[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.6509445549041194), lazy_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.39056673294247163), lazy_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.4320780207890627), lazy_zscore[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_minmax[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), lazy_minmax[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6), lazy_minmax[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_minmax[3], 1e-12);
}

test "device lazy frame collects robust operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var robust_plan = try DeviceLazyFrame.init(gpa, table);
    defer robust_plan.deinit();
    try robust_plan.robustProfile("sales", "sales", .{});
    try robust_plan.select(&.{ "sales", "sales_median_centered", "sales_mad_zscore", "sales_iqr_outlier", "sales_winsorized" });
    const robust_explain = try robust_plan.explain(gpa);
    defer gpa.free(robust_explain);
    try std.testing.expect(std.mem.indexOf(u8, robust_explain, "robust_profile(sales") != null);
    var robust = try robust_plan.collect();
    defer robust.deinit();
    try std.testing.expectEqual(@as(usize, 4), robust.height());
    try std.testing.expectEqual(@as(usize, 5), robust.width());
    const lazy_median_centered = try (try robust.column("sales_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_median_centered);
    const lazy_mad_zscore = try (try robust.column("sales_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_mad_zscore);
    const lazy_iqr_outlier = try (try robust.column("sales_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_iqr_outlier);
    const lazy_winsorized = try (try robust.column("sales_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_winsorized);
    try std.testing.expectApproxEqAbs(@as(f64, -2.0), lazy_median_centered[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -1.0), lazy_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.8993196669281089), lazy_mad_zscore[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, -0.44965983346405447), lazy_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.44965983346405447), lazy_mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3489795003921634), lazy_mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_iqr_outlier);
    try std.testing.expectEqualSlices(f64, &.{ 2.0, 3.0, 5.0, 7.0 }, lazy_winsorized);
}

test "device lazy frame collects expanding robust operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_robust_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_robust_plan.deinit();
    try expanding_robust_plan.expandingRobustProfile("sales", "sales", .{ .min_periods = 2 });
    try expanding_robust_plan.select(&.{ "sales", "sales_expanding_median_centered", "sales_expanding_mad_zscore", "sales_expanding_iqr_outlier", "sales_expanding_winsorized" });
    const expanding_robust_explain = try expanding_robust_plan.explain(gpa);
    defer gpa.free(expanding_robust_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_robust_explain, "expanding_robust_profile(sales") != null);
    var expanding_robust = try expanding_robust_plan.collect();
    defer expanding_robust.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_robust.height());
    try std.testing.expectEqual(@as(usize, 5), expanding_robust.width());
    const lazy_expanding_median_centered = try (try expanding_robust.column("sales_expanding_median_centered")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_median_centered);
    const lazy_expanding_mad_zscore = try (try expanding_robust.column("sales_expanding_mad_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mad_zscore);
    const lazy_expanding_iqr_outlier = try (try expanding_robust.column("sales_expanding_iqr_outlier")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_iqr_outlier);
    const lazy_expanding_winsorized = try (try expanding_robust.column("sales_expanding_winsorized")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_winsorized);
    const lazy_expanding_robust_validity = try (try expanding_robust.column("sales_expanding_mad_zscore")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_robust_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_robust_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_expanding_median_centered[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_expanding_median_centered[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_median_centered[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.6744897501960817), lazy_expanding_mad_zscore[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3489795003921634), lazy_expanding_mad_zscore[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.3489795003921634), lazy_expanding_mad_zscore[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_expanding_iqr_outlier);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_winsorized[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_expanding_winsorized[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_expanding_winsorized[3], 1e-12);
}
