const std = @import("std");
const boltha = @import("boltha");
const vectra = @import("vectra");

const DataFrame = vectra.DataFrame;
const DeviceColumn = vectra.DeviceColumn;
const DeviceDataFrame = vectra.DeviceDataFrame;
const DeviceLazyFrame = vectra.DeviceLazyFrame;
const DeviceDType = vectra.DeviceDType;
const DeviceValidityEncoding = vectra.DeviceValidityEncoding;
const DeviceParquetScan = vectra.DeviceParquetScan;

fn lazyCollectTable(gpa: std.mem.Allocator) !DeviceDataFrame {
    var sales = try DeviceColumn.fromSlice(f64, gpa, &.{ 2.0, 3.0, 5.0, 7.0 }, .cpu);
    defer sales.deinit();
    var units = try DeviceColumn.fromSlice(i64, gpa, &.{ 1, 2, 3, 4 }, .cpu);
    defer units.deinit();
    var active = try DeviceColumn.fromSlice(bool, gpa, &.{ true, false, true, true }, .cpu);
    defer active.deinit();

    return DeviceDataFrame.init(gpa, &.{
        .{ .name = "sales", .data = sales },
        .{ .name = "units", .data = units },
        .{ .name = "active", .data = active },
    });
}

test "device lazy frame collects crossover operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var crossover_plan = try DeviceLazyFrame.init(gpa, table);
    defer crossover_plan.deinit();
    try crossover_plan.withColumnScalar("units_f64", "sales", f64, 1.0, .sub);
    try crossover_plan.crossoverProfile("sales", "units_f64", "sales_units", .{ .periods = 1 });
    try crossover_plan.select(&.{ "sales", "units_f64", "sales_units_spread", "sales_units_ratio", "sales_units_cross_above", "sales_units_cross_below" });
    const crossover_explain = try crossover_plan.explain(gpa);
    defer gpa.free(crossover_explain);
    try std.testing.expect(std.mem.indexOf(u8, crossover_explain, "crossover_profile(sales,units_f64") != null);
    var crossover = try crossover_plan.collect();
    defer crossover.deinit();
    try std.testing.expectEqual(@as(usize, 4), crossover.height());
    try std.testing.expectEqual(@as(usize, 6), crossover.width());
    const lazy_spread = try (try crossover.column("sales_units_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_spread);
    const lazy_ratio = try (try crossover.column("sales_units_ratio")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ratio);
    const lazy_cross_above = try (try crossover.column("sales_units_cross_above")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_cross_above);
    const lazy_cross_below = try (try crossover.column("sales_units_cross_below")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_cross_below);
    const lazy_cross_validity = try (try crossover.column("sales_units_cross_above")).bool.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_cross_validity);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_cross_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_spread[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_ratio[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_ratio[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.25), lazy_ratio[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0 / 6.0), lazy_ratio[3], 1e-12);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_cross_above);
    try std.testing.expectEqualSlices(bool, &.{ false, false, false, false }, lazy_cross_below);
}

test "device lazy frame collects rolling crossover operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_crossover_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_crossover_plan.deinit();
    try rolling_crossover_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try rolling_crossover_plan.withColumnScalar("zero_sales", "sales", f64, 0.0, .mul);
    try rolling_crossover_plan.rollingCrossoverProfile("sales_minus4", "zero_sales", "sales_zero", .{ .periods = 1 }, .{ .window = 2, .min_periods = 2 });
    try rolling_crossover_plan.select(&.{ "sales", "sales_minus4", "zero_sales", "sales_zero_rolling_cross_count", "sales_zero_rolling_cross_above_count", "sales_zero_rolling_cross_below_count", "sales_zero_rolling_cross_above_rate", "sales_zero_rolling_cross_below_rate", "sales_zero_rolling_mean_abs_spread" });
    const rolling_crossover_explain = try rolling_crossover_plan.explain(gpa);
    defer gpa.free(rolling_crossover_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_crossover_explain, "rolling_crossover_profile(sales_minus4,zero_sales") != null);
    var rolling_crossover = try rolling_crossover_plan.collect();
    defer rolling_crossover.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_crossover.height());
    try std.testing.expectEqual(@as(usize, 9), rolling_crossover.width());
    const lazy_rolling_cross_count = try (try rolling_crossover.column("sales_zero_rolling_cross_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_count);
    const lazy_rolling_cross_above_count = try (try rolling_crossover.column("sales_zero_rolling_cross_above_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_above_count);
    const lazy_rolling_cross_below_count = try (try rolling_crossover.column("sales_zero_rolling_cross_below_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_below_count);
    const lazy_rolling_cross_above_rate = try (try rolling_crossover.column("sales_zero_rolling_cross_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_above_rate);
    const lazy_rolling_cross_below_rate = try (try rolling_crossover.column("sales_zero_rolling_cross_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_cross_below_rate);
    const lazy_rolling_mean_abs_spread = try (try rolling_crossover.column("sales_zero_rolling_mean_abs_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mean_abs_spread);
    const lazy_rolling_crossover_validity = try (try rolling_crossover.column("sales_zero_rolling_cross_above_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_crossover_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_cross_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_rolling_cross_above_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_rolling_cross_below_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_crossover_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_cross_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_cross_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_rolling_cross_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_cross_below_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_rolling_mean_abs_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_mean_abs_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_rolling_mean_abs_spread[3], 1e-12);
}

test "device lazy frame collects expanding crossover operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_crossover_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_crossover_plan.deinit();
    try expanding_crossover_plan.withColumnScalar("sales_minus4", "sales", f64, 4.0, .sub);
    try expanding_crossover_plan.withColumnScalar("zero_sales", "sales", f64, 0.0, .mul);
    try expanding_crossover_plan.expandingCrossoverProfile("sales_minus4", "zero_sales", "sales_zero", .{ .periods = 1 }, .{ .min_periods = 2 });
    try expanding_crossover_plan.select(&.{ "sales", "sales_minus4", "zero_sales", "sales_zero_expanding_cross_count", "sales_zero_expanding_cross_above_count", "sales_zero_expanding_cross_below_count", "sales_zero_expanding_cross_above_rate", "sales_zero_expanding_cross_below_rate", "sales_zero_expanding_mean_abs_spread" });
    const expanding_crossover_explain = try expanding_crossover_plan.explain(gpa);
    defer gpa.free(expanding_crossover_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_crossover_explain, "expanding_crossover_profile(sales_minus4,zero_sales") != null);
    var expanding_crossover = try expanding_crossover_plan.collect();
    defer expanding_crossover.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_crossover.height());
    try std.testing.expectEqual(@as(usize, 9), expanding_crossover.width());
    const lazy_expanding_cross_count = try (try expanding_crossover.column("sales_zero_expanding_cross_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_count);
    const lazy_expanding_cross_above_count = try (try expanding_crossover.column("sales_zero_expanding_cross_above_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_above_count);
    const lazy_expanding_cross_below_count = try (try expanding_crossover.column("sales_zero_expanding_cross_below_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_below_count);
    const lazy_expanding_cross_above_rate = try (try expanding_crossover.column("sales_zero_expanding_cross_above_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_above_rate);
    const lazy_expanding_cross_below_rate = try (try expanding_crossover.column("sales_zero_expanding_cross_below_rate")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_cross_below_rate);
    const lazy_expanding_mean_abs_spread = try (try expanding_crossover.column("sales_zero_expanding_mean_abs_spread")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mean_abs_spread);
    const lazy_expanding_crossover_validity = try (try expanding_crossover.column("sales_zero_expanding_cross_above_rate")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_crossover_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_cross_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_expanding_cross_above_count);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 0, 0 }, lazy_expanding_cross_below_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_crossover_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_cross_above_rate[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_expanding_cross_above_rate[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_cross_above_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_cross_below_rate[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5), lazy_expanding_mean_abs_spread[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 4.0 / 3.0), lazy_expanding_mean_abs_spread[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.75), lazy_expanding_mean_abs_spread[3], 1e-12);
}

test "device lazy frame collects fit operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var fit_plan = try DeviceLazyFrame.init(gpa, table);
    defer fit_plan.deinit();
    try fit_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try fit_plan.linearFitProfile("sales_minus1", "sales", "sales_fit", .{});
    try fit_plan.select(&.{ "sales", "sales_minus1", "sales_fit_fitted", "sales_fit_residual", "sales_fit_residual_zscore", "sales_fit_slope" });
    const fit_explain = try fit_plan.explain(gpa);
    defer gpa.free(fit_explain);
    try std.testing.expect(std.mem.indexOf(u8, fit_explain, "linear_fit_profile(sales_minus1->sales") != null);
    var fit = try fit_plan.collect();
    defer fit.deinit();
    try std.testing.expectEqual(@as(usize, 4), fit.height());
    try std.testing.expectEqual(@as(usize, 6), fit.width());
    const lazy_fitted = try (try fit.column("sales_fit_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fitted);
    const lazy_fit_residual = try (try fit.column("sales_fit_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_residual);
    const lazy_fit_residual_z = try (try fit.column("sales_fit_residual_zscore")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_residual_z);
    const lazy_fit_slope = try (try fit.column("sales_fit_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_slope);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0), lazy_fitted[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_fit_residual[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_fit_residual[3], 1e-12);
    try std.testing.expect(std.math.isNan(lazy_fit_residual_z[0]));
    try std.testing.expect(std.math.isNan(lazy_fit_residual_z[3]));
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_fit_slope[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_fit_slope[3], 1e-12);
}

test "device lazy frame collects error operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var error_plan = try DeviceLazyFrame.init(gpa, table);
    defer error_plan.deinit();
    try error_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try error_plan.errorProfile("sales", "sales_minus1", "sales_err");
    try error_plan.select(&.{ "sales", "sales_err_error", "sales_err_abs_error", "sales_err_squared_error", "sales_err_ape", "sales_err_smape" });
    const error_explain = try error_plan.explain(gpa);
    defer gpa.free(error_explain);
    try std.testing.expect(std.mem.indexOf(u8, error_explain, "error_profile(actual=sales, predicted=sales_minus1") != null);
    var lazy_errors = try error_plan.collect();
    defer lazy_errors.deinit();
    try std.testing.expectEqual(@as(usize, 4), lazy_errors.height());
    try std.testing.expectEqual(@as(usize, 6), lazy_errors.width());
    const lazy_error = try (try lazy_errors.column("sales_err_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_error);
    const lazy_abs_error = try (try lazy_errors.column("sales_err_abs_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_abs_error);
    const lazy_squared_error = try (try lazy_errors.column("sales_err_squared_error")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_squared_error);
    const lazy_ape = try (try lazy_errors.column("sales_err_ape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ape);
    const lazy_smape = try (try lazy_errors.column("sales_err_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_smape);
    try std.testing.expectEqualSlices(f64, &.{ 1.0, 1.0, 1.0, 1.0 }, lazy_error);
    try std.testing.expectEqualSlices(f64, &.{ 1.0, 1.0, 1.0, 1.0 }, lazy_abs_error);
    try std.testing.expectEqualSlices(f64, &.{ 1.0, 1.0, 1.0, 1.0 }, lazy_squared_error);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_ape[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 3.0), lazy_ape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.2), lazy_ape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0 / 7.0), lazy_ape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 3.0), lazy_smape[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 5.0), lazy_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 9.0), lazy_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 2.0 / 13.0), lazy_smape[3], 1e-12);
}

test "device lazy frame collects rolling error operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_error_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_error_plan.deinit();
    try rolling_error_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try rolling_error_plan.rollingErrorProfile("sales", "sales_minus1", "sales_err", .{ .window = 2, .min_periods = 2 });
    try rolling_error_plan.select(&.{ "sales", "sales_err_rolling_error_count", "sales_err_rolling_mae", "sales_err_rolling_rmse", "sales_err_rolling_mape", "sales_err_rolling_smape" });
    const rolling_error_explain = try rolling_error_plan.explain(gpa);
    defer gpa.free(rolling_error_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_error_explain, "rolling_error_profile(actual=sales, predicted=sales_minus1") != null);
    var rolling_errors = try rolling_error_plan.collect();
    defer rolling_errors.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_errors.height());
    try std.testing.expectEqual(@as(usize, 6), rolling_errors.width());
    const lazy_rolling_error_count = try (try rolling_errors.column("sales_err_rolling_error_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_error_count);
    const lazy_rolling_mae = try (try rolling_errors.column("sales_err_rolling_mae")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mae);
    const lazy_rolling_rmse = try (try rolling_errors.column("sales_err_rolling_rmse")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_rmse);
    const lazy_rolling_mape = try (try rolling_errors.column("sales_err_rolling_mape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_mape);
    const lazy_rolling_smape = try (try rolling_errors.column("sales_err_rolling_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_smape);
    const lazy_rolling_error_validity = try (try rolling_errors.column("sales_err_rolling_mae")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_error_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_rolling_error_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_rolling_error_validity);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_rolling_mae);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_rolling_rmse);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0) / 2.0), lazy_rolling_mape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (1.0 / 3.0 + 0.2) / 2.0), lazy_rolling_mape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (0.2 + 1.0 / 7.0) / 2.0), lazy_rolling_mape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0) / 2.0), lazy_rolling_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 5.0 + 2.0 / 9.0) / 2.0), lazy_rolling_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 9.0 + 2.0 / 13.0) / 2.0), lazy_rolling_smape[3], 1e-12);
}

test "device lazy frame collects expanding error operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_error_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_error_plan.deinit();
    try expanding_error_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try expanding_error_plan.expandingErrorProfile("sales", "sales_minus1", "sales_err", .{ .min_periods = 2 });
    try expanding_error_plan.select(&.{ "sales", "sales_err_expanding_error_count", "sales_err_expanding_mae", "sales_err_expanding_rmse", "sales_err_expanding_mape", "sales_err_expanding_smape" });
    const expanding_error_explain = try expanding_error_plan.explain(gpa);
    defer gpa.free(expanding_error_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_error_explain, "expanding_error_profile(actual=sales, predicted=sales_minus1") != null);
    var expanding_errors = try expanding_error_plan.collect();
    defer expanding_errors.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_errors.height());
    try std.testing.expectEqual(@as(usize, 6), expanding_errors.width());
    const lazy_expanding_error_count = try (try expanding_errors.column("sales_err_expanding_error_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_error_count);
    const lazy_expanding_mae = try (try expanding_errors.column("sales_err_expanding_mae")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mae);
    const lazy_expanding_rmse = try (try expanding_errors.column("sales_err_expanding_rmse")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_rmse);
    const lazy_expanding_mape = try (try expanding_errors.column("sales_err_expanding_mape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_mape);
    const lazy_expanding_smape = try (try expanding_errors.column("sales_err_expanding_smape")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_smape);
    const lazy_expanding_error_validity = try (try expanding_errors.column("sales_err_expanding_mae")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_error_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_error_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_error_validity);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_expanding_mae);
    try std.testing.expectEqualSlices(f64, &.{ 0.0, 1.0, 1.0, 1.0 }, lazy_expanding_rmse);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0) / 2.0), lazy_expanding_mape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0 + 0.2) / 3.0), lazy_expanding_mape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (0.5 + 1.0 / 3.0 + 0.2 + 1.0 / 7.0) / 4.0), lazy_expanding_mape[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0) / 2.0), lazy_expanding_smape[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0 + 2.0 / 9.0) / 3.0), lazy_expanding_smape[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, (2.0 / 3.0 + 2.0 / 5.0 + 2.0 / 9.0 + 2.0 / 13.0) / 4.0), lazy_expanding_smape[3], 1e-12);
}

test "device lazy frame collects corr operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var corr_plan = try DeviceLazyFrame.init(gpa, table);
    defer corr_plan.deinit();
    try corr_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try corr_plan.rollingCorrelationProfile("sales_minus1", "sales", "sales_corr", .{ .window = 2, .min_periods = 2 });
    try corr_plan.select(&.{ "sales", "sales_corr_rolling_pair_count", "sales_corr_rolling_covariance", "sales_corr_rolling_correlation", "sales_corr_rolling_beta" });
    const corr_explain = try corr_plan.explain(gpa);
    defer gpa.free(corr_explain);
    try std.testing.expect(std.mem.indexOf(u8, corr_explain, "rolling_correlation_profile(sales_minus1,sales") != null);
    var rolling_corr = try corr_plan.collect();
    defer rolling_corr.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_corr.height());
    try std.testing.expectEqual(@as(usize, 5), rolling_corr.width());
    const lazy_pair_count = try (try rolling_corr.column("sales_corr_rolling_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_pair_count);
    const lazy_covariance = try (try rolling_corr.column("sales_corr_rolling_covariance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_covariance);
    const lazy_correlation = try (try rolling_corr.column("sales_corr_rolling_correlation")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_correlation);
    const lazy_beta = try (try rolling_corr.column("sales_corr_rolling_beta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_beta);
    const lazy_corr_validity = try (try rolling_corr.column("sales_corr_rolling_correlation")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_corr_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_pair_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_corr_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_covariance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_covariance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_covariance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_correlation[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_correlation[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_correlation[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_beta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_beta[3], 1e-12);
}

test "device lazy frame collects expanding corr operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_corr_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_corr_plan.deinit();
    try expanding_corr_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try expanding_corr_plan.expandingCorrelationProfile("sales_minus1", "sales", "sales_corr", .{ .min_periods = 2 });
    try expanding_corr_plan.select(&.{ "sales", "sales_corr_expanding_pair_count", "sales_corr_expanding_covariance", "sales_corr_expanding_correlation", "sales_corr_expanding_beta" });
    const expanding_corr_explain = try expanding_corr_plan.explain(gpa);
    defer gpa.free(expanding_corr_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_corr_explain, "expanding_correlation_profile(sales_minus1,sales") != null);
    var expanding_corr = try expanding_corr_plan.collect();
    defer expanding_corr.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_corr.height());
    try std.testing.expectEqual(@as(usize, 5), expanding_corr.width());
    const lazy_expanding_pair_count = try (try expanding_corr.column("sales_corr_expanding_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_pair_count);
    const lazy_expanding_covariance = try (try expanding_corr.column("sales_corr_expanding_covariance")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_covariance);
    const lazy_expanding_correlation = try (try expanding_corr.column("sales_corr_expanding_correlation")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_correlation);
    const lazy_expanding_beta = try (try expanding_corr.column("sales_corr_expanding_beta")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_beta);
    const lazy_expanding_corr_validity = try (try expanding_corr.column("sales_corr_expanding_correlation")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_corr_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_pair_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_corr_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_expanding_covariance[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.5555555555555554), lazy_expanding_covariance[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.6875), lazy_expanding_covariance[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_correlation[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_correlation[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_correlation[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_beta[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_beta[3], 1e-12);
}

test "device lazy frame collects expanding fit operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var expanding_fit_plan = try DeviceLazyFrame.init(gpa, table);
    defer expanding_fit_plan.deinit();
    try expanding_fit_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try expanding_fit_plan.expandingLinearFitProfile("sales_minus1", "sales", "sales_fit", .{ .min_periods = 2 });
    try expanding_fit_plan.select(&.{ "sales", "sales_fit_expanding_pair_count", "sales_fit_expanding_slope", "sales_fit_expanding_intercept", "sales_fit_expanding_fitted", "sales_fit_expanding_residual" });
    const expanding_fit_explain = try expanding_fit_plan.explain(gpa);
    defer gpa.free(expanding_fit_explain);
    try std.testing.expect(std.mem.indexOf(u8, expanding_fit_explain, "expanding_linear_fit_profile(sales_minus1->sales") != null);
    var expanding_fit = try expanding_fit_plan.collect();
    defer expanding_fit.deinit();
    try std.testing.expectEqual(@as(usize, 4), expanding_fit.height());
    try std.testing.expectEqual(@as(usize, 6), expanding_fit.width());
    const lazy_expanding_fit_count = try (try expanding_fit.column("sales_fit_expanding_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_count);
    const lazy_expanding_fit_slope = try (try expanding_fit.column("sales_fit_expanding_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_slope);
    const lazy_expanding_fit_intercept = try (try expanding_fit.column("sales_fit_expanding_intercept")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_intercept);
    const lazy_expanding_fit_fitted = try (try expanding_fit.column("sales_fit_expanding_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_fitted);
    const lazy_expanding_fit_residual = try (try expanding_fit.column("sales_fit_expanding_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_residual);
    const lazy_expanding_fit_validity = try (try expanding_fit.column("sales_fit_expanding_slope")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_expanding_fit_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 3, 4 }, lazy_expanding_fit_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_expanding_fit_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_slope[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_slope[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_slope[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_intercept[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_expanding_fit_intercept[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_expanding_fit_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_expanding_fit_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_expanding_fit_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_fit_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_expanding_fit_residual[3], 1e-12);
}

test "device lazy frame collects rolling fit operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var rolling_fit_plan = try DeviceLazyFrame.init(gpa, table);
    defer rolling_fit_plan.deinit();
    try rolling_fit_plan.withColumnScalar("sales_minus1", "sales", f64, 1.0, .sub);
    try rolling_fit_plan.rollingLinearFitProfile("sales_minus1", "sales", "sales_fit", .{ .window = 2, .min_periods = 2 });
    try rolling_fit_plan.select(&.{ "sales", "sales_fit_rolling_pair_count", "sales_fit_rolling_slope", "sales_fit_rolling_intercept", "sales_fit_rolling_fitted", "sales_fit_rolling_residual" });
    const rolling_fit_explain = try rolling_fit_plan.explain(gpa);
    defer gpa.free(rolling_fit_explain);
    try std.testing.expect(std.mem.indexOf(u8, rolling_fit_explain, "rolling_linear_fit_profile(sales_minus1->sales") != null);
    var rolling_fit = try rolling_fit_plan.collect();
    defer rolling_fit.deinit();
    try std.testing.expectEqual(@as(usize, 4), rolling_fit.height());
    try std.testing.expectEqual(@as(usize, 6), rolling_fit.width());
    const lazy_fit_count = try (try rolling_fit.column("sales_fit_rolling_pair_count")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_count);
    const lazy_rolling_fit_slope = try (try rolling_fit.column("sales_fit_rolling_slope")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_slope);
    const lazy_rolling_fit_intercept = try (try rolling_fit.column("sales_fit_rolling_intercept")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_intercept);
    const lazy_rolling_fit_fitted = try (try rolling_fit.column("sales_fit_rolling_fitted")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_fitted);
    const lazy_rolling_fit_residual = try (try rolling_fit.column("sales_fit_rolling_residual")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_rolling_fit_residual);
    const lazy_fit_validity = try (try rolling_fit.column("sales_fit_rolling_slope")).f64.validity.?.toOwnedSlice(gpa);
    defer gpa.free(lazy_fit_validity);
    try std.testing.expectEqualSlices(i64, &.{ 1, 2, 2, 2 }, lazy_fit_count);
    try std.testing.expectEqualSlices(bool, &.{ false, true, true, true }, lazy_fit_validity);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_slope[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_slope[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_slope[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_intercept[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_intercept[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_rolling_fit_intercept[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 3.0), lazy_rolling_fit_fitted[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 5.0), lazy_rolling_fit_fitted[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 7.0), lazy_rolling_fit_fitted[3], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_fit_residual[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_fit_residual[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.0), lazy_rolling_fit_residual[3], 1e-12);
}

test "device lazy frame collects bucket operations" {
    const gpa = std.testing.allocator;
    var table = try lazyCollectTable(gpa);
    defer table.deinit();
    var bucket_plan = try DeviceLazyFrame.init(gpa, table);
    defer bucket_plan.deinit();
    try bucket_plan.bucketProfile("sales", "sales", .{ .buckets = 2, .lower_quantile = 0.25, .upper_quantile = 0.75 });
    try bucket_plan.select(&.{ "sales", "sales_ecdf", "sales_bucket", "sales_lower_tail", "sales_upper_tail" });
    const bucket_explain = try bucket_plan.explain(gpa);
    defer gpa.free(bucket_explain);
    try std.testing.expect(std.mem.indexOf(u8, bucket_explain, "bucket_profile(sales") != null);
    var bucketed = try bucket_plan.collect();
    defer bucketed.deinit();
    try std.testing.expectEqual(@as(usize, 4), bucketed.height());
    try std.testing.expectEqual(@as(usize, 5), bucketed.width());
    const lazy_ecdf = try (try bucketed.column("sales_ecdf")).f64.toOwnedSlice(gpa);
    defer gpa.free(lazy_ecdf);
    const lazy_bucket = try (try bucketed.column("sales_bucket")).i64.toOwnedSlice(gpa);
    defer gpa.free(lazy_bucket);
    const lazy_lower_tail = try (try bucketed.column("sales_lower_tail")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_lower_tail);
    const lazy_upper_tail = try (try bucketed.column("sales_upper_tail")).bool.toOwnedSlice(gpa);
    defer gpa.free(lazy_upper_tail);
    try std.testing.expectApproxEqAbs(@as(f64, 0.25), lazy_ecdf[0], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.5), lazy_ecdf[1], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 0.75), lazy_ecdf[2], 1e-12);
    try std.testing.expectApproxEqAbs(@as(f64, 1.0), lazy_ecdf[3], 1e-12);
    try std.testing.expectEqualSlices(i64, &.{ 0, 0, 1, 1 }, lazy_bucket);
    try std.testing.expectEqualSlices(bool, &.{ true, false, false, false }, lazy_lower_tail);
    try std.testing.expectEqualSlices(bool, &.{ false, false, true, true }, lazy_upper_tail);
}
